const fs = require("fs");
const path = require("path");

const root = path.join(__dirname, "..");
const storyPath = path.join(root, "stories.json");
const topics = [
  "Fantasy/stories", "Nature and animals", "World affairs", "Everyday life", "History",
  "Science", "Famous books", "Mystery and adventure", "Travel and culture", "People and biography",
];
const entry = (level, topic, title, text, subtopic, contentType, sourceWork = null) => ({
  level, topic, title, text: text.trim(), subtopic, contentType, sourceWork,
});

const entries = [
  // Level 1
  entry(1, "Fantasy/stories", "A Star in the Bread Tin", `Lio opens an old bread tin. A small star is inside. It is cold and weak. Lio puts the tin near a warm lamp. He gives the star a drop of rain. At night, the star grows bright. It flies out the window and takes its place in the sky.`, "small magic and kindness", "narrative-fiction"),
  entry(1, "Nature and animals", "A Bat Lets Go", `A bat rests with its head down. Its feet hold the roof of a cave. When the bat wants to fly, it lets go. It falls a short way and opens its wings. The open space helps it begin to fly. Later, it comes back and hangs again.`, "bat movement and rest", "explanatory-nonfiction"),
  entry(1, "World affairs", "One Ramp for the Hall", `The town hall has three steps. Some people cannot get inside. The town has little money. A group draws a safe ramp. A builder gives wood, and neighbors help with the work. The ramp opens on Friday. It helps people with chairs, carts, and tired legs.`, "access and public buildings", "explanatory-nonfiction"),
  entry(1, "Everyday life", "Tea for the Early Driver", `Mika wakes before her father. He must drive a bus at dawn. She puts tea in his blue cup and bread on a plate. The tea is too hot, so she adds a little cold water. Her father smiles. They sit in the quiet kitchen for five minutes.`, "family and morning routines", "narrative-fiction"),
  entry(1, "History", "Words Pressed into Clay", `Long ago, people wrote on wet clay. They used a cut reed to press small marks into it. Some marks helped people count food, work, and goods. The clay could dry and become hard. These old tablets now help us learn about life in ancient towns.`, "cuneiform and record keeping", "historical-narrative"),
  entry(1, "Science", "The Moon Has No Lamp", `The Moon looks bright at night, but it does not make its own light. Light from the Sun reaches the Moon. Some of that light comes back toward Earth. We see the bright part. As the Moon moves around Earth, the bright shape we see can change.`, "moonlight and observation", "explanatory-nonfiction"),
  entry(1, "Famous books", "Heidi Returns to the Mountain", `Heidi lives in the city with Clara, but she misses the mountain. She misses the wind, the goats, and her grandfather. At last, she goes home. The fresh air and open land make her happy. Later, Clara visits. With help and courage, Clara learns to stand and walk.`, "home, health, and friendship", "classic-retelling", "Heidi"),
  entry(1, "Mystery and adventure", "Mud on the Clean Floor", `A line of mud crosses the clean floor. It begins at the door and ends by a chair. No shoes are there. Hana looks under the chair. A small dog is asleep with dirty paws. The dog came in through its own little door. Hana finds a towel.`, "home mysteries", "mystery-fiction"),
  entry(1, "Travel and culture", "A Seat by the Small Harbor", `Eli walks beside a small harbor. Fishers pull in their boats. A woman sells warm soup from a cart. Eli buys one bowl and sits on a low wall. He does not know anyone there. Soon, an old man points to the sunset and shares his bread.`, "harbors and shared meals", "travel-vignette"),
  entry(1, "People and biography", "Pia Paints Safe Paths", `Pia works near a school. Cars move fast on the road. She asks children where they cross. Then she paints bright paths with the town workers. She also puts signs near the gate. Drivers slow down. Pia keeps watching the road and changes one path after rain fills it.`, "road safety and community work", "fictional-biography"),

  // Level 2
  entry(2, "Fantasy/stories", "The Umbrella Tree", `A tree behind Nia's house grows umbrellas instead of fruit. Most are black, but one is yellow. Nia takes it on a rainy day. The umbrella lifts her above the road and carries her to school. After class, she returns it to the tree. A new green umbrella is already growing beside it.`, "enchanted plants and travel", "narrative-fiction"),
  entry(2, "Nature and animals", "Water Saved by a Tortoise", `A desert tortoise lives where rain is rare. It digs a deep home under the ground to escape great heat. After rain, it can drink a lot of water. Its body can keep water in the bladder and use some of it later. A frightened tortoise may lose this supply, so people should watch from far away.`, "desert survival", "explanatory-nonfiction"),
  entry(2, "World affairs", "The Shared Street Light", `Two villages meet at a dark road. Each village says the other should pay for a street light. A nurse explains that people from both places use the road at night. The leaders agree to share the cost. One village buys the lamp, and the other pays for power and repairs.`, "shared infrastructure", "explanatory-nonfiction"),
  entry(2, "Everyday life", "A Different Birthday Cake", `Jon wants to bake a cake for his friend. She cannot eat milk or eggs. His first cake falls apart. He calls her brother and asks for help. They use oil, fruit, and plant milk. The second cake is soft and good. Jon writes the new recipe down before the party begins.`, "food and inclusion", "narrative-fiction"),
  entry(2, "History", "A Map Made from Sticks", `People of the Marshall Islands made special charts from sticks and shells. The sticks showed how ocean waves moved around islands. The shells could mark islands. Sailors learned by watching the sea and traveling with skilled teachers. A chart was not always carried on a trip. Much of the map lived in the sailor's memory.`, "Micronesian navigation", "historical-narrative"),
  entry(2, "Science", "Colors in a Drop of Rain", `Sunlight may look white, but it holds many colors. When light enters a drop of water, it bends. The light also bounces inside the drop and bends again as it leaves. The colors do not all bend in the same way. Many drops together can make a rainbow across the sky.`, "light and rainbows", "explanatory-nonfiction"),
  entry(2, "Famous books", "Black Beauty Finds a Gentle Home", `Black Beauty tells the story of his life as a horse. Some owners are kind, but others use painful equipment or work him too hard. He meets horses who have also suffered. After illness and difficult years, Beauty is sold to people who treat him gently. He ends his life in a safe green field.`, "animal welfare and empathy", "classic-retelling", "Black Beauty"),
  entry(2, "Mystery and adventure", "The Note in the Empty Jar", `A note appears inside an empty glass jar at the cafe. It says, “Look under the red seat.” Bo checks every red chair but finds nothing. Then he sees a child holding a red toy bus. Under its seat is a tiny paper heart. The note was part of a birthday game.`, "message mysteries", "mystery-fiction"),
  entry(2, "Travel and culture", "Rain at the Hill Market", `Rain begins at a hill market. Sellers cover fruit and cloth with wide sheets. A visitor named Mara helps hold one corner. When the rain stops, the seller gives her a cup of hot tea. Mara buys a small blue bag and learns the word for “thank you.”`, "markets and weather", "travel-vignette"),
  entry(2, "People and biography", "Dani Opens a Tool Box", `Dani repairs chairs and tables. Many neighbors throw things away because they have no tools. Dani puts simple tools in a box at the library. People may borrow them with a card. On Saturdays, Dani shows how to use each tool safely. Soon, broken chairs begin to return to use.`, "repair and shared resources", "fictional-biography"),

  // Level 3
  entry(3, "Fantasy/stories", "The Clock That Needed a Story", `A clock in the station stopped at eight every night. The keeper cleaned it and changed its parts, but nothing helped. One evening, a child read a story while waiting for a train. The clock began to move again. From then on, travelers left short stories beside it. The clock kept good time as long as someone read before eight.`, "stories and enchanted objects", "narrative-fiction"),
  entry(3, "Nature and animals", "A Meadow Under the Sea", `Seagrass is a flowering plant that grows under shallow sea water. Its leaves slow the water and give small animals places to hide. Its roots and the mud around them can hold carbon for a long time. Boats, dirty water, and work along the coast can damage these meadows. Protecting seagrass supports both sea life and the climate.`, "seagrass ecosystems", "explanatory-nonfiction"),
  entry(3, "World affairs", "The Clinic's Three Languages", `A town clinic gave health forms in only one language. Some patients signed papers they did not understand. The clinic could not hire three full-time translators, so it trained a phone team shared with nearby towns. It also rewrote common forms in plain language. Patients still asked questions, but fewer left without knowing what to do next.`, "language access and health", "explanatory-nonfiction"),
  entry(3, "Everyday life", "The Coat with Two Owners", `Sam found a warm coat in a secondhand shop. A name was written inside one pocket. He wore the coat all winter, then found a photo hidden behind the cloth. Sam took it back to the shop. The former owner came for the picture and told him about the coat's first journey. Sam kept the coat, but now knew part of its story.`, "secondhand objects and memory", "narrative-fiction"),
  entry(3, "History", "Books Carried Out of Timbuktu", `Timbuktu became an important center of learning and trade. Families kept many old handwritten books in private collections. During conflict in 2012, local people moved thousands of manuscripts to safer places. Some books were lost or damaged, but many survived because people packed and carried them away in secret. Their work protected part of Africa's written history.`, "manuscripts and cultural protection", "historical-narrative"),
  entry(3, "Science", "Water Keeps Moving", `Water rises from seas, lakes, soil, and plants as vapor. Higher in the air, it cools and forms clouds. Rain or snow brings it back to the ground. Some water flows into rivers, while some enters the soil or freezes. The same water can move through this cycle many times, although it may stay in one place for a long period.`, "the water cycle", "explanatory-nonfiction"),
  entry(3, "Famous books", "Anne Chooses Green Gables", `Anne Shirley expects a new family, but Marilla and Matthew wanted a boy to help on their farm. Anne talks too much, makes mistakes, and has a fierce imagination. Matthew quickly loves her, while Marilla learns more slowly. Through school, friendship, and loss, Anne grows. When she must choose, she stays near Green Gables to support Marilla.`, "belonging and growing up", "classic-retelling", "Anne of Green Gables"),
  entry(3, "Mystery and adventure", "The Train Ticket with No Town", `Iris finds an old train ticket marked with a town that is not on any map. The date is only ten years old. She checks old newspapers and learns that the town changed its name after two villages joined. The ticket is not from a lost place. It records a name that people used for only six months.`, "maps and local history mysteries", "mystery-fiction"),
  entry(3, "Travel and culture", "Bread from the Shared Oven", `In a mountain town, Noor sees families carrying bowls of dough to one large oven. Each loaf has a different mark pressed on top, so people can find their own bread later. The baker controls the heat while neighbors wait and talk. Noor buys a loaf but also stays to learn why a simple oven can become a meeting place.`, "food and community spaces", "travel-vignette"),
  entry(3, "People and biography", "Arun Records the Quiet Hours", `Arun works in a town library. Students need quiet, but parents with young children also need a welcoming place. He records when each group visits and changes the room plan. One room stays quiet in the afternoon. Another has soft mats and picture books. Arun's notes help the same building serve people with different needs.`, "libraries and inclusive design", "fictional-biography"),

  // Level 4
  entry(4, "Fantasy/stories", "The Door That Opened on Tuesdays", `Every Tuesday, a blue door appeared behind the bakery. Mina finally opened it and found a garden where each flower held a forgotten sound. One rang like her old school bell. Another carried her grandmother's laugh. The gardener warned her to take only one sound, because memories grew weak when moved. Mina chose the laugh, carried it home in a paper cup, and played it for her mother. On Wednesday, the door was gone, but the sound remained.`, "memory and enchanted places", "narrative-fiction"),
  entry(4, "Nature and animals", "Pines That Wait for Fire", `Some lodgepole pine cones stay tightly closed for years. A strong resin seals their scales. During a forest fire, heat can open these cones and release the seeds. The fire may also clear shade and return useful material to the soil. Young pines can then grow where older trees once stood. Fire is still dangerous, and not every fire helps a forest. Yet in lodgepole pine country, fire has long been part of the way the land changes and begins again.`, "lodgepole pine and fire", "explanatory-nonfiction"),
  entry(4, "World affairs", "The Bridge Used by Two Towns", `A river divided two towns, but people crossed it every day for work and school. When the old bridge needed repairs, the towns argued about the bill. Students counted how many travelers came from each side. Shop owners listed the money that visitors spent. The councils used this information to share the cost, while a regional fund paid for safer rails. The agreement was not perfect, but both towns accepted it because the bridge served them both.`, "regional cooperation and infrastructure", "explanatory-nonfiction"),
  entry(4, "Everyday life", "The Week without a Washing Machine", `The washing machine stopped on Sunday, just before Lia's busy week. She first wanted to buy a new one at once. Her neighbor suggested checking the filter. They found a button and several coins blocking the water. Lia cleaned the part, but the machine still would not start. A repair worker replaced one small switch the next day. The week taught Lia that fixing an object can take patience, yet may cost less and create less waste than replacing it.`, "repair and household choices", "narrative-fiction"),
  entry(4, "History", "Counting Grain on Clay", `In ancient Mesopotamia, people pressed signs into clay tablets. Many surviving tablets record ordinary business rather than grand stories. They list grain, animals, workers, and payments. A reed cut into a wedge shape made the marks now called cuneiform. Because clay was common and could become hard, some records lasted for thousands of years. These small accounts help historians study how temples, farms, and households organized work, even when the writers never expected distant readers to see them.`, "cuneiform accounting", "historical-narrative"),
  entry(4, "Science", "A Lever Lifts the Stone", `A class tried to lift a heavy garden stone. Pulling with their hands did not work. Their teacher placed a strong board under the stone and rested it on a small block. The block became the turning point, or fulcrum. When the students pushed down on the long end, the short end lifted the stone. A lever does not remove the work needed, but it can trade distance for force. Moving the fulcrum changes how much force the students must use.`, "levers and mechanical advantage", "explanatory-nonfiction"),
  entry(4, "Famous books", "Phileas Fogg Makes a Wager", `Phileas Fogg lives by a strict schedule in London. After hearing that new routes may allow a journey around the world in eighty days, he makes a large wager that he can do it. He leaves at once with his servant, Passepartout. Trains, ships, delays, and a mistaken detective complicate the trip. Fogg also rescues Aouda, who joins them. He seems to return too late, but crossing the date line has saved a day. He reaches his club in time and wins.`, "time, travel, and loyalty", "classic-retelling", "Around the World in Eighty Days"),
  entry(4, "Mystery and adventure", "The Bell beneath the Path", `Each evening, a faint bell sounded under the park path. Tess searched after rain and found a metal ring beside a drain. Pulling it opened a narrow cover. Below lay an old service tunnel, but entering alone was unsafe. A city worker came with lights and maps. Inside, they found a loose cable striking a pipe whenever the water pump began. The hidden bell was not a warning from the past. It was a small fault that helped the workers find a larger leak.`, "urban clues and safe investigation", "mystery-fiction"),
  entry(4, "Travel and culture", "The Ferry with a Library Shelf", `On a long ferry ride, Ken expected only gray water and hard seats. Near the stairs, he found a shelf of books in several languages. A sign invited travelers to take one and leave another. Ken chose a picture book about the islands they were passing. A deck worker showed him the lighthouse drawn on one page. Before leaving, Ken placed his own mystery novel on the shelf. The crossing became a quiet exchange between people who might never meet.`, "ferries and book exchange", "travel-vignette"),
  entry(4, "People and biography", "Lea Measures the Bus Stops", `Lea designs bus routes for a growing town. Complaints arrive from every neighborhood, but the town cannot add a bus everywhere. She rides each route, measures waiting times, and speaks with passengers who work early or use walking aids. Her first plan looks efficient on a map but leaves hospital workers without a morning service. Lea changes it. The final route is not the shortest; it connects more people to places they truly need.`, "public transport planning", "fictional-biography"),

  // Level 5
  entry(5, "Fantasy/stories", "The Museum of Unfinished Wishes", `At the edge of the city stood a museum that accepted wishes people had abandoned. Niko visited expecting broken toys, but the rooms held stranger things: half-learned songs, unopened letters, and plans for journeys. A guide explained that an unfinished wish was not always a failure. Sometimes a person had changed; sometimes fear had stopped them. Niko found his own childhood wish to build a boat. He did not take it home. Instead, he wrote a new card: “Learn to repair the boats already on the river.” The old wish faded, and the new one began to glow.`, "choices and unfinished dreams", "narrative-fiction"),
  entry(5, "Nature and animals", "Living Light in the Ocean", `In dark water, many organisms can produce light through chemical reactions. This ability is called bioluminescence. Tiny drifting organisms may flash when water moves around them. Some animals use light to attract prey, confuse attackers, or communicate. In the deep ocean, where sunlight cannot reach, living light is especially common. It is not the same as light reflected from a fish's silver body. The organism makes the light itself, often with the help of a light-producing molecule and an enzyme. Scientists study these systems both to understand ocean life and to develop useful tools for research.`, "marine bioluminescence", "explanatory-nonfiction"),
  entry(5, "World affairs", "The Island's Fresh-Water Plan", `A small island depended on rain for most of its fresh water. Longer dry periods placed farms, hotels, and homes in competition. The council first proposed strict limits for everyone, but residents argued that equal limits were not always fair. Farmers needed water to protect food crops, while hotels could reuse water from sinks for gardens. The revised plan repaired leaking pipes, priced heavy use more highly, protected a basic household supply, and helped farms install drip systems. No single measure solved the shortage. Together, conservation, reuse, and public reporting made the island better prepared for the next dry season.`, "water governance and adaptation", "explanatory-nonfiction"),
  entry(5, "Everyday life", "A Calendar for Caring", `After their father hurt his leg, three adult siblings promised to help. Good intentions soon became confused visits, missed medicine, and repeated shopping. Mei created a shared calendar, but their father disliked feeling like a project. The family met again and asked what support he actually wanted. They agreed on two meal deliveries, one ride to therapy, and a weekly call to review changes. They also left free days when he could manage alone. The calendar became useful only after it reflected his choices, not just the helpers' schedules.`, "family care and coordination", "narrative-fiction"),
  entry(5, "History", "Steering by Stars and Swells", `For generations, Polynesian navigators traveled across wide stretches of the Pacific without modern instruments. They learned the rising and setting points of stars, the path of the Sun, winds, clouds, birds, and the movement of ocean swells. This knowledge was carried through teaching and repeated voyages. In the twentieth century, the Hawaiian canoe Hōkūleʻa helped renew public knowledge of traditional wayfinding. Its voyages showed that skilled navigators could guide a canoe by close observation and a trained memory. The achievement joined inherited knowledge with a modern cultural revival rather than presenting navigation as a lost mystery.`, "Polynesian wayfinding", "historical-narrative"),
  entry(5, "Science", "A Practice Alarm for the Immune System", `A vaccine prepares the immune system before a dangerous infection arrives. Different vaccines work in different ways, but they present the body with a safe form, piece, or set of instructions linked to a germ. Immune cells respond and develop a memory of that target. Later, if the real germ enters the body, the response can begin faster and reduce the chance of serious disease. Vaccines do not create a perfect shield for every person. Their protection can vary and may weaken over time, which is why some vaccines require more than one dose or a later booster.`, "vaccines and immune memory", "explanatory-nonfiction"),
  entry(5, "Famous books", "Mowgli Hears the Law of the Jungle", `Mowgli grows up among wolves after the tiger Shere Khan threatens him. Baloo the bear teaches him the law of the jungle, while Bagheera the panther protects and advises him. Mowgli learns the languages and customs of many animals, yet his place remains uncertain. Some wolves fear Shere Khan and turn against the boy. With fire, which the animals fear, Mowgli defeats the tiger's challenge. His victories do not end his struggle between two worlds. He must decide how to live among animals who raised him and humans who share his kind.`, "belonging, law, and courage", "classic-retelling", "The Jungle Book"),
  entry(5, "Mystery and adventure", "The Photograph Taken after Closing", `A museum camera recorded a photograph at midnight, although the building was locked and empty. The image showed a pale shape beside a glass case. Omar checked the alarm log, then compared the photograph with earlier nights. The shape appeared only when a street-cleaning truck passed outside. Its bright lamp shone through a high window and reflected from two pieces of glass. A loose display card added the outline that looked like a face. The mystery was solved, but the test revealed that light could reach a sensitive painting. Staff changed the shade the next morning.`, "optical clues and museum safety", "mystery-fiction"),
  entry(5, "Travel and culture", "A Song Learned on the Night Train", `Rosa boarded a night train with a phrasebook and too much luggage. In her compartment, a family was teaching a child a traditional song for a wedding. Rosa could not understand the words, but she recognized the repeated rhythm and tapped it on the table. The grandmother slowly taught her the chorus. At dawn, the family left at a small station and wrote the song's title in Rosa's notebook. Months later, she found a recording and learned its meaning. The memory remained valuable because it began with listening, not with pretending that one short encounter made her an expert.`, "music and respectful cultural exchange", "travel-vignette"),
  entry(5, "People and biography", "Mateo Builds a Cooler Classroom", `Mateo teaches science in a school where afternoon heat makes concentration difficult. Air-conditioning is too costly for every room. He records indoor and outdoor temperatures, maps the strongest sunlight, and asks students where they feel most comfortable. With local builders, he adds shade cloth, reflective roof paint, window vents, and two trees in safe locations. The changes do not make hot days cold, but the rooms cool more quickly after lunch. Mateo publishes the measurements, including the days when the plan works poorly, so other schools can judge which ideas suit their own buildings.`, "school heat adaptation", "fictional-biography"),

  // Level 6
  entry(6, "Fantasy/stories", "The City That Borrowed Tomorrow", `Every winter, the city borrowed one warm day from the coming summer. People used it for repairs, outdoor meals, and washing blankets. The bargain seemed harmless until summer arrived one day shorter each year. Gardens failed before their fruit ripened, and migrating birds reached an autumn that had come too soon. A young clerk named Ivo found the records and called a public meeting. The city could not return the missing days at once. It stopped borrowing and agreed to receive a week of sudden heat each spring until the debt was paid. Admitting the cost disrupted daily life, but hiding it would have stolen even more from the future.`, "future costs and collective choices", "narrative-fiction"),
  entry(6, "Nature and animals", "Salmon Carry the Sea Inland", `Pacific salmon hatch in fresh water, travel to the ocean, and later return to rivers to reproduce. Along this journey, they connect habitats that may appear separate. Predators such as bears and birds eat salmon and leave remains on riverbanks. Nutrients that the fish gained at sea can then enter streams, forests, and other food webs. Young salmon also feed larger fish and wildlife. Dams, warm water, damaged habitat, fishing pressure, and changing ocean conditions can affect different populations in different ways. Protecting salmon therefore involves more than counting adult fish; it requires attention to the rivers, estuaries, ocean, and human communities linked by their migration.`, "salmon and connected ecosystems", "explanatory-nonfiction"),
  entry(6, "World affairs", "The Vaccine Freezer at the Border", `A health team had enough vaccine for two remote districts, but a broken bridge delayed the refrigerated truck. One district suggested taking the whole shipment before it warmed. The other argued that its outbreak was growing faster. Rather than decide by political pressure, the teams shared current case reports, storage capacity, travel times, and the number of people at greatest risk. They sent a smaller cold box by boat to the nearer district and used the repaired route for the rest. The solution depended on accurate local data and cooperation. It also showed why delivering medicine requires transport, storage, trained staff, and trust—not merely a supply at a national warehouse.`, "health logistics and equitable allocation", "explanatory-nonfiction"),
  entry(6, "Everyday life", "The Subscription Nobody Used", `Nora noticed that small monthly charges were quietly draining her account. A music service, a meal plan, and cloud storage each seemed inexpensive when she joined. Together they cost more than she expected. She listed every repeating payment and marked the last time she had used it. Canceling everything would have been easy, but not wise: the storage protected family photographs, and the music service was used daily. She ended the meal plan, lowered one storage tier after deleting duplicates, and set a review date three months ahead. The exercise was not about refusing every convenience. It was about making repeated costs visible enough to choose deliberately.`, "subscriptions and household budgeting", "narrative-fiction"),
  entry(6, "History", "Timbuktu's Libraries of Many Homes", `From roughly the thirteenth to the sixteenth centuries, Timbuktu became an important center of trade and Islamic learning. Scholars copied and studied works on religion, law, language, mathematics, astronomy, and other subjects. Many manuscripts remained not in one central library but in family collections passed through generations. This pattern helped preserve a rich written record, although heat, insects, neglect, theft, and conflict all posed dangers. During the 2012 crisis in Mali, custodians and residents moved many manuscripts away from risk. Their actions remind us that cultural heritage survives through ordinary care as well as famous buildings and international projects.`, "Timbuktu scholarship and manuscript culture", "historical-narrative"),
  entry(6, "Science", "Why the City Stays Hot after Sunset", `Cities often become warmer than nearby rural areas, a pattern known as the urban heat-island effect. Dark roofs and paved surfaces absorb solar energy during the day and release heat later. Closely spaced buildings can reduce airflow, while fewer trees mean less shade and less cooling from water leaving plant leaves. Vehicles, air conditioners, and industry add heat as well. The effect varies across a city; neighborhoods with more pavement and fewer trees may face greater exposure. Reflective roofs, shade, vegetation, and thoughtful street design can help, but planners must measure local conditions because a solution useful in one climate or neighborhood may work differently elsewhere.`, "urban heat islands", "explanatory-nonfiction"),
  entry(6, "Famous books", "Edmond Dantès Returns under Another Name", `Edmond Dantès is a young sailor about to marry Mercédès when jealous enemies falsely accuse him of political betrayal. Imprisoned in the Château d'If, he meets Abbé Faria, who educates him and reveals the location of a hidden treasure. After escaping, Dantès finds the fortune and returns as the Count of Monte Cristo. He carefully rewards old friends and punishes those who destroyed his life. Yet his plans harm innocent people as well as the guilty. By the end, revenge no longer appears perfectly controlled, and Dantès must recognize limits to his judgment.`, "revenge, justice, and mercy", "classic-retelling", "The Count of Monte Cristo"),
  entry(6, "Mystery and adventure", "The Lighthouse Log with Two Midnights", `A lighthouse log contained two entries marked midnight on the same date. One described calm water; the other reported a sudden storm. Selene suspected that someone had altered the record to hide a wreck. She compared the handwriting, tide table, and radio notes. Both entries were genuine. That night, the country had moved its clocks back at the end of daylight-saving time, so the hour from midnight to one occurred twice. The storm began during the second midnight. The log keeper had added no time-zone label, turning a routine clock change into a historical puzzle. Selene recommended recording times in a single standard for future emergencies.`, "time records and evidence", "mystery-fiction"),
  entry(6, "Travel and culture", "The Courtyard behind the Music Shop", `While visiting an old port city, Ben followed the sound of string instruments into a narrow shop. The owner repaired instruments used in several local music traditions. Ben asked whether he could photograph everything. The owner invited him first to sit in the courtyard and hear an apprentice practice. She explained how one instrument's wood, tuning, and playing style had changed as merchants and migrants crossed the region. Ben bought no souvenir. Instead, he paid for the small evening performance and wrote down the musicians' names correctly. Travel gave him access to a story, but respect required attention to who was telling it and how they wished it shared.`, "music, migration, and respectful travel", "travel-vignette"),
  entry(6, "People and biography", "Sora Maps the Missing Trees", `Sora works as a community health researcher. Residents of one district report hotter walks and fewer shaded bus stops than wealthier areas receive. She combines street-temperature readings with a map of trees, building materials, and pedestrian routes. The first map contains errors because young trees are hidden beneath larger ones in aerial images. Sora trains volunteers to check each block on foot and pays them for their time. The revised study shows where shade would protect the most-used routes, but it also identifies broken drinking fountains and unsafe crossings. Her report recommends several measures rather than treating tree planting as the only answer.`, "community mapping and heat equity", "fictional-biography"),

  // Level 7
  entry(7, "Fantasy/stories", "Mara Learns the Storm Language", `In Mara's village, storms arrived speaking a language no one understood. Their thunder broke windows, and their rain flooded fields without warning. Mara discovered that each gust repeated a pattern, so she spent years recording pauses, pressure, and pitch. Eventually she translated one message: the storms were not angry; mountains had blocked the ancient route they used to release their water. The village offered to cut a pass, but Mara refused to damage the forest on uncertain evidence. Instead, engineers restored wetlands along the river while she continued listening. Floods became less severe. Mara never proved that the storms understood the work, yet the village learned to combine an unusual warning with careful observation rather than treating either wonder or doubt as a complete answer.`, "language, evidence, and environmental change", "narrative-fiction"),
  entry(7, "Nature and animals", "A Compass inside an Animal", `Many animals travel accurately across places with few obvious landmarks. Experiments indicate that some can detect Earth's magnetic field and use it for orientation or navigation. The ability, often called magnetoreception, has been studied in animals including birds, sea turtles, fish, and insects. It does not mean that every individual follows a magnetic signal like a metal compass. Animals may combine magnetic information with stars, sunlight, smells, currents, and learned routes. Researchers also continue to investigate the biological mechanisms involved. Evidence for magnetic guidance can come from changing the field around an animal and observing whether its preferred direction changes, while controlling for other cues that might explain the result.`, "magnetoreception and migration", "explanatory-nonfiction"),
  entry(7, "World affairs", "When the River Crosses a Border", `An upstream country planned a dam to provide electricity and reduce seasonal flooding. Downstream farmers feared that altered flows would harm crops and fisheries. Early talks failed because each government presented only the benefits or costs within its own border. A joint technical group then compared several operating plans using shared rainfall, energy, irrigation, and ecosystem data. The countries agreed on minimum flows, advance notice of major releases, and a process for reviewing drought conditions. Disagreement did not disappear, and the data could not settle questions of fairness by itself. Still, transparent measurements narrowed the factual disputes and made the political choices clearer. River cooperation required institutions that could keep working after a single agreement was signed.`, "transboundary water cooperation", "explanatory-nonfiction"),
  entry(7, "Everyday life", "The Family Archive on Four Phones", `When Alma tried to assemble a birthday film, she discovered that her family's photographs were scattered across four phones, two old laptops, and several messaging apps. Some files had been copied so often that nobody knew which version was original. She first gathered everything onto one drive, then created a second backup in a separate place. Rather than naming thousands of files by hand, she sorted them by year and event, kept the original dates, and recorded who had supplied uncertain images. Family members could request corrections or private folders. The archive remained incomplete, but it became understandable and safer. Alma also learned that preservation is not simply saving more copies; it requires organization, access rules, and a plan for future formats.`, "personal archives and digital care", "narrative-fiction"),
  entry(7, "History", "A Student's Clay Exercise", `Not every cuneiform tablet was a royal order or a commercial account. Some were the work of students learning to become scribes in ancient Mesopotamia. A teacher might write a sign, word list, or model text, and the learner copied it into soft clay. Uneven marks and repeated lines can reveal the practice behind literacy. Because writing required knowledge of many signs and conventions, scribal education was demanding and valuable. Archaeologists must still interpret such tablets cautiously: a school exercise that copies an old text does not necessarily describe the student's own time. Its physical form, handwriting, find location, and relationship to other tablets all help distinguish classroom practice from a document used in administration or public life.`, "scribal education in Mesopotamia", "historical-narrative"),
  entry(7, "Science", "Continents on Moving Plates", `Earth's rigid outer shell is divided into tectonic plates that move slowly over the softer layer beneath them. Their motion is measured in centimeters per year, yet over millions of years it rearranges oceans and continents. Where plates separate, new crust may form; where they converge, one plate may sink beneath another or mountains may rise; where they slide past, stress can produce earthquakes. Plate tectonics unites evidence from the shapes of continents, fossils, rocks, the ocean floor, earthquake patterns, volcanoes, and modern measurements. The theory does not allow scientists to predict the exact time of an earthquake. It does explain why many earthquakes and volcanoes cluster near plate boundaries and helps researchers estimate regional hazards.`, "plate tectonics and geologic hazards", "explanatory-nonfiction"),
  entry(7, "Famous books", "Jane Eyre Refuses an Unequal Choice", `Orphaned Jane Eyre grows up under cruelty, then studies and teaches at Lowood School. As a governess at Thornfield Hall, she falls in love with its owner, Edward Rochester. Their wedding is stopped when Jane learns that Rochester already has a living wife, Bertha Mason, hidden in the house. Although Rochester asks Jane to stay, she leaves rather than accept a life that violates her conscience. After hardship, she finds relatives and gains financial independence. Jane later returns to Rochester after Thornfield has burned and Bertha has died. Their reunion matters because Jane can now choose freely, with property and family of her own, rather than enter the relationship as a dependent employee.`, "conscience, autonomy, and equality", "classic-retelling", "Jane Eyre"),
  entry(7, "Mystery and adventure", "The Map Drawn in Condensation", `Every cold morning, lines appeared on the inside of a greenhouse window and vanished as the glass warmed. They resembled a map leading from the door to a locked cabinet. Priya photographed the pattern before touching anything. The lines matched marks left by transparent tape that had once held signs against the glass. Dust and oil changed where water condensed, revealing the old adhesive boundaries. Yet one rectangle was new. Inside the cabinet, staff found a leaking container whose vapor had settled nearby and altered the surface. The apparent treasure map was partly an innocent trace of past displays and partly evidence of a current safety problem. Careful observation solved both without forcing the lock.`, "surface traces and safe inquiry", "mystery-fiction"),
  entry(7, "Travel and culture", "The Guide Who Revised the Tour", `A city guide named Elif had long repeated a popular story about a stone tower. According to the tale, one heroic architect had built it alone after receiving a dream. A visiting historian politely showed her tax records naming dozens of craftspeople, suppliers, and laborers. Elif worried that removing the legend would disappoint travelers. Instead, she revised the tour. She presented the dream as a later tradition, then used the records to describe the coordinated work behind the building. Visitors still enjoyed the legend, but they also heard about quarry workers, rope makers, cooks, and apprentices. The tour became richer when uncertainty and evidence were part of the story rather than threats to it.`, "heritage interpretation and evidence", "travel-vignette"),
  entry(7, "People and biography", "Noor Designs a Fair Queue", `Noor manages appointments at a crowded legal-aid center. The old system served people in arrival order, which seemed fair but failed clients with urgent deadlines, disabilities, or jobs they could not leave for hours. She interviews staff and visitors, then tests a system that combines scheduled times, a small urgent queue, and clear walk-in capacity. At first, staff classify too many cases as urgent. Noor narrows the criteria and reviews decisions weekly. Waiting times fall, yet she also tracks who abandons the queue before receiving help. Her work shows that a fair service cannot be judged only by average speed; it must examine whose needs remain invisible in the average.`, "service design and procedural fairness", "fictional-biography"),

  // Level 8
  entry(8, "Fantasy/stories", "The Cartographer of Possible Roads", `Eren's maps did not show roads that existed. They displayed routes a traveler might have taken if one earlier choice had changed. A pale line marked the apprenticeship he had refused; another led toward a friendship lost through silence. Wealthy clients paid to view their brightest alternatives, but many returned bitter, treating possibility as proof that their present lives were mistakes. Eren began adding uncertainty to every map: washed-out bridges, unseen storms, joys that could not be predicted. One client demanded a perfect route to a happier life. Eren handed her a blank sheet and explained that the future was the only territory his instrument could not survey. She accused him of fraud, yet later asked him to map the choices still available from where she stood. His craft became less profitable and more honest.`, "counterfactual choices and uncertainty", "narrative-fiction"),
  entry(8, "Nature and animals", "A Community Built on a Fallen Whale", `When a whale dies and sinks to the deep seafloor, its body can create a concentrated source of food in an environment where large meals are rare. Mobile scavengers may first remove soft tissue. Smaller animals then use remaining organic material and the enriched sediment. Later, microbes can break down fats in the bones, supporting chemical processes that feed specialized communities. Scientists often describe these changes as stages, although the timing and species vary with depth, location, whale size, and local conditions. A whale fall does not nourish the entire deep ocean, but it can support a local community for years and provide habitat as well as energy. Studying these sites helps researchers understand how resources move through deep-sea ecosystems and how isolated habitats may be connected.`, "whale falls and deep-sea ecology", "explanatory-nonfiction"),
  entry(8, "World affairs", "The Price of Moving a Coastline", `A low-lying coastal district faced repeated flooding. Engineers could strengthen the seawall for a limited period, while planners argued that some homes would eventually need to move. Residents feared that “managed retreat” was a polite name for abandonment. The local government created a voluntary purchase program, but early offers reflected old property values and ignored renters, informal businesses, and cultural ties. After protest, the plan added relocation counseling, rental support, community-site funding, and an independent appeal process. Even then, no formula could measure every loss. Adaptation required scientific estimates of risk, yet legitimacy depended on who shaped the choices, how benefits and burdens were distributed, and whether people had credible options rather than a single decision imposed on them.`, "climate adaptation and planned relocation", "explanatory-nonfiction"),
  entry(8, "Everyday life", "The Meeting That Became an Email", `The neighborhood committee held a weekly meeting because it had always done so. Twelve people traveled across town to hear announcements that were already written down. When Riku proposed replacing most meetings with a short email, several members worried that quieter residents would lose their chance to speak. The group experimented for six weeks. Routine updates went into an accessible message with a phone option, while decisions requiring discussion remained on a monthly agenda. Each proposal stayed open for written comments before a vote. Attendance improved, but one member without reliable internet still struggled, so the library offered a printed copy and reply form. The lesson was not that meetings were wasteful or email was efficient. Communication worked when its form matched the task and did not quietly exclude participants.`, "meetings, access, and group decisions", "narrative-fiction"),
  entry(8, "History", "Reading the Ocean in Bent Sticks", `Navigators in the Marshall Islands developed stick charts that represented relationships among islands, ocean swells, and wave patterns. Thin ribs or sticks could be bent and tied to indicate how waves approached, crossed, or changed near land; shells sometimes marked islands. The charts were teaching instruments within a wider system of embodied knowledge. A navigator had to feel a canoe's motion, read winds and clouds, and remember routes learned from experts. Treating a chart as though it were a modern street map misses its purpose. Many were studied before a voyage rather than consulted at sea, and different forms served different instructional roles. Museum examples preserve remarkable objects, but the knowledge cannot be reduced to an object separated from the people, language, practice, and ocean experience that made it meaningful.`, "Marshallese stick charts and navigation", "historical-narrative"),
  entry(8, "Science", "Editing DNA with a Guided Tool", `Genome editing refers to methods that allow researchers to change DNA at selected locations. One widely used system, CRISPR-Cas9, combines a guide molecule that can recognize a target sequence with a protein that cuts DNA. The cell then repairs the break, and researchers can use that process to disrupt, remove, or sometimes replace genetic material. The phrase “molecular scissors” is helpful but incomplete: targeting can fail, unintended changes can occur, and delivering the components to the right cells is a major challenge. Editing cells in a patient also raises different questions from editing embryos in ways that could be inherited. Laboratory success therefore does not by itself establish medical safety, social acceptance, or ethical justification. Each proposed use requires evidence about benefits, risks, alternatives, consent, and oversight.`, "genome editing and CRISPR", "explanatory-nonfiction"),
  entry(8, "Famous books", "Odysseus Returns to Ithaca", `After the Trojan War, Odysseus spends years struggling to return to Ithaca. He faces the Cyclops, Circe, the Sirens, shipwrecks, and the anger of Poseidon. His cleverness repeatedly saves him, but pride and poor choices also deepen his losses. At home, suitors consume his household while pressuring Penelope to remarry. She delays them through her own intelligence, weaving by day and undoing the work at night. Odysseus finally arrives in disguise, tests the loyalty of those around him, and reveals himself during the contest of the bow. He kills the suitors and reunites with Penelope after she tests his knowledge of their marriage bed. The poem's homecoming is therefore not merely an arrival; it is a difficult recovery of identity, trust, and order.`, "homecoming, identity, and cunning", "classic-retelling", "The Odyssey"),
  entry(8, "Mystery and adventure", "The Dataset with a Perfect Pattern", `A research team studying bird calls found an astonishing result: every seventh recording contained the same rare note. The pattern looked too regular to be natural, and one scientist suspected fabricated data. Before accusing anyone, Leila traced the files from field recorder to analysis software. The note occurred at the exact moment an automated system announced battery status through a tiny speaker. A software update had activated the message, and the microphone captured it whenever long sessions reached a fixed interval. The recordings were genuine, but the measurement process had introduced a signal that resembled the behavior under study. The team documented the fault, repeated affected observations, and kept the original files. The mystery demonstrated why surprising regularity should prompt an audit of instruments and workflow as well as scrutiny of people.`, "data integrity and instrument artifacts", "mystery-fiction"),
  entry(8, "Travel and culture", "A Recipe with No Single Homeland", `In a harbor town, Salma joined a cooking lesson advertised as the home of an “ancient unchanged recipe.” The instructor laughed at the phrase. The dish used a grain grown locally, a spice carried through older trade routes, a vegetable introduced more recently, and a cooking tool adapted from another region. Families disagreed about the proper balance, and each claimed a grandmother as authority. Rather than searching for one original version, the class compared how migration, price, faith, climate, and available fuel shaped different methods. Salma left with a recipe, but also with permission to label it accurately: one family's present practice, learned in a particular town. Food could express belonging without needing to be pure, timeless, or owned by a single story.`, "foodways, trade, and cultural change", "travel-vignette"),
  entry(8, "People and biography", "Imani Tests the Flood Warning", `Imani develops public warnings for a river city. A technically accurate alert once failed because it arrived late, used unfamiliar terms, and offered no clear action. She brings together forecasters, disability advocates, translators, emergency workers, and residents from frequently flooded streets. They test short messages through text, radio, sirens, and door-to-door networks. One version reaches many phones but cannot be understood by screen readers; another warns people without identifying safe routes. Imani revises the system and runs exercises during calm weather. She publishes delivery failures as well as successes. Her role is not to predict every flood alone. It is to turn uncertain forecasts into timely, accessible choices while preserving trust about what officials know, what they do not know, and when guidance may change.`, "risk communication and accessible warnings", "fictional-biography"),

  // Level 9
  entry(9, "Fantasy/stories", "The Ministry of Unspoken Consequences", `The ministry occupied a windowless building where civil servants recorded consequences that laws had produced but never named. One ledger listed the hours caregivers lost while proving eligibility for support. Another measured how a noise rule displaced musicians into poorer districts. An analyst named Sen discovered that officials treated the ledgers as confidential embarrassments rather than evidence. He proposed publishing them beside every new policy. Ministers objected that no decision could survive a list of harms. Sen replied that silence did not remove harm; it merely selected who would notice it. The first public ledger caused outrage, but it also revealed competing costs. Extending clinic hours improved access for shift workers while exhausting nurses unless staffing rose. Citizens could no longer demand a benefit without seeing its conditions. The ministry did not become an oracle. Its records were incomplete, and some effects resisted measurement. Yet policy debates changed when unspoken consequences gained names, uncertainty ranges, and people responsible for reviewing them.`, "policy tradeoffs and accountability", "narrative-fiction"),
  entry(9, "Nature and animals", "Peatlands: Slow Growth, Large Stores", `Peatlands form where waterlogged conditions slow the complete decay of plant material. Over long periods, partly decomposed matter accumulates as peat, storing substantial quantities of carbon. Although peatlands cover only a modest share of Earth's land surface, global assessments indicate that they hold more carbon than all the world's forests combined. Their value is not limited to carbon: many regulate water, support distinctive species, and sustain local livelihoods. Drainage for farming, forestry, or extraction exposes peat to oxygen, accelerating decomposition and releasing greenhouse gases; dry peat can also burn. Restoration often involves raising water levels, but it is not as simple as flooding every site. Land rights, current uses, nutrient conditions, methane emissions, and the original ecosystem all matter. Protecting intact peat is generally easier than rebuilding the slow processes that created it.`, "peatlands and carbon storage", "explanatory-nonfiction"),
  entry(9, "World affairs", "Debt after the Cyclone", `A cyclone destroyed roads, clinics, and power lines in a country already spending a large share of public revenue on debt service. Emergency loans could finance reconstruction quickly, but would increase future payments. Grants were limited, and waiting for ideal terms would prolong disruption. The finance ministry published three scenarios: rapid borrowing, slower rebuilding with fewer loans, and a mixed plan tied to temporary debt relief. Civil-society groups added costs the models had omitted, including unpaid care, lost schooling, and unequal insurance coverage. Creditors and the government eventually accepted a package combining grants, concessional loans, and delayed payments, with public reporting of contracts. The arrangement did not erase the disaster's economic burden. It made the tradeoffs more visible and reduced the risk that urgent procurement would become permanently opaque. Recovery depended both on immediate resources and on whether future budgets could still fund essential services.`, "disaster recovery and sovereign debt", "explanatory-nonfiction"),
  entry(9, "Everyday life", "A Recommendation Engine at Dinner", `Jonas's family used a meal-planning app to reduce weekday arguments. At first, its recommendations felt almost magical. After several months, however, the same inexpensive dishes appeared repeatedly, while a family member's allergy was occasionally overlooked. Jonas examined the settings and discovered that cost and past clicks dominated the ranking. Meals they had eaten without enthusiasm counted as approval because nobody recorded dissatisfaction. The family began rating recipes, entering dietary limits as fixed constraints, and reserving one evening for a human choice outside the system. Their food budget remained stable while variety improved. More importantly, they stopped describing the app as objective. It optimized the signals it received, including misleading ones, according to priorities someone had encoded. The tool was valuable once the family treated its output as a proposal to inspect rather than a decision that had already been made.`, "algorithmic recommendations in daily life", "narrative-fiction"),
  entry(9, "History", "A Tablet without Its Excavation Story", `A cuneiform tablet may contain a readable list of grain, names, or legal obligations, yet its historical value depends on more than translated words. Archaeological context can connect it to a building, layer, archive, and neighboring objects. When a tablet reaches a collection without a documented find location, scholars may still analyze its clay, script, language, and content, but many relationships have been lost. Unprovenanced objects also raise ethical and legal concerns because undocumented trade can encourage looting and destroy sites. The Library of Congress collection illustrates both the attraction of ancient written records and the need to describe what is and is not known about their histories. Responsible study separates confident reading from inference, records gaps rather than inventing origins, and considers how an object's modern path affects the knowledge researchers can recover from it.`, "provenance and ancient documents", "historical-narrative"),
  entry(9, "Science", "Listening to Space-Time", `Gravitational waves are ripples in space-time produced by accelerating masses, especially extremely compact objects moving violently. Einstein's general theory of relativity predicted them, but their effects at Earth are extraordinarily small. The LIGO detectors use long perpendicular arms and laser interferometry to measure tiny differences in distance as a wave passes. In 2015, researchers made the first direct observation of gravitational waves from two merging black holes, after extensive checks against noise and instrument faults. Detection does not resemble hearing sound through air; scientists convert the measured signal into audio frequencies for analysis and communication. Each event can reveal properties of objects that may emit little or no light. Confidence depends on matched detectors, statistical analysis, physical models, calibration, and the willingness to investigate signals that could arise from Earth rather than the cosmos.`, "gravitational-wave detection", "explanatory-nonfiction"),
  entry(9, "Famous books", "The War of the Worlds without Human Victory", `In H. G. Wells's novel, cylinders from Mars fall in southern England and release technologically superior invaders. Their heat-rays and fighting machines overwhelm soldiers, cities, and assumptions about human dominance. The unnamed narrator is separated from his wife and moves through a society breaking under panic. His brother witnesses refugees struggling to escape by sea. Human weapons achieve little, and heroic battle does not decide the invasion. The Martians eventually die because they lack resistance to earthly microorganisms. This ending reverses the position humans often imagine for themselves: the conquerors are defeated by organisms too small to notice. The novel combines suspense with criticism of empire, complacency, and social order. Its power lies partly in denying readers a comfortable victory earned by courage or superior morality.`, "invasion, empire, and human vulnerability", "classic-retelling", "The War of the Worlds"),
  entry(9, "Mystery and adventure", "The Anonymous Reviewer's Footnotes", `A historian received an anonymous peer review that cited three obscure letters missing from every archive catalog. The quotations supported the reviewer's criticism perfectly, raising suspicion that the documents had been invented. Instead of trying to identify the reviewer, the historian asked the journal editor to verify the sources confidentially. The editor located photographs from a private family collection, but their dates had been assigned from an envelope that might not belong to them. Handwriting and paper supported a broad period, not the precise year claimed. The historian revised the argument, acknowledged the uncertain dates, and requested permission for the images to enter a public archive. The episode produced no villain. It exposed a chain in which genuine evidence acquired false precision through an undocumented assumption. Solving the puzzle meant protecting anonymous review while demanding that extraordinary citations remain inspectable.`, "source verification and scholarly ethics", "mystery-fiction"),
  entry(9, "Travel and culture", "The Festival after the Cameras Leave", `A winter festival became famous after short videos drew thousands of visitors. Hotels prospered, but narrow streets filled beyond safe capacity, residents could not reach homes, and sacred parts of the ceremony were filmed despite requests for privacy. Organizers introduced timed entry, designated viewing areas, and a ban on commercial recording during certain rites. Critics called the rules unfriendly; others argued they arrived too late. The town also directed a portion of ticket income toward sanitation, performers, and year-round cultural education. Visitor numbers fell slightly, while average stays grew longer. No policy removed the tension between welcome, livelihood, worship, and local control. The revised festival worked better because success was no longer measured only by attendance. Organizers tracked crowd safety, resident experience, performer compensation, waste, and whether the tradition remained meaningful to the community that practiced it.`, "festival tourism and community governance", "travel-vignette"),
  entry(9, "People and biography", "Elias Audits the Helpful Algorithm", `Elias leads an audit of software used to prioritize housing inspections. The system appears efficient because it finds violations more often than random selection. Yet most historical complaints came from neighborhoods where residents trusted the reporting process and had reliable internet access. Areas with poor reporting therefore look safer than they are. Elias tests performance across districts, examines missing data, and organizes independent building surveys. He recommends using the model to identify questions, not automatically rank every property. Inspectors add information about building age and tenant vulnerability, while residents gain ways to report offline and appeal ignored cases. The redesigned process is slower on paper, but it uncovers hazards the original metric concealed. Elias's most important finding is institutional: an accurate calculation can still reproduce an incomplete view of the world if the system collecting its inputs is unequal.`, "algorithmic auditing and housing safety", "fictional-biography"),

  // Level 10
  entry(10, "Fantasy/stories", "The Republic of Reversible Decisions", `The republic prided itself on a machine that could reverse any public decision within one year. Failed bridges vanished, misspent funds returned, and unjust rules unwrote themselves. Because error seemed temporary, legislators began voting before investigations were complete. Citizens postponed objections, assuming harm could be erased. Then a reversed factory closure restored the building and payroll but not the skills workers had abandoned, the river species lost during pollution, or the trust broken by secret negotiations. The machine had reversed formal acts, not every consequence that followed them. A constitutional scholar named Vale proposed a distinction: decisions might be legally reversible while their effects remained socially, ecologically, or psychologically path dependent. The republic limited the machine to emergencies and required ordinary policies to include evidence, consultation, review dates, and repair funds. Opponents complained that government had become slow again. Vale agreed. Reversibility, she argued, should make experimentation safer, not make care unnecessary. The machine remained powerful only after the republic stopped confusing the undoing of a command with the restoration of a world.`, "reversibility, governance, and path dependence", "narrative-fiction"),
  entry(10, "Nature and animals", "Wolves, Elk, and the Limits of a Simple Cascade", `After wolves were restored to Yellowstone National Park in 1995 and 1996, researchers documented changes involving elk, scavengers, competing predators, and vegetation. The return of a top predator can influence an ecosystem through direct predation and through changes in prey distribution or behavior, a process often discussed as a trophic cascade. Popular accounts sometimes reduce Yellowstone's history to a single claim that wolves “changed the rivers.” The evidence is more complicated. Elk numbers and browsing changed, and some willow or aspen stands recovered, but climate, water availability, fire, beavers, hunting outside the park, and the spatial pattern of animal use also matter. Effects vary by location and time, and scientists continue to debate their relative strength. The restoration remains a powerful example of ecological connection precisely because it resists a tidy one-cause story: predators can reshape relationships, yet they operate within landscapes already governed by many interacting forces.`, "Yellowstone wolves and trophic cascades", "explanatory-nonfiction"),
  entry(10, "World affairs", "The Carbon Market and the Forest Village", `A company sought to offset emissions by paying to protect a forest used by several villages. Satellite images showed declining tree cover, so the project promised credits for preventing future loss. Residents asked harder questions: Who owned the carbon claim? Would protecting one tract move logging elsewhere? What would have happened without the project? A credible program needed a defensible baseline, monitoring over time, safeguards against leakage, and a plan for carbon that might later be released by fire or policy change. It also needed meaningful consent and a fair distribution of revenue. The final agreement recognized community land use, funded independent monitoring, and held part of the credits in reserve against future loss. Even so, offsets did not make the buyer's emissions physically disappear. The project could support conservation, but its climate value depended on additional, durable results, while the fastest certainty still came from reducing emissions at their source.`, "carbon offsets and forest governance", "explanatory-nonfiction"),
  entry(10, "Everyday life", "The Inheritance of Digital Accounts", `After her uncle died, Celia found careful instructions for the house, bank, and funeral but none for his digital life. Subscription charges continued, family photographs sat behind device passwords, and an online shop still accepted orders. She resisted the temptation to use every credential she discovered. Access rights, privacy, service terms, and inheritance law did not necessarily align, especially where messages involved living correspondents. With the estate's legal adviser, she identified essential accounts, preserved devices without altering them, contacted providers through formal processes, and documented each decision. The family recovered shared photographs but declined to read private correspondence merely because technical access might have been possible. Celia later prepared her own digital plan: an inventory, designated contacts, backup locations, and explicit wishes about deletion and memorialization. The task was less about mastering passwords than distinguishing property, memory, obligation, and privacy after a person can no longer clarify consent.`, "digital estates and privacy", "narrative-fiction"),
  entry(10, "History", "Saving Timbuktu's Manuscripts without Freezing Their Meaning", `Timbuktu's manuscript heritage includes works transmitted through families, libraries, scholars, markets, and religious institutions over centuries. During the 2012 conflict in Mali, custodians moved many manuscripts from danger, while some monuments and documents were damaged or destroyed. Subsequent conservation has involved local experts and international partners, but preservation is not simply a technical matter of stabilizing paper. Cataloging can improve access while exposing sensitive information; moving collections can protect them while separating them from the communities that gave them meaning. Digitization creates copies but requires equipment, description, long-term storage, and decisions about who may view what. Responsible preservation therefore combines physical care, security, documentation, training, community authority, and sustainable access. The rescue stories are extraordinary, yet focusing only on dramatic evacuation can obscure the quieter generations of family stewardship that made it possible for manuscripts to survive long enough to be rescued.`, "Timbuktu manuscript preservation", "historical-narrative"),
  entry(10, "Science", "A Measurement Is More Than a Number", `Reporting a measurement without its uncertainty can imply a precision the experiment did not achieve. Uncertainty is not simply a confession of error; it expresses the range of values reasonably attributable to the quantity under stated conditions. A result may be affected by instrument resolution, calibration, environmental variation, sampling, the measurement model, and repeated observations. Some components can be evaluated statistically, while others rely on certificates, prior data, or reasoned estimates. These contributions are combined according to how they influence the result, and an expanded uncertainty may be reported with a stated coverage factor. The procedure does not guarantee that every source of bias has been found. It makes assumptions and evidence inspectable so another person can compare results or repeat the work. More decimal places cannot substitute for better knowledge: a scale displaying thousandths is not necessarily accurate to a thousandth, and agreement between two instruments may only show that they share the same uncorrected bias.`, "measurement uncertainty and scientific reporting", "explanatory-nonfiction"),
  entry(10, "Famous books", "The Karamazov Brothers and the Burden of Choice", `Fyodor Pavlovich Karamazov is a negligent father whose sons embody conflicting temperaments. Dmitri is passionate and indebted; Ivan is intellectually tormented by suffering and faith; Alyosha seeks compassionate action under the guidance of the elder Zosima. Their half-brother Smerdyakov occupies a resentful, ambiguous place in the household. When Fyodor is murdered, suspicion falls on Dmitri, who had publicly threatened him and desperately needed money. The trial converts fragments of truth into a persuasive but incomplete story. Smerdyakov tells Ivan that he committed the murder, exploiting ideas he believed Ivan had licensed, then dies by suicide. Dmitri is convicted despite not being the killer. The novel does not reduce responsibility to the hand that performs an act. Through argument, confession, doubt, and care, it asks how desire, example, neglect, and freedom bind people to one another without eliminating individual choice. Alyosha's final appeal to remember kindness offers no solution to the family's tragedy, but it points toward responsibility practiced through attention rather than abstract certainty.`, "moral responsibility, faith, and family", "classic-retelling", "The Brothers Karamazov"),
  entry(10, "Mystery and adventure", "The Archive That Corrected Itself", `Researchers noticed that scanned newspapers in a public archive were changing between visits. Dates shifted, names became more legible, and occasionally a paragraph disappeared. Rumors spread that officials were rewriting the historical record. Archivist Jun compared file hashes, optical-character-recognition output, image masters, and the preservation log. Most changes came from a new recognition model applied to the same page images; the underlying scans had not changed. One missing paragraph, however, resulted from an automated crop that mistook a dark column border for the edge of the page. A final discrepancy revealed that two editions had been cataloged under one identifier decades earlier. Jun restored versioned access, separated image evidence from machine-generated text, and displayed correction histories. The archive had never literally corrected itself. Multiple layers—physical page, scan, crop, transcription, and catalog record—had been presented as one object. The mystery ended when the interface exposed those layers instead of concealing revision behind a seamless search box.`, "digital archives and version evidence", "mystery-fiction"),
  entry(10, "Travel and culture", "Returning an Ancestor's Recording", `A university archive held songs recorded in a mountain community nearly a century earlier. The cylinders were fragile, and catalog cards used names imposed by an outside collector. When a restoration project invited descendants to hear the recordings, some recognized singers, places, and ceremonial material that should not circulate publicly. The institution had legal possession, but legal control did not settle questions of cultural authority. Archivists created high-quality preservation copies, corrected descriptions with community knowledge, restricted sensitive tracks, and provided local copies in usable formats. They also recorded disagreement rather than pretending the community spoke with one voice. A visitor to the region could now hear selected songs through a locally designed exhibit, while other recordings remained limited. The project treated return not as a single transfer of an object but as an ongoing relationship involving consent, context, technical care, and the right to decide when access is not the highest value.`, "sound archives, repatriation, and consent", "travel-vignette"),
  entry(10, "People and biography", "Ada Writes the Failure Report First", `Ada directs a nonprofit that tests low-cost water sensors. Funding proposals reward confident promises, yet field devices fail when mud covers probes, batteries degrade, or networks disappear during storms. Before the next pilot, she writes a “failure report” describing conditions that would make the project misleading or unsafe. Engineers add manual sampling, calibration checks, replaceable parts, and visible warnings when data are stale. Community technicians receive pay and authority to reject readings that conflict with direct observation. The pilot detects several leaks, but it also misses one contaminated well. Ada publishes both outcomes, explains the limits of the sample, and postpones expansion until the cause is understood. Donors initially dislike the cautious report; local partners trust it. Her leadership does not celebrate failure for its own sake. It converts foreseeable weaknesses into design requirements and unexpected failures into evidence, refusing to let a polished average conceal the particular households whom a system failed to protect.`, "transparent leadership and responsible technology", "fictional-biography"),
];

// Keep required subject terms while preventing names and specialist vocabulary from
// crowding out the familiar language expected at each level.
const vocabularyEdits = {
  "One Ramp for the Hall": [
    [/A group draws a safe ramp\./, "A group draws a safe path."],
    [/A builder gives wood, and neighbors help with the work\./, "A worker gives wood, and people nearby help with the work."],
    [/The ramp opens on Friday\./, "The new ramp opens on Friday."],
    [/chairs, carts, and tired legs/, "chairs with wheels, baby cars, and people with tired legs"],
  ],
  "Tea for the Early Driver": [
    [/Mika wakes before her father\./, "Mika gets up before her father."],
    [/Her father smiles\./, "Her father is happy."],
    [/They sit/, "Mika and her father sit"],
  ],
  "Heidi Returns to the Mountain": [
    [/she misses the mountain/, "Heidi wants to be back on the mountain"],
    [/She misses the wind, the goats, and her grandfather\./, "She wants the wind, the animals, and her grandfather."],
    [/Clara learns to stand and walk/, "Clara is able to stand and walk"],
  ],
  "Mud on the Clean Floor": [
    [/crosses the clean floor/, "goes across the clean floor"],
    [/dirty paws/, "dirty feet"],
    [/Hana finds a towel\./, "Hana finds a cloth and cleans the floor."],
  ],
  "A Seat by the Small Harbor": [
    [/Fishers pull in their boats\./, "People pull in their fishing boats."],
    [/Eli buys one bowl/, "Eli buys one bowl"],
    [/from a cart/, "from a small stand"],
    [/Soon, an old man/, "Soon, Eli sees an old man who"],
  ],
  "The Umbrella Tree": [
    [/behind Nia's house/, "behind the house of Nia"],
    [/Most are black, but one is yellow\./, "Most are black, but Nia sees one yellow umbrella."],
    [/on a rainy day/, "on a wet day"],
    [/The umbrella lifts her above the road and carries her to school\./, "It takes her above the road and carries her to school."],
    [/A new green umbrella/, "Nia sees a new green umbrella"],
  ],
  "Water Saved by a Tortoise": [
    [/It digs a deep home/, "The tortoise makes a deep home"],
    [/A frightened tortoise/, "An afraid tortoise"],
    [/keep water in the bladder and use some of it later/, "hold water in a body part called the bladder and use some of that water later"],
    [/so people should watch from far away/, "so people should leave it alone and watch from far away"],
  ],
  "A Map Made from Sticks": [
    [/The shells could mark islands\./, "Small shells could show the islands."],
    [/Sailors learned/, "People learned"],
    [/the sailor's memory/, "their memory"],
  ],
  "Colors in a Drop of Rain": [
    [/Sunlight may look white/, "Light from the Sun may look white"],
    [/it bends/, "it changes direction"],
    [/also bounces inside the drop and bends again/, "also turns back inside the drop and changes direction again"],
    [/do not all bend/, "do not all change direction"],
  ],
  "A Meadow Under the Sea": [
    [/Seagrass is a flowering plant/, "Sea grass is a plant with flowers"],
    [/these meadows/, "these places"],
    [/can hold carbon for a long time/, "can hold carbon for a long time. This plant also gives young fish a safe place"],
  ],
  "The Clinic's Three Languages": [
    [/could not hire three full-time translators/, "could not hire three people to translate all day"],
    [/It also rewrote common forms in plain language\./, "It also made new forms with clear and common words."],
  ],
  "The Coat with Two Owners": [
    [/secondhand shop/, "used-clothes shop"],
    [/the coat's first journey/, "the first journey of the coat"],
  ],
  "Books Carried Out of Timbuktu": [
    [/old handwritten books/, "old books written by hand"],
    [/thousands of manuscripts/, "thousands of these books"],
    [/part of Africa's written history/, "part of the written history of Africa"],
    [/Timbuktu became/, "Timbuktu was a city that became"],
    [/Families kept/, "Timbuktu grew as people came to learn and trade. Families kept"],
  ],
  "Arun Records the Quiet Hours": [
    [/a welcoming place/, "an open and friendly place"],
    [/soft mats/, "soft floor covers"],
    [/Arun's notes/, "His notes"],
    [/Students need quiet/, "Arun asks people what they need. Students need quiet"],
  ],
  "Pines That Wait for Fire": [
    [/Some lodgepole pine cones/, "Some pine cones"],
    [/A strong resin seals their scales\./, "A sticky material keeps them closed."],
    [/these cones/, "the cones"],
    [/In lodgepole pine country/, "In places with these pines"],
  ],
  "A Lever Lifts the Stone": [
    [/rested it on a small block/, "put it on a small block"],
    [/The block became the turning point, or fulcrum\./, "The block became the point where the board could turn."],
    [/A lever does not/, "This simple lever does not"],
  ],
  "Steering by Stars and Swells": [
    [/Polynesian navigators traveled across wide stretches of the Pacific without modern instruments/, "people of the Pacific islands traveled across a wide ocean without modern tools"],
    [/movement of ocean swells/, "long movement of ocean waves"],
    [/through teaching and repeated voyages/, "as teachers shared it and students made many trips"],
    [/In the twentieth century, the Hawaiian canoe Hōkūleʻa helped renew public knowledge of traditional wayfinding\./, "In modern times, trips by a large Hawaiian sea canoe helped bring new public interest to this old skill."],
    [/Its voyages showed that skilled navigators could guide a canoe/, "Its trips showed that a skilled guide could lead a boat"],
    [/inherited knowledge with a modern cultural revival/, "knowledge passed down over time with new cultural work"],
  ],
  "Mowgli Hears the Law of the Jungle": [
    [/Baloo the bear teaches him/, "A bear teaches Mowgli"],
    [/Bagheera the panther protects and advises him/, "and a black cat protects him and gives advice"],
    [/defeats the tiger's challenge/, "wins against the tiger"],
    [/His victories do not/, "His wins do not"],
    [/his place remains uncertain/, "he is not sure where he belongs"],
  ],
  "Edmond Dantès Returns under Another Name": [
    [/Edmond Dantès/g, "Edmond Dantes"],
    [/Mercédès/, "the woman he loves"],
    [/Imprisoned in the Château d'If, he meets Abbé Faria/, "In an island prison, Edmond meets an older prisoner"],
    [/Dantès finds/, "Edmond finds"],
    [/as the Count of Monte Cristo/, "under the rich name of the Count"],
    [/political betrayal/, "a political crime"],
    [/falsely accuse/, "wrongly accuse"],
    [/and punishes those/, "and seeks to punish those"],
  ],
  "Continents on Moving Plates": [
    [/over millions of years it rearranges oceans and continents\./, "over millions of years it changes the position of oceans and continents. The movement is slow enough to escape daily notice but large enough to remake the planet over deep time."],
  ],
  "Odysseus Returns to Ithaca": [
    [/He faces the Cyclops, Circe, the Sirens, shipwrecks, and the anger of Poseidon\./, "He faces a one-eyed giant, a powerful woman who uses magic, dangerous singers, storms, and an angry sea god."],
    [/Odysseus repeatedly saves him/, "Odysseus repeatedly saves himself"],
    [/Odysseus finally arrives in disguise/, "Odysseus finally arrives dressed as a poor stranger"],
    [/Penelope to remarry/, "Penelope to marry one of them"],
    [/weaving by day and undoing the work at night/, "making cloth by day and taking the work apart at night"],
    [/the suitors/, "the men who seek his home"],
    [/The poem's homecoming/, "The return home"],
    [/cleverness/, "quick mind"],
  ],
  "Peatlands: Slow Growth, Large Stores": [
    [/Protecting intact peat is generally easier than rebuilding the slow processes that created it\./, "Protecting peat that is still in good condition is generally easier than rebuilding the slow processes that created it. Choices must also reflect the people who live and work on this land, because long-term care depends on local rights and practical support."],
  ],
};
for (const story of entries) {
  for (const [pattern, replacement] of vocabularyEdits[story.title] || []) {
    story.text = story.text.replace(pattern, replacement);
  }
}
const titleEdits = {
  "When the River Crosses a Border": "The Border River Council",
  "The Museum of Unfinished Wishes": "The Gallery of Abandoned Wishes",
  "Debt after the Cyclone": "Rebuilding While Loans Remain",
  "A Map Made from Sticks": "Shells and Waves on a Stick Chart",
  "Phileas Fogg Makes a Wager": "Fogg's Eighty-Day Promise",
  "The City That Borrowed Tomorrow": "The Summer Missing from the Calendar",
  "A Song Learned on the Night Train": "The Chorus Shared before Dawn",
};
for (const story of entries) story.title = titleEdits[story.title] || story.title;

const stories = JSON.parse(fs.readFileSync(storyPath, "utf8"));
const baseStories = stories.filter((story) => {
  const match = /^s(\d+)$/.exec(String(story.id || ""));
  return match && Number(match[1]) <= 1710;
});
if (baseStories.length !== 1710) throw new Error(`Expected 1,710 reviewed base stories, found ${baseStories.length}.`);
if (entries.length !== 100) throw new Error(`Expected 100 new entries, found ${entries.length}.`);

for (let level = 1; level <= 10; level += 1) {
  for (const topic of topics) {
    const count = entries.filter((story) => story.level === level && story.topic === topic).length;
    if (count !== 1) throw new Error(`Expected one entry for Level ${level} / ${topic}, found ${count}.`);
  }
}

const existingIds = new Set(baseStories.map((story) => story.id));
const existingTitles = new Set(baseStories.map((story) => story.title));
const additions = entries.map((story, index) => {
  const id = `s${String(1711 + index).padStart(3, "0")}`;
  if (existingIds.has(id)) throw new Error(`ID already exists: ${id}`);
  if (existingTitles.has(story.title)) throw new Error(`Title already exists: ${story.title}`);
  return {
    id, level: story.level, topic: story.topic, title: story.title, text: story.text,
    wordCount: story.text.split(/\s+/).filter(Boolean).length,
    subtopic: story.subtopic, contentType: story.contentType,
    editorialStatus: "published", factChecked: true, reviewedAt: "2026-09-14",
    sourceWork: story.sourceWork, vocabularyVersion: "v2",
  };
});

fs.writeFileSync(storyPath, `${JSON.stringify([...baseStories, ...additions], null, 2)}\n`);
console.log(`Added or refreshed ${additions.length} fact-checked stories: ${additions[0].id}-${additions.at(-1).id}`);
