#!/usr/bin/env node
"use strict";

const fs = require("fs");
const path = require("path");

const root = path.resolve(__dirname, "..");
const storyPath = path.join(root, "stories.json");
const reviewedAt = "2026-09-14";
const baseCount = 1910;
const finalCount = 2000;
const topics = [
  "Fantasy/stories", "Nature and animals", "World affairs", "Everyday life", "History",
  "Science", "Famous books", "Mystery and adventure", "Travel and culture", "People and biography",
];
const omittedTopicByLevel = {
  1: "Mystery and adventure",
  2: "Travel and culture",
  3: "People and biography",
  4: "Fantasy/stories",
  5: "History",
  6: "Nature and animals",
  7: "Everyday life",
  8: "World affairs",
  9: "Science",
  10: "Famous books",
};
const contentTypes = {
  "Fantasy/stories": "narrative-fiction",
  "Nature and animals": "explanatory-nonfiction",
  "World affairs": "explanatory-nonfiction",
  "Everyday life": "narrative-fiction",
  History: "historical-narrative",
  Science: "explanatory-nonfiction",
  "Famous books": "classic-retelling",
  "Mystery and adventure": "mystery-fiction",
  "Travel and culture": "travel-vignette",
  "People and biography": "fictional-biography",
};
const e = (level, topic, title, text, subtopic, sourceWork = null) => ({
  level, topic, title, text: text.trim(), subtopic, sourceWork,
});

const entries = [
  // Level 1 — Mystery and adventure omitted
  e(1, "Fantasy/stories", "The Moon in a Mug", `Lio finds a small moon in his mug. It shines on the table. He does not drink it. He takes the mug outside. The little moon rises into the dark sky. A round light grows above him. Lio smiles and goes home.`, "small magic and kindness"),
  e(1, "Nature and animals", "A Turtle Comes Up for Air", `A sea turtle lives in the ocean, but it breathes air. It swims up and puts its nose above the water. Then it takes a breath and goes down again. A mother turtle also comes onto land to lay her eggs in sand.`, "sea turtles and breathing"),
  e(1, "World affairs", "A Bus Map for Everyone", `This town is not real. Its bus map is hard to read. Riders ask for bigger words and clear colors. The town makes a new map. It also adds a list for people who cannot see colors well. More riders can now find the right bus.`, "fictional accessible transit information"),
  e(1, "Everyday life", "The Blue Sock on the Stairs", `A blue sock is on the stairs. Hana walks past it three times. At last, she picks it up. The other blue sock is under a chair. Hana puts the pair away. The stairs are clear, and her feet are warm the next morning.`, "small household habits"),
  e(1, "History", "Clay Held the First Marks", `Long ago in Mesopotamia, people wrote on soft clay. They pressed small signs into it with a cut reed. The signs are called cuneiform. Some tablets held lists, letters, stories, or numbers. Dry clay could keep the marks for a very long time.`, "cuneiform clay tablets"),
  e(1, "Science", "Water Leaves a Leaf", `A plant takes water from the soil. The water moves up through the plant. Some of it leaves the leaves as a gas. This is called transpiration. We cannot see the gas, but it can make drops inside a clear bag around a leaf.`, "plant transpiration"),
  e(1, "Famous books", "Peter Runs from the Garden", `Peter Rabbit does not follow his mother's warning. He goes into Mr. McGregor's garden and eats vegetables. The gardener sees him and gives chase. Peter loses his shoes and coat, but he finds the gate. He reaches home tired and ill.`, "disobedience and escape", "The Tale of Peter Rabbit"),
  e(1, "Travel and culture", "Bread at Sun Street", `Sun Street is in an imaginary town. Noa smells warm bread there. A baker shows her three round loaves. Noa points before she touches anything. She buys one loaf and sits by the square. A family shares fruit with her, and she shares the bread.`, "an imaginary street bakery"),
  e(1, "People and biography", "A Sign Maker Uses Clear Words", `Milo is a fictional sign maker. A park sign has too many words. Children do not know where to go. Milo asks them what they need. He makes short signs with large letters and simple pictures. The children find the garden and the toilets more easily.`, "fictional clear public signs"),

  // Level 2 — Travel and culture omitted
  e(2, "Fantasy/stories", "The Umbrella That Hated Rain", `Nuri buys an old yellow umbrella. It opens in the sun but closes whenever rain starts. Nuri tries to fix it. Then she finds tiny seeds inside the handle. She plants them in a pot. The next week, yellow flowers open whenever drops touch them.`, "a strange umbrella and seeds"),
  e(2, "Nature and animals", "A Bat Listens for Dinner", `Many bats find insects by sending out high sounds. The sounds hit an object and return as echoes. A bat can use the echoes to learn where something is moving. Bats can also see, so echolocation is not a sign that they are blind.`, "bat echolocation"),
  e(2, "World affairs", "A Quiet Town Meeting", `This is a fictional town. Its public meetings are loud, so some people stop coming. The town adds a written question box and a short quiet period. People can also send ideas before the meeting. The new choices do not end every argument, but more voices enter the plan.`, "fictional inclusive public meetings"),
  e(2, "Everyday life", "Toast for the Late Train", `Jun misses his train and must wait forty minutes. He feels angry and hungry. A small cafe is still open. Jun orders toast and writes tomorrow's shopping list. When the next train comes, the wait no longer feels empty. He has eaten and finished one useful task.`, "using an unexpected wait"),
  e(2, "History", "Pompeii under Ash", `Mount Vesuvius erupted in the year 79. Ash and other hot volcanic material covered Pompeii and nearby places. Many buildings, streets, and objects were buried. Later digging revealed parts of the Roman town. The ruins help people study daily life in that time.`, "Pompeii and Vesuvius"),
  e(2, "Science", "Why the Moon Looks Different", `The Sun always lights half of the Moon. As the Moon moves around Earth, we see different parts of that bright half. These changing views are called phases. A thin Moon does not mean that Earth's shadow is covering it. That happens only during a lunar eclipse.`, "moon phases"),
  e(2, "Famous books", "Alice Follows a White Rabbit", `Alice sees a White Rabbit look at a watch and follows him down a hole. In Wonderland, she changes size and meets strange creatures. A cat disappears, a tea party never ends, and a queen orders punishments. At last, Alice wakes and understands that the wild trial was a dream.`, "curiosity and nonsense", "Alice's Adventures in Wonderland"),
  e(2, "Mystery and adventure", "The Lunchbox with the Wrong Name", `Eli finds his lunchbox, but another name is on it. Inside is the same apple and bread he packed. He checks the label again. His own name is written on a loose paper strip under the box. The strip moved when two lunchboxes touched in the school bag.`, "a mixed label clue"),
  e(2, "People and biography", "Nara Repairs One Bicycle", `Nara is a fictional bicycle repairer. She begins with one broken bike in a small shed. She explains each repair and saves useful old parts. Neighbors start bringing children's bikes before school. Nara later teaches a free monthly class, so riders can fix a loose seat or chain safely.`, "fictional community bicycle repair"),

  // Level 3 — People and biography omitted
  e(3, "Fantasy/stories", "The Bell beneath the Lake", `Every evening, Suri hears a bell under the lake. Her grandfather says an old town once stood there, but he calls the story a legend. Suri rows out and lowers a rope. It touches a metal box tied to a fallen tree. Inside, a small glass bell rings as water moves through it. She leaves it for the fish and the next curious listener.`, "a lake bell and a local legend"),
  e(3, "Nature and animals", "A Beaver Changes a Stream", `A beaver cuts branches and builds a dam across moving water. The dam can slow the stream and spread water into a pond or wet ground. This new habitat may support fish, frogs, birds, and plants. Results differ by place, and a dam can also flood roads or fields. Beavers change landscapes, but people still have to manage conflicts carefully.`, "beavers and wetland habitat"),
  e(3, "World affairs", "The Library Opens Later", `This fictional district closes its library at five. Students and shift workers say they cannot arrive in time. Keeping every branch open late would cost too much. The district tests two late evenings at the busiest branch and a small locker for returns. After three months, it checks use, cost, safety, and staff feedback before deciding what to keep.`, "fictional library access policy"),
  e(3, "Everyday life", "A Cup Returned with a Note", `Mina borrows a travel cup from her coworker and forgets it for a week. She feels too embarrassed to mention it. On Friday, she washes the cup, fills it with tea, and adds a short note: “I am sorry I kept this so long.” Her coworker laughs and says the silence worried him more than the late return.`, "repairing a small mistake"),
  e(3, "History", "The Charter at Runnymede", `In 1215, King John of England accepted Magna Carta after a conflict with rebel barons. The charter put some limits on royal power and recorded certain legal protections. It did not create modern democracy, and most people gained no direct political voice from it. The first agreement soon failed, but later versions helped shape ideas about rulers being subject to law.`, "Magna Carta and its limits"),
  e(3, "Science", "Cabbage Water Changes Color", `Red cabbage contains substances that can change color in acids and bases. A student pours cabbage water into three clear cups. Lemon juice turns one sample pink, while a mild baking-soda mixture shifts another toward blue or green. The colors give clues, not exact measurements. The student wears eye protection and never tastes test liquids.`, "acid-base indicators"),
  e(3, "Famous books", "Heidi Returns to the Mountains", `Young Heidi goes to live with her grandfather in the Swiss Alps. She loves the goats, the open air, and her friend Peter. Later, she is taken to Frankfurt to be a companion to Clara, who cannot walk. Heidi misses the mountains and becomes ill. When she returns home, her health improves. Clara later visits, and the friends help each other grow stronger.`, "home, friendship, and health", "Heidi"),
  e(3, "Mystery and adventure", "The Muddy Number Seven", `Someone writes a muddy number seven on the community hall door each night. Priya waits nearby and hears a soft scrape. A delivery cart turns at the corner, and one wet wheel brushes the door. The wheel has seven raised bars. Each turn leaves the same mark. Priya moves the cart's parking place and cleans the door.`, "a repeating wheel mark"),
  e(3, "Travel and culture", "Tea on the Wind Hill", `Wind Hill is part of an imaginary island. Visitors often expect a formal tea event, but local families bring plain cups to the hill at sunset. Their host asks Aki to pour only after everyone is seated. Aki watches, asks questions, and follows the group's pace. The tea is simple; the shared attention is what makes the evening special.`, "an imaginary sunset tea custom"),

  // Level 4 — Fantasy/stories omitted
  e(4, "Nature and animals", "How a Penguin Holds Heat", `Penguins live in very different climates, but species in cold places have several ways to limit heat loss. Dense feathers trap a layer of air near the body. Fat also provides insulation, and birds may huddle or change posture. Feathers must stay in good condition, so penguins spend time cleaning and arranging them. These features do not make a penguin immune to cold. Wind, wet feathers, food supply, age, and health can still affect its ability to keep warm.`, "penguin insulation and behavior"),
  e(4, "World affairs", "Cool Rooms during a Heat Wave", `This fictional city opens public cool rooms during very hot weather. At first, nearly all sites are downtown and close before night workers finish. Residents map where older people live, compare bus routes, and ask which hours are useful. The city moves two sites to neighborhood halls and publishes opening times by radio, text, and paper notice. It also checks that water, seating, and backup power are available. The plan is tested each season rather than treated as complete.`, "fictional heat-response planning"),
  e(4, "Everyday life", "The Calendar No One Owned", `Four housemates share a kitchen but keep buying the same food. They create a calendar, then discover that nobody updates it. Instead of blaming the person who forgets, they place a small whiteboard beside the refrigerator. Anyone who opens the last packet writes the item down. One housemate photographs the board before shopping. The method is less advanced than their unused app, but it fits the moment when the information is needed.`, "a practical shared shopping system"),
  e(4, "History", "The Army Made of Clay", `Farmers near Xi'an found fragments of clay figures in 1974. Archaeologists then uncovered pits connected with the tomb complex of Qin Shi Huang, the first emperor to unify China. Thousands of life-size soldiers, along with horses and chariots, formed part of the site. The figures vary in face, hair, clothing, and position, although they were produced through organized workshop methods. Much of the complex remains unexcavated, and conservation is as important as discovery.`, "the Terracotta Army"),
  e(4, "Science", "A Clear Bag around a Branch", `Water enters a plant through its roots and moves through tissues to the leaves. Tiny openings in the leaves allow water vapor to escape. This process, called transpiration, is usually invisible. If a clear bag is tied around a leafy branch, water may collect inside as vapor cools and becomes liquid again. The demonstration needs a comparison because water might also come from damp soil or rain. Heat, light, wind, humidity, and plant type all affect the rate.`, "observing plant transpiration"),
  e(4, "Famous books", "Black Beauty Meets Kind and Cruel Hands", `Black Beauty tells his own life story as a horse. He begins with gentle care, but later owners and drivers treat him in very different ways. Some understand his needs; others value speed, fashion, or money more than his pain. Beauty works in the country and in busy London streets, suffers illness and exhaustion, and loses old friends. At last, he reaches a quiet home where people recognize him and promise good care.`, "animal care and human responsibility", "Black Beauty"),
  e(4, "Mystery and adventure", "The Blue Light in Cabin Nine", `A closed train cabin shows a blue light every time the train enters a tunnel. The conductor checks the power and finds no fault. Inez notices that a passenger across the hall is reading from a tablet with a blue cover. In darkness, the bright screen reflects off the cover, through one window, and into the glass of Cabin Nine. The cabin itself is empty. The strange light is only a reflection moving between two panes.`, "a reflection on a night train"),
  e(4, "Travel and culture", "Threads at Cedar Market", `Cedar Market belongs to an imaginary mountain city. Sellers display cloth marked with family and workshop patterns. Visitor Ren wants to photograph every bright design. A weaver explains that public samples are fine, but one covered piece is for a private ceremony. Ren puts away the camera and asks about the yarn instead. The weaver shows how two colors cross on a small frame. Ren leaves with a plain scarf and a better understanding of where permission matters.`, "an imaginary textile market"),
  e(4, "People and biography", "The Gardener Who Lowered the Beds", `Tala is a fictional community gardener. She notices that several neighbors watch lessons but rarely join. The tools are heavy, and every planting bed is near the ground. Tala does not guess what each person needs. She invites them to test lighter tools, raised boxes, wide paths, and seats. Some ideas help; others take too much space. The group keeps two raised beds and a tool rack at different heights. Participation grows because the garden changes with its users.`, "fictional accessible community gardening"),

  // Level 5 — History omitted
  e(5, "Fantasy/stories", "The River That Fell Asleep", `One summer, the River Iri stops moving. Boats rest on still water, and the mills fall silent. People blame a stone giant upstream, but Mara walks the banks and hears quiet singing under a bridge. The river has spent centuries carrying every wish thrown into it and is too tired to continue. Mara asks the town to stop feeding it coins and secret demands. For seven nights, residents return to collect litter and speak their wishes to one another instead. On the eighth morning, the river begins to move—not because every wish is solved, but because it no longer carries them alone.`, "a tired river and shared responsibility"),
  e(5, "Nature and animals", "An Octopus Changes Its Look", `An octopus can alter its appearance quickly. Pigment cells in the skin expand or contract, changing visible color and pattern. Other structures affect how light reflects, and small muscles can raise parts of the skin to change texture. These shifts may help with hiding, signaling, hunting, or responding to a threat. An octopus does not simply copy any background like a photograph. Its eyes, nervous system, species, body state, and surroundings shape the display. Researchers still study how the animal controls such fast, coordinated changes across its body.`, "octopus camouflage and signaling"),
  e(5, "World affairs", "A Ballot without a Stair", `This fictional region holds local elections in schools, but many entrances have steps. Officials first suggest carrying anyone who asks for help. Disability groups explain that access should not depend on being lifted by strangers. The region surveys every site, moves some voting rooms, adds temporary ramps where safe, and offers an independent mail option. It trains workers and publishes an access guide before election day. Afterward, voters report blocked paths and poor signs. The review shows that a legal right becomes practical only when transport, information, privacy, and physical design work together.`, "fictional accessible election planning"),
  e(5, "Everyday life", "The Garden behind the Lease", `Mara wants vegetables outside her rented apartment, but the lease forbids digging. She almost plants in secret. Her neighbor points out that roots could damage a buried pipe. Mara asks the owner about movable containers instead. Together, residents mark a sunny area that keeps the emergency path clear. They use light pots, collect no standing water, and agree who will clean the space. The first crop is small: herbs, beans, and three tomatoes. More important, the garden survives because the rules were discussed before the soil arrived.`, "container gardening in shared housing"),
  e(5, "Science", "Bread Rises on Yeast Gas", `Yeast is a living fungus. In bread dough, it uses available sugars and releases carbon dioxide along with other products. The gas enters small spaces in the dough. A network formed by flour proteins helps hold many of those bubbles, so the dough expands. Warm conditions can speed yeast activity, but too much heat can damage or kill the cells. Salt, sugar, water, flour, and time also change the result. When bread bakes, heat expands gases, sets the structure, and produces new flavors. The holes in a loaf therefore record both biology and careful control.`, "yeast fermentation in bread"),
  e(5, "Famous books", "Anne Finds a Home at Green Gables", `Marilla and Matthew Cuthbert expect an orphan boy who can help on their farm. Instead, Anne Shirley arrives: talkative, imaginative, and desperate to belong. Marilla considers sending her back but allows her to stay. Anne makes loyal friends, quarrels with Gilbert Blythe, causes accidents, studies hard, and slowly becomes part of Avonlea. When Matthew dies and Marilla's eyesight worsens, Anne gives up a distant teaching plan so she can remain near home. Her choice is not a defeat. It shows that the restless child has learned how love can guide a future.`, "belonging, growth, and choice", "Anne of Green Gables"),
  e(5, "Mystery and adventure", "The Photograph Taken Tomorrow", `A museum guard finds a printed photograph showing a vase broken on the gallery floor. The time stamp says tomorrow afternoon. Staff fear a threat, but investigator Sol notices fresh construction dust on the pictured wall. That wall was painted months ago and is clean now. In a storage room, he finds a model gallery used to plan a new exhibit. A designer photographed the model, changed the date to test a label printer, and dropped the print. The tiny “vase” is clay. No prediction occurred, yet the mistake reveals that storage records need clearer labels.`, "a misleading model photograph"),
  e(5, "Travel and culture", "The Last Ferry to Orin", `Orin is an imaginary island where the night ferry carries people, bicycles, baskets, and sometimes musical instruments. Visitor Sora expects a quiet crossing. Instead, passengers begin a soft call-and-response song as the harbor lights disappear. Her host explains that joining is welcome but not required. Sora listens through the first verse, then repeats one simple line. When the boat arrives, everyone stops without applause and helps unload the older passengers' bags. Sora realizes that a shared custom may be less about performance than about marking a familiar journey together.`, "an imaginary island ferry song"),
  e(5, "People and biography", "Iven Keeps the Oven Warm", `Iven is a fictional baker in a town where the last grocery shop closes. He cannot replace a full store, but he notices that older neighbors need small amounts of bread, milk, and fruit. Iven clears one shelf and asks a nearby farm and dairy to make limited deliveries. He records what sells instead of guessing, keeps prices visible, and gives unsold bread to a meal group under a written agreement. The shelf remains modest. Its success comes from fitting the bakery's real capacity while solving one part of a larger problem.`, "fictional neighborhood food access"),
];

entries.push(
  // Level 6 — Nature and animals omitted
  e(6, "Fantasy/stories", "The Station for Unclaimed Memories", `At the end of the tram line, Nela discovers a station with no tracks. Its shelves hold memories that people have dropped: the sound of a childhood door, the taste of a winter pear, the face of someone met only once. The keeper says she may take any memory whose owner cannot be found. Nela reaches for a bright summer afternoon, then notices a name stitched into its cloth bag. She spends the night searching old city lists and returns it to a woman who had forgotten why she loved the sea. Nela leaves empty-handed, but the keeper tells her that returning a memory creates one of its own.`, "memory, ownership, and return"),
  e(6, "World affairs", "Water Prices in a Dry Year", `This fictional city faces a long dry season. Leaders propose one high price for every unit of household water, hoping that cost will reduce use. Residents warn that the plan could punish large low-income families while barely affecting wealthy households. The city tests a tiered system: a basic amount remains affordable, heavier use costs more, and verified medical or household needs can receive adjustments. Leaks are repaired before penalties begin, and monthly data are published without naming homes. Demand falls, but the review also finds confusing bills. The policy continues only after clearer notices and an independent appeal process are added.`, "fictional equitable water pricing"),
  e(6, "Everyday life", "Saturday at the Repair Table", `A cafe owner lets volunteers use one corner for a monthly repair table. At first, visitors expect every lamp, toaster, and radio to be saved. The volunteers explain that some devices are unsafe to open or too damaged to repair. They begin each visit with a check, then offer three outcomes: repair, advice on a part, or guidance for safe disposal. Mina brings a fan that only needs dust removed from its guard. Another visitor learns that his cracked heater should not be used again. The table prevents waste when it can, but it treats honest limits as part of good repair.`, "community repair and safety"),
  e(6, "History", "Freedom Won in Saint-Domingue", `The Haitian Revolution began in 1791 in the French colony of Saint-Domingue, where an economy built on slavery had produced extreme violence and inequality. Enslaved people launched a major uprising, while free people of color, white colonists, foreign armies, and leaders with changing alliances pursued different aims. Toussaint Louverture became a powerful revolutionary leader but died in French captivity. Forces led by Jean-Jacques Dessalines defeated Napoleon's expedition, and Haiti declared independence in 1804. The revolution destroyed slavery in the new state and created the first independent Black republic, though war, isolation, and later foreign pressure imposed lasting costs.`, "the Haitian Revolution"),
  e(6, "Science", "A Complete Path for Electric Current", `A simple electric circuit needs a source of electrical energy, conducting material, and a complete path. When a battery, wires, and a lamp are connected in a closed loop, charge can move through the circuit and the lamp may light. Opening a switch breaks the path, so the current stops. The battery does not send out a fixed amount of current regardless of the circuit; voltage, resistance, and component design all matter. A short circuit can allow dangerously large current and heat. Classroom investigations therefore use low-voltage equipment and follow instructions about safe connections.`, "closed electric circuits"),
  e(6, "Famous books", "Fogg Races around the World", `Phileas Fogg makes a wager that he can travel around the world in eighty days. He leaves London with his servant Passepartout and follows steamship and railway routes across several continents. Detective Fix follows because he wrongly suspects Fogg of a bank robbery. Delays, danger, rescue, and imperfect transport threaten the schedule, while Aouda joins the travelers and becomes important to Fogg. Back in London, Fogg believes he has arrived one day too late. Then he learns that traveling east across the date line has gained him a calendar day. He wins the wager and, more importantly, finds love.`, "time, travel, and mistaken suspicion", "Around the World in Eighty Days"),
  e(6, "Mystery and adventure", "Seven Keys and One Warm Lock", `A hotel manager receives seven old keys in an envelope. A note says that one opens a room that should not exist. Investigator Ema checks each key without forcing any lock. Six are cold from the office drawer, but one is slightly warm. She studies the staff log and learns that a worker found the keys beside the basement boiler. The warm key had rested on a pipe, not inside a secret room. Yet its worn label leads Ema to a sealed supply door omitted from the latest floor plan. The missing room is ordinary, but the outdated records could have delayed firefighters. The mystery ends with a safer map rather than hidden treasure.`, "keys, heat, and an outdated plan"),
  e(6, "Travel and culture", "Three Ways to Say Welcome in Vela", `Vela is an imaginary coastal region with three commonly used languages. Visitor Omi memorizes one greeting and assumes it will suit every village. His guide explains that language choice can express family history, education, or local identity, and that no greeting is neutral in every setting. Omi begins by listening. At a market, he uses the words the seller has used with him; at a community hall, he follows the bilingual sign; with an older host, he asks which language feels comfortable. His accent remains imperfect, but the question itself opens better conversations. Travel becomes less about displaying what he knows and more about noticing who is speaking.`, "language choice in an imaginary region"),
  e(6, "People and biography", "Daro Builds a Bridge in Pieces", `Daro is a fictional civil engineer in a river district where a full bridge replacement is beyond the yearly budget. Residents need safer access before the long project can begin. Daro organizes inspections, publishes the load limits, and separates urgent repairs from cosmetic wishes. Workers strengthen one damaged support, improve lighting, and create a protected walking lane. Heavy trucks take a temporary route. Daro refuses to promise that the smaller work makes the bridge new; monitoring continues after every flood. His reputation grows not from a dramatic opening ceremony, but from explaining uncertainty, sequencing work, and treating maintenance as a public responsibility.`, "fictional phased bridge repair"),

  // Level 7 — Everyday life omitted
  e(7, "Fantasy/stories", "The Market Where Shadows Were Traded", `In the old quarter, merchants sell shadows for purposes people seldom admit. A musician buys a tall shadow to appear confident onstage. A thief seeks one that makes no sound. Arin comes to replace her own shadow, which has begun pointing toward roads she fears. The seller offers obedient darkness in a silver jar, but asks for one memory in payment. Arin refuses and follows her troublesome shadow instead. It leads to the house of a friend she abandoned after an argument. The shadow does not predict the future or excuse her silence; it merely reveals the direction she has avoided looking. After Arin knocks, the two women talk until sunrise. Her shadow lies quietly at her feet, still hers and still free to disagree.`, "shadows, avoidance, and reconciliation"),
  e(7, "Nature and animals", "Fungi Return a Fallen Tree to the Forest", `A fallen tree may look inactive, yet it becomes habitat and food for a changing community. Wood-decay fungi release enzymes that break large plant compounds into smaller materials they can use. Insects open tunnels, bacteria contribute to chemical change, and moisture influences which organisms thrive. As decay proceeds, nutrients can return to soil and other living things, while the log stores water and shelters seedlings or animals. Not every fungus performs the same role, and rates differ with tree species, temperature, oxygen, and climate. Removing all dead wood may reduce habitat, but leaving it everywhere can create safety or fire concerns. Forest management therefore balances ecological value with local risk.`, "wood-decay fungi and nutrient cycling"),
  e(7, "World affairs", "Homes after the Factory Closed", `This fictional town loses its largest employer, and many tenants fall behind on rent. The council considers a temporary housing grant. A universal payment would be simple but expensive; a strict means test might exclude people whose recent income records no longer reflect reality. The town combines a short emergency payment with later verification and free debt advice. Landlords who accept funds must pause eviction for a defined period, while tenants may appeal an incorrect decision. Six months later, the program has prevented some displacement but has not created new jobs or affordable homes. The public report distinguishes immediate protection from structural reform, allowing residents to judge what the grant solved and what it did not.`, "fictional emergency housing support"),
  e(7, "History", "Many Roads Called the Silk Roads", `The Silk Roads were not a single highway with one beginning and end. They were changing networks of land and sea routes that linked communities across Asia, Europe, and Africa. Merchants carried silk, horses, spices, glass, metals, and many other goods through chains of exchange rather than always crossing the full distance themselves. Religious ideas, artistic forms, languages, technologies, and diseases also moved through contact. States sometimes protected routes and sometimes fought over them; deserts, mountains, weather, and political change redirected travel. Calling the networks “Silk Roads” is useful, but it can hide their variety and the importance of local traders, ports, caravan towns, and maritime connections.`, "exchange along the Silk Roads"),
  e(7, "Science", "Resistance Is an Evolutionary Problem", `Antibiotics can kill susceptible bacteria or stop them from growing, but they do not work against viruses. Within a bacterial population, genetic differences may allow some cells to survive a drug. When antibiotics are used, those survivors can multiply, and resistance genes may also move between bacteria. The person does not become resistant; the microorganisms do. Unnecessary use increases selection pressure, while poor infection control helps resistant strains spread. Good stewardship means using the right medicine only when it is needed, at an appropriate dose and duration, while also improving sanitation, vaccination, diagnosis, and surveillance. No single action will remove resistance, because evolution continues wherever microbes reproduce.`, "antibiotic resistance and selection"),
  e(7, "Famous books", "Buck Hears the Call", `Buck lives comfortably in California until he is stolen and sold as a sled dog during the Klondike Gold Rush. In the North, he encounters cold, hunger, violent handlers, and competition among dogs. He learns the harsh rules of survival and gradually becomes stronger and more alert. John Thornton treats him with affection, and Buck returns that loyalty with extraordinary courage. Yet the wilderness continues to attract him. After Thornton is killed, Buck joins a wolf pack and leaves human society. The novel presents this change as both liberation and loss: Buck survives by recovering ancient instincts, but the path toward the wild is marked by cruelty and grief.`, "survival, loyalty, and wildness", "The Call of the Wild"),
  e(7, "Mystery and adventure", "The Radio Message from an Empty Mine", `A rescue team hears a weak voice from a mine closed for twenty years. The message repeats coordinates and the phrase “air running low.” Before entering, engineer Salma checks the recording time and signal path. The transmission occurs at the same minute each evening. She traces a cable to a weather station, where a damaged player once used for emergency drills has connected to an old radio unit. Temperature changes activate the failing circuit after sunset. The coordinates identify a training chamber, not trapped workers. The team removes the device and updates the frequency register. Careful caution prevented a dangerous rush underground, while the false alarm exposed equipment that should have been disconnected long ago.`, "an automated emergency recording"),
  e(7, "Travel and culture", "Following the Wells of Aras", `Aras is an imaginary desert province where older walking routes connect deep wells. Guide Samira tells visitors that the paths are not empty wilderness: herding families, maintenance crews, and seasonal travelers still use them. She limits the group size, asks permission before camping near a well, and carries more water than the map suggests. When a storm fills one shallow basin, a visitor wants to discard the reserve. Samira refuses; surface water may be muddy or temporary. At each stop, she records damage to the stone walls and shares the notes with local caretakers. The journey teaches that cultural landscapes survive through current work, not simply because an old route appears romantic.`, "responsible travel on an imaginary desert route"),
  e(7, "People and biography", "Lena Preserves Ordinary Voices", `Lena is a fictional archivist who notices that her town collection contains speeches by mayors but few accounts from cleaners, shop workers, migrants, or children. She begins an oral-history project, then learns that inviting stories is not enough. Participants need to understand where recordings will be stored, who may hear them, and whether names can be hidden. Lena offers withdrawal periods, translated consent forms, and several access levels. Some people decline; others donate only a transcript. The archive grows more slowly than expected, but it becomes more trustworthy. Lena's achievement is not capturing every voice. It is building a process in which people retain meaningful control over how their memories enter the public record.`, "fictional ethical oral history"),

  // Level 8 — World affairs omitted
  e(8, "Fantasy/stories", "The City That Forgot Its Names", `One morning, every street sign in Belis turns blank. Residents still know the routes, yet deliveries fail and emergency crews lose time. The Council of Names orders scribes to restore the oldest labels from royal maps. Historian Sera objects: several districts were renamed by the communities that now live there, and some official names honor rulers who expelled earlier residents. A magical census book can recover every title ever used, but it cannot decide which one is just. The city holds assemblies, accepts multiple names in some places, and records disputed histories beside others. Navigation returns slowly. Sera realizes that the spell did not steal language; it removed the illusion that a map is neutral. Choosing what to print has always been an act of memory and power.`, "place names, memory, and power"),
  e(8, "Nature and animals", "Horseshoe Crabs at the Spring Tide", `Horseshoe crabs are marine arthropods, not true crabs. Along parts of the Atlantic coast, adults gather in shallow water and on beaches to spawn, often around high tides in spring. Females place clusters of eggs in sand, and males fertilize them. Many eggs remain buried, while waves expose others. Migrating shorebirds can consume the exposed eggs as a rich food source during demanding journeys. Harvest, shoreline development, weather, and changing habitat can affect this relationship, so managers use monitoring and local rules rather than assuming one uniform trend everywhere. The animals' blue blood is also used in biomedical testing, creating another conservation issue and encouraging work on alternative methods.`, "horseshoe crab spawning ecology"),
  e(8, "Everyday life", "The Roster beside the Hospital Bed", `When their father becomes seriously ill, three siblings create a care roster. At first it looks perfectly equal: each person receives the same number of visits. Within a week, the arrangement fails. One sibling lives nearby but works nights; another lives far away and can manage insurance calls; the third has young children and can cook in batches. They replace identical shifts with a list of tasks, limits, and backup plans. They also ask their father what help he wants instead of discussing him as a schedule. The revised system remains uneven in hours, yet it is more equitable in burden and more respectful of his agency. Fairness, they learn, cannot always be measured by counting visits alone.`, "shared family care and fairness"),
  e(8, "History", "What the Emancipation Proclamation Changed", `Abraham Lincoln issued the Emancipation Proclamation on January 1, 1863, during the American Civil War. It declared enslaved people free in areas still rebelling against the United States, but it did not apply to loyal border states or every place already under Union control. Its legal reach therefore depended on military advance, and it did not by itself abolish slavery nationwide. The proclamation nevertheless transformed the war's stated purpose, authorized the enlistment of Black men in Union forces, and gave federal force to freedom claims made by enslaved people themselves. The Thirteenth Amendment later abolished slavery throughout the country, except as punishment for a crime. Understanding both the proclamation's power and its limits prevents a symbolic milestone from replacing the longer struggle.`, "the Emancipation Proclamation and its limits"),
  e(8, "Science", "Listening for Distortions in Space-Time", `General relativity predicts that accelerating masses can produce gravitational waves: disturbances in space-time that travel outward. By the time waves from distant compact objects reach Earth, their effects are extraordinarily small. Laser interferometers compare the lengths of perpendicular arms, looking for a coordinated pattern in which one direction stretches while the other contracts. Local vibration, thermal motion, and instrument noise can imitate pieces of a signal, so one detector and one unusual movement are not enough. Analysts model noise, compare separated observatories, and test whether the waveform matches a plausible source. The first direct detection, announced in 2016, came from two merging black holes. It opened a new way to observe events that may emit little or no light.`, "gravitational-wave detection"),
  e(8, "Famous books", "The Creature Asks Victor to Listen", `Victor Frankenstein becomes obsessed with creating life and succeeds, but he abandons the being as soon as it awakens. The creature learns language by secretly observing a family and longs for sympathy. Repeated rejection turns loneliness into anger. He confronts Victor and asks for a companion, promising to leave humanity. Victor begins the work, then destroys it, fearing future harm. The creature retaliates against people Victor loves, while Victor pursues him into the Arctic. Neither responsibility nor revenge restores what they have lost. After Victor dies, the creature appears in grief and declares that he will end his own life. The novel's tragedy grows not from a simple monster, but from creation without care, prejudice, secrecy, and choices that narrow until violence seems inevitable.`, "creation, rejection, and responsibility", "Frankenstein; or, The Modern Prometheus"),
  e(8, "Mystery and adventure", "A Star Missing from the Observatory", `An observatory's archive contains twelve glass plates from a century-old sky survey, but the catalog claims that one plate shows a bright star absent from every modern image. Rumors of an unexplained disappearance spread online. Astronomer Keo first checks coordinates, dates, and plate orientation. The supposed star lies exactly where a small ink mark appears on the paper sleeve. Under angled light, he sees that damp ink transferred onto the emulsion while the plates were stacked. The mark is an artifact, not a celestial event. Yet the investigation uncovers a real problem: two plates were filed under reversed east-west labels. Keo publishes both findings, because explaining an error honestly can improve an archive without making the sky less interesting.`, "an archival astronomy artifact"),
  e(8, "Travel and culture", "Two Currencies at the Reed Market", `The Reed Market stands in an imaginary border valley where traders arrive from both sides of a mountain pass. Prices appear in two currencies, three languages, and sometimes in measures understood only within a craft. Visitor Dani assumes this confusion invites cheating. Merchant Aro explains the public weighing table, the daily exchange board, and the custom of repeating a bargain aloud before payment. These practices do not eliminate unequal knowledge, but they make terms easier to challenge. Dani hires a local interpreter for a large purchase and accepts that translation is skilled labor, not a casual favor. By afternoon, the market seems less chaotic. Its order exists in shared procedures rather than in one language or one set of coins.`, "an imaginary multilingual border market"),
  e(8, "People and biography", "Mara Maps Water without Owning It", `Mara is a fictional hydrologist asked to map springs in a drought-prone valley. A regional agency wants exact locations published online, but residents warn that some springs are culturally sensitive and easily damaged. Mara separates the scientific need to understand water flow from the assumption that every coordinate must be public. With community representatives, she creates a detailed protected dataset and a general map showing watershed patterns without vulnerable sites. She documents uncertainty, seasonal gaps, and who may update the records. The compromise frustrates users who equate openness with unrestricted access. Mara argues that responsible data practice asks not only whether information can be shared, but also who may bear the cost when it is.`, "fictional ethical water mapping"),

  // Level 9 — Science omitted
  e(9, "Fantasy/stories", "An Archive of Futures That Did Not Happen", `The royal archive preserves treaties, census books, and one forbidden collection: accounts of futures that almost occurred. Apprentice Jalen opens a volume describing a flood prevented by a farmer's unnoticed repair. Another records a war avoided because a messenger stopped to help an injured horse and missed his deadline. The pages tempt rulers, who want to identify the one action that guarantees prosperity. Archivist Meira warns that each future appears only after it becomes impossible; the books reveal contingency, not a usable forecast. When the king orders her to extract a formula, she displays thousands of contradictory volumes. Small causes matter, but they interact with structures, chance, and other choices. The archive's lesson is humbling: history could have differed, yet imagined alternatives do not absolve anyone from deciding under uncertainty now.`, "counterfactual futures and uncertainty"),
  e(9, "Nature and animals", "A Whale Fall Becomes a Deep-Sea Habitat", `When the body of a large whale reaches the deep seafloor, it can create a concentrated source of food in an otherwise energy-poor environment. Mobile scavengers may remove soft tissue first. Smaller animals then use enriched sediments and exposed surfaces, while microbes and specialized organisms exploit fats stored in the bones. These stages overlap and vary with depth, temperature, oxygen, whale size, burial, and local ecology; a whale fall does not follow one rigid timetable. Chemosynthetic communities can develop when microbial processes produce reduced chemicals that other microbes use for energy. Researchers study whale falls with submersibles, remotely operated vehicles, experiments, and naturally discovered remains. Each observation is valuable because the deep ocean is difficult to sample and carcasses are unevenly distributed.`, "whale falls and deep-sea succession"),
  e(9, "World affairs", "The Appeal behind the Benefits Algorithm", `This fictional country uses an automated system to flag benefit claims for review. Officials say the model merely prioritizes cases, yet flagged households wait months longer for payment. Journalists discover that neighborhood and work-history variables reproduce older patterns of disadvantage. The government removes one variable, but independent auditors show that several substitutes carry similar information. A revised law requires impact testing, published error rates, human reasons for adverse decisions, and a rapid appeal that pauses collection. Automation continues for low-risk administrative checks, while eligibility decisions receive stricter oversight. The reform does not make the model neutral. It changes where evidence, responsibility, and contestability must enter the system—and recognizes that procedural delay can itself become a serious harm.`, "fictional algorithmic benefits review"),
  e(9, "Everyday life", "Closing an Account after a Death", `After their mother dies, Arun and his sister discover that her photographs, bills, subscriptions, and messages are spread across many online accounts. Grief turns each password request into an argument about privacy. Arun wants to preserve everything; his sister believes some conversations were never meant for them. They pause and list practical duties separately from sentimental wishes. Legal documents guide access to financial records, while platform memorial tools handle public profiles. Private messages remain unopened unless needed for a clear reason. They download family photographs, cancel paid services, and record what they chose not to inspect. The work teaches them that digital inheritance is not simply data recovery. It involves authority, restraint, memory, and respect for relationships that continue to have boundaries after death.`, "digital accounts, grief, and privacy"),
  e(9, "History", "Designing the Bretton Woods Institutions", `In July 1944, delegates from forty-four Allied nations met at Bretton Woods, New Hampshire, to design a postwar monetary order. They sought greater exchange-rate stability, support for countries facing balance-of-payments problems, and financing for reconstruction and development. The agreements created the International Monetary Fund and what became the World Bank, while currencies were linked through a system centered on the U.S. dollar and gold. The arrangements reflected negotiation but also unequal power, especially the economic position of the United States. The fixed-rate system later broke down, yet the institutions survived and changed. Bretton Woods therefore names both a specific historical settlement and an evolving set of organizations whose roles, conditions, and representation remain subjects of debate.`, "the Bretton Woods conference"),
  e(9, "Famous books", "Jane Eyre Chooses Equality", `Jane Eyre grows up unwanted in her aunt's household and endures deprivation at Lowood School. As an adult, she becomes governess to Adèle at Thornfield Hall and develops a bond with Edward Rochester. On their wedding day, Jane learns that Rochester is already married to Bertha Mason, whom he keeps confined in the house. Although leaving costs Jane security and love, she refuses a relationship that would violate her conscience and reduce her independence. After hardship, she finds relatives and inherits money, gaining both family and material freedom. She returns only after Thornfield burns and Rochester's circumstances change. Their eventual marriage rests on a more equal footing, though the novel's treatment of Bertha and empire continues to invite critical scrutiny.`, "conscience, independence, and equality", "Jane Eyre"),
  e(9, "Mystery and adventure", "The Harbor Ledger with Two Midnights", `Customs investigator Lian finds a cargo ledger in which the same vessel arrives twice at midnight, once carrying medical supplies and once carrying machine parts. Smuggling seems likely, but the crew list is identical and both entries bear valid seals. Lian compares weather logs, radio records, and the clerk's software settings. The port changed its official time zone that week, while one terminal updated automatically and another remained on the old offset. The ship crossed no ocean between entries; two systems described one arrival with different dates and commodity codes imported from separate manifests. The discrepancy is administrative, but not harmless. Lian requires synchronized clocks, preserved source records, and an audit trail so future errors cannot conceal a genuinely altered cargo.`, "time-zone errors in a harbor record"),
  e(9, "Travel and culture", "The Pilgrim Road without a Finish Line", `Namar is an imaginary pilgrimage route linking springs, shrines, farms, and guesthouses across a high plateau. Some travelers walk for faith, others for family memory, recovery, curiosity, or work. Visitor Leen expects a certificate at the final gate, but learns that local tradition recognizes no single official endpoint. Different communities maintain different sections and tell different origin stories. Rather than selecting the version that sounds oldest, Leen records who told each account and under what circumstances. She pays for lodging, follows water limits, and avoids photographing private rites. By the final village, the absence of a universal finish no longer feels like a defect. The route's continuity depends on overlapping practices, not on one authority declaring where meaning ends.`, "an imaginary plural pilgrimage route"),
  e(9, "People and biography", "Sorin Turns a Shop into a Cooperative", `Sorin is a fictional mechanic whose employer plans to close a farm-equipment workshop. He proposes that workers buy the business together. Enthusiasm is immediate, but ownership proves more complex than dividing profits equally. The group must value old machines, negotiate debt, define voting rights, and decide how new members gain shares. Sorin insists on paid training so office staff and apprentices can understand the accounts. The cooperative survives its first difficult year by postponing expansion and publishing monthly cash-flow reports to members. Sorin later steps down as chair, arguing that a worker-owned business should not depend on its founder's permanent authority. His lasting contribution is a structure that can question him and continue without him.`, "fictional worker cooperative formation"),

  // Level 10 — Famous books omitted
  e(10, "Fantasy/stories", "The Prophecy That Required Consent", `Every child in Aven receives a sealed prophecy at birth. The state opens each document at sixteen and assigns education, work, and marriage accordingly. Officials defend the system because most predictions appear accurate, but accuracy is difficult to separate from enforcement: people trained for one path often follow it because alternatives have been removed. When Ilya's prophecy names her as the next royal judge, she refuses to open it publicly. The court threatens to read it without her, exposing the coercion beneath a ritual described as destiny. Ilya proposes a radical test: prophecies may be offered privately, but no institution may demand disclosure or attach rights to compliance. Some citizens still choose to read theirs; others burn the envelopes. The future becomes less orderly, yet also more genuinely informative, because a prediction can no longer manufacture the behavior used to prove it true.`, "prophecy, coercion, and self-fulfilling systems"),
  e(10, "Nature and animals", "The Negotiated Partnership around a Root", `Mycorrhiza describes an association between certain fungi and plant roots. Fungal threads can extend through soil beyond the immediate root surface, gaining access to water or mineral nutrients; in return, the plant supplies carbon compounds produced through photosynthesis. The common language of trade is useful but incomplete. Neither partner calculates a fair price, outcomes vary among species and environments, and the association can shift along a continuum from strongly beneficial to costly. Soil fertility, moisture, disturbance, competing organisms, and developmental stage all influence the exchange. Moreover, mycorrhizal fungi are not the same as free-living decomposers, although ecological roles can overlap in complicated ways. Treating the relationship as negotiated cooperation helps organize evidence, provided the metaphor does not smuggle human intention into underground biology.`, "mycorrhizal fungi and plant roots"),
  e(10, "World affairs", "A Constitution Written after the Storm", `In this fictional island federation, a devastating storm exposes deep regional inequalities and prompts demands for constitutional reform. The government convenes an elected assembly, but emergency displacement means many citizens cannot vote from their registered districts. Rather than proceed under a false appearance of inclusion, the court extends registration and creates temporary constituencies for displaced communities. Delegates debate central disaster powers, local autonomy, fiscal transfers, and enforceable social rights. A draft is published clause by clause with minority reports, then revised before a referendum. The final text cannot guarantee fair government; constitutions distribute authority but still require institutions, resources, interpretation, and civic pressure. The process nevertheless changes legitimacy by making disagreement visible and by allowing affected people to contest both the rules and the conditions under which those rules are written.`, "fictional inclusive constitutional reform"),
  e(10, "Everyday life", "The Promise Hidden in a Group Chat", `Years after university, Mei discovers an old group message in which she casually promised to share profits if a friend's design ever became commercially useful. Her current company has independently developed a similar product, and the friend never signed a contract. Lawyers say the message is probably too vague to determine ownership. Mei could treat that uncertainty as permission to remain silent. Instead, she reconstructs the design history, separates common ideas from distinctive contributions, and invites the friend to review the evidence with independent advice. They do not agree on every memory, but they negotiate credit and a limited royalty for material the company did use. The decision costs less than litigation yet more than legal minimum compliance. Mei learns that ethical responsibility often begins where enforceable obligation becomes uncertain, not where certainty makes action unavoidable.`, "informal promises and ethical responsibility"),
  e(10, "History", "How Smallpox Eradication Was Verified", `The global eradication of smallpox was not established merely because reported cases declined. After the World Health Organization intensified its program in 1967, vaccination was combined with surveillance, investigation, containment, and international coordination. The last known naturally occurring case was identified in Somalia in 1977. Teams then searched for continuing transmission, and independent commissions examined evidence from countries and regions. In 1980, the World Health Assembly declared smallpox eradicated. The achievement depended on a biological advantage—the virus had no known nonhuman reservoir that could silently reintroduce infection—but also on field workers, laboratories, political cooperation, and methods adapted to local conditions. Eradication means worldwide interruption of natural transmission; it does not erase laboratory risk, historical suffering, or the need to distinguish smallpox from related diseases.`, "smallpox eradication and certification"),
  e(10, "Science", "Entanglement without Faster Messages", `Quantum entanglement describes correlations between parts of a joint quantum system that cannot be reproduced by assigning each part an ordinary, independent set of pre-existing local properties. Measurements on separated particles can display patterns that violate Bell inequalities, provided experiments address alternative explanations such as detector inefficiency and unnoticed communication. The correlations are stronger than classical intuition permits, but they do not supply a channel for controllable faster-than-light messages. Each observer's local outcome is not chosen at will, and comparing the pattern still requires ordinary communication. Entanglement is therefore neither telepathy nor a thread carrying secret instructions through space. It is a structural feature of quantum states, central to tests of foundations and to technologies such as quantum communication, sensing, and computation, all of which remain constrained by physical implementation and noise.`, "quantum entanglement and communication limits"),
  e(10, "Mystery and adventure", "The Evidence Bag That Arrived Before the Crime", `A sealed evidence bag appears at a laboratory on Monday, although the alleged burglary is not reported until Tuesday. Its barcode is valid, and the analyst's signature appears in the database. Detective Amara resists the convenient theory that someone predicted or staged the crime. She reconstructs custody from independent records: label-printer logs, door access, camera time sources, courier scans, and the database's revision history. A software migration had interpreted a test record in coordinated universal time as local time, while an unused training bag remained physically stored in the intake cabinet. On Tuesday, a clerk reused the visible barcode instead of generating a new one. The impossible chronology dissolves, but the investigation reveals two serious failures—reusable identifiers and mutable timestamps. Amara preserves the error itself as evidence and requires append-only audit records before the system returns to service.`, "chain of custody and timestamp errors"),
  e(10, "Travel and culture", "Returning the Mask from the Glass Case", `The National Museum of Lyr is imaginary, as is the coastal community asking it to return a ceremonial mask acquired during colonial rule. Museum officials initially frame the dispute as a choice between universal public access and private local possession. Community representatives reject that binary: the mask remains culturally active, was transferred under coercive conditions, and should not be treated only as an art object. Researchers examine acquisition papers, oral histories, conservation needs, and the authority of current claimants. The parties agree on return, a community-controlled digital record, and future loans initiated by the owners rather than presumed by the museum. Repatriation does not settle every question about competing descendants or care, but it changes who has the right to decide. The process shows that preservation without legitimate custody can perpetuate the history a label claims merely to describe.`, "fictional museum repatriation"),
  e(10, "People and biography", "Ada Counts Who Is Missing", `Ada is a fictional demographer asked to estimate the population of an informal settlement before public services are allocated. Satellite images suggest household numbers, but roofs do not reveal occupancy, migration, age, disability, or people sharing one structure. A rapid phone survey excludes residents without stable numbers, while official addresses omit much of the area entirely. Ada combines mapping with locally recruited enumerators, repeated visits, transparent sampling, and privacy protections. She reports ranges instead of a false point estimate and documents which groups may still be undercounted. Officials complain that uncertainty weakens the funding request. Ada argues the opposite: an honest interval shows what evidence supports and where exclusion may persist. Her work treats missing data not as empty space, but as a pattern shaped by power, mobility, trust, and administrative recognition.`, "fictional inclusive population estimation"),
);

const editorialRevisions = {
  "The Moon in a Mug": `A small moon sits in a boy's cup. It gives a soft light. The boy does not take a drink. He brings the cup out under the dark sky. The moon goes up and grows as it rises. Soon it is high above the house. The boy goes home in its light.`,
  "A Turtle Comes Up for Air": `A sea turtle lives in the ocean, but it needs air. It goes up and puts its nose above the water. Then it takes air in and goes down once more. A mother sea turtle must also go onto land. She puts her eggs in the sand and then returns to the sea.`,
  "Clay Held the First Marks": `Long ago, people in an old part of the Middle East wrote on wet clay. They used a cut plant stem. It made small marks in the clay. The marks could hold lists, letters, tales, and numbers. When the clay became dry, the words could stay for a very long time.`,
  "Water Leaves a Leaf": `A plant takes water from the ground. The water goes up inside the plant. Some of it then goes out from the leaves as a gas. We cannot see this gas. Put a clear bag around some leaves, and small drops may form in the bag. The drops came from water in the plant.`,
  "Peter Runs from the Garden": `Peter Rabbit goes into a garden after his mother tells him not to go. He takes food from the plants. The man who owns the garden sees Peter and runs after him. Peter loses his shoes and coat, but he finds the gate. He gets home tired and sick.`,
  "Bread at Sun Street": `This town is not real. A girl smells warm bread on Sun Street. A bread maker shows her three round pieces. The girl points before she puts out her hand. She buys one and sits by the town square. A family gives her fruit, and she gives them some bread.`,
  "A Sign Maker Uses Clear Words": `This sign maker is not a real person. A park sign has too many words. Children do not know which way to go. The worker asks what they need. He makes short signs with big letters and simple pictures. The children can now find the garden and the rest room with less help. More boys and girls can use the park on their own.`,
  "A Bat Listens for Dinner": `A bat can find small insects by making high sounds. The sound hits a thing and comes back. The bat uses the sound that comes back to learn where the thing is. It can do this in the dark. A bat can also see. It does not use sound because it is blind.`,
  "Pompeii under Ash": `In the year 79, Mount Vesuvius sent hot rock, ash, and gas into the air. The material covered Pompeii and places near it. Many streets, homes, and things were left under the ground. Much later, people began to find parts of Pompeii again. The site helps us learn about life in a Roman town.`,
  "Why the Moon Looks Different": `The Sun always lights one half of the Moon. The Moon moves around Earth. As it moves, we see more or less of its bright side. This is why its shape seems to change through the month. Earth's shadow is not the cause of these daily changes. It covers the Moon only at special times.`,
  "The Lunchbox with the Wrong Name": `A boy finds his food box, but a girl's name is on it. Inside, he sees the same apple and bread that he put there. He looks under the box. His own name is on a loose strip of paper. Two food boxes had touched in a school bag, and the strips moved from one box to the other.`,
  "Nara Repairs One Bicycle": `This bike worker is not a real person. She starts with one broken bike in a small shed. She tells each person what she will fix and keeps old parts that are still good. Soon, families bring bikes before school. Once a month, she shows people how to make a seat firm and put a chain back in place.`,
  "A Beaver Changes a Stream": `An animal called a beaver cuts small trees and puts the wood across moving water. The wall can slow the stream and make a pool or wet area. Fish, birds, and many small animals may use the new place. The result is not the same in every area. The water can also cover a road or field, so people may need a safe plan.`,
  "A Cup Returned with a Note": `A woman takes a work friend's cup home and keeps it for a week. She feels bad and says nothing. On Friday, she cleans the cup, fills it with tea, and adds a short note: “I am sorry this took so long.” Her friend laughs and says that the week of silence was harder than waiting for the cup.`,
  "The Charter at Runnymede": `In 1215, King John of England agreed to a text called Magna Carta after a fight with a group of powerful men. It set some limits on what the king could do. It did not give most people a vote or make a modern form of rule. The first deal soon failed, but later forms helped build the idea that a king must also follow the law.`,
  "Cabbage Water Changes Color": `Water made from red cabbage can change color when it meets an acid or a base. A student puts the water into three clear cups. Lemon juice makes one cup pink. A mix of water and baking soda can make another cup blue or green. The colors give a clue, but they do not give an exact number. The student wears eye protection and does not taste any test cup.`,
  "The Muddy Number Seven": `Each night, a mark like the number seven appears on a hall door. A girl waits near it and hears a low sound. A work cart turns at the corner, and one wet wheel hits the door. The wheel has seven high lines on it. Each turn leaves the same mark. The girl moves the cart and washes the door.`,
  "How a Penguin Holds Heat": `A penguin in a cold place has several ways to hold body heat. Many close feathers keep air near the skin. Body fat also slows heat loss. The birds may stand close to one another or turn away from strong wind. They must clean and set their feathers often. These features do not make cold harmless. Wet feathers, poor food, age, and health can still make it hard for a bird to stay warm.`,
  "The Calendar No One Owned": `Four friends share a home and often buy the same food. They make an online list, but no one keeps it up to date. Then they put a small board next to the cold food box. The person who uses the last pack writes its name on the board. Before going to the shop, one friend takes a picture of the list. The simple system works because it sits where people need it.`,
  "The Army Made of Clay": `In 1974, people working near Xi'an found pieces of clay figures. Later work showed large holes near the resting place of Qin Shi Huang, the first emperor of a united China. The holes held thousands of full-size clay soldiers, as well as horses and war vehicles. Their faces, hair, clothes, and ways of standing are not all the same. Much of the whole area is still under the ground. People must care for what has been found while they look for more.`,
  "A Clear Bag around a Branch": `Water enters a plant through its roots and goes up to the leaves. Small holes in the leaves let water move into the air as gas. This process is called transpiration. It is hard to see. If a clear bag is put around a branch with leaves, drops may form as the gas turns back into water. Light, heat, wind, dry air, and the kind of plant can all change how fast water moves.`,
  "The Blue Light in Cabin Nine": `A closed train room shows a blue light each time the train enters a tunnel. The worker checks the power and finds no problem. A passenger across the hall is reading from a bright screen in a blue case. In the dark, the screen's light hits the case and then crosses two glass windows. The empty room has no lamp. The strange blue light is only a moving reflection.`,
  "Bread Rises on Yeast Gas": `Yeast is a small living fungus. In bread dough, it uses sugar and gives off carbon dioxide gas. The gas makes many little spaces in the dough. Flour and water form a network that can hold much of the gas, so the dough grows in size. Warmth may make the yeast work faster, but high heat can kill it. Salt, sugar, water, flour, and time also affect the loaf. In the oven, heat sets the bread's shape and makes new tastes and smells.`,
  "Anne Finds a Home at Green Gables": `A brother and sister expect a boy who can help on their farm. Instead, they meet Anne Shirley, an orphan who is full of talk and ideas. Marilla Cuthbert thinks about sending Anne back, but she lets the girl stay. Anne makes a close friend, argues with Gilbert Blythe, causes many small disasters, and works hard at school. Over time, she becomes part of the town and the family. After Matthew dies and Marilla needs help, Anne changes her teaching plan so she can remain near Green Gables. The choice shows that she has found both a home and a future.`,
  "Fogg Races around the World": `A man named Phileas Fogg bets that he can travel around the world in eighty days. Fogg leaves London with his servant, Passepartout, and uses ships and trains to move east. A police officer follows because he wrongly thinks Fogg stole money from a bank. Delays and danger threaten the trip, and a woman named Aouda joins the group after they help her. Back in London, Fogg thinks he is one day too late. He then learns that going east around Earth gave him one calendar day. He wins the bet and asks Aouda to marry him.`,
  "Fungi Return a Fallen Tree to the Forest": `A fallen tree may look still, but it becomes food and shelter for many forms of life. Wood-decay fungi release enzymes that break large plant compounds into smaller parts they can use. Insects open paths, bacteria add other changes, and water affects which organisms grow. As the log breaks down, useful material can return to the soil. It may also hold water and protect young plants or animals. Not every fungus does the same work, and the speed changes with tree type, heat, air, and climate. Dead wood has great value in a forest, though managers must also consider paths, fire, and other local risks. Each site needs its own balance.`,
  "The Evidence Bag That Arrived Before the Crime": `A sealed evidence bag reaches a laboratory on Monday, although the reported break-in occurs on Tuesday. Its label number is valid, and a staff signature appears in the computer record. Detective Amara does not accept the easy claim that someone predicted or planned the crime. She builds the chain of custody from door records, camera clocks, delivery scans, printer history, and saved changes in the system. During a software move, a test entry recorded in universal time had been read as local time. An unused training bag also remained in the intake room. On Tuesday, a clerk copied its old label number instead of making a new one. The impossible order of events disappears, but two serious flaws remain: numbers could be used again, and old time entries could be changed. Amara keeps the error in the case file and requires a record that preserves every change.`,
};

for (const entry of entries) {
  if (editorialRevisions[entry.title]) entry.text = editorialRevisions[entry.title].trim();
}

const loaded = JSON.parse(fs.readFileSync(storyPath, "utf8"));
const existing = loaded.length === finalCount ? loaded.slice(0, baseCount) : loaded;
if (existing.length !== baseCount || existing.at(-1)?.id !== "s1910") {
  throw new Error(`Expected the 1,910-story base corpus ending at s1910, found ${loaded.length}.`);
}
if (entries.length !== finalCount - baseCount) throw new Error(`Expected 90 additions, found ${entries.length}.`);

const additions = entries.map((item, index) => ({
  id: `s${String(baseCount + index + 1).padStart(3, "0")}`,
  level: item.level,
  topic: item.topic,
  title: item.title,
  text: item.text,
  wordCount: item.text.split(/\s+/).filter(Boolean).length,
  subtopic: item.subtopic,
  contentType: contentTypes[item.topic],
  editorialStatus: "published",
  factChecked: true,
  reviewedAt,
  sourceWork: item.sourceWork,
  vocabularyVersion: "v2",
}));

const levelCounts = new Map();
const topicCounts = new Map();
const cellCounts = new Map();
for (const story of additions) {
  levelCounts.set(story.level, (levelCounts.get(story.level) || 0) + 1);
  topicCounts.set(story.topic, (topicCounts.get(story.topic) || 0) + 1);
  const cell = `${story.level}|${story.topic}`;
  cellCounts.set(cell, (cellCounts.get(cell) || 0) + 1);
  if (story.topic === omittedTopicByLevel[story.level]) throw new Error(`Unexpected omitted cell: ${cell}`);
}
if ([...levelCounts.values()].some((count) => count !== 9) || levelCounts.size !== 10) throw new Error("Each level must receive nine stories.");
if ([...topicCounts.values()].some((count) => count !== 9) || topicCounts.size !== 10) throw new Error("Each topic must receive nine stories.");
if ([...cellCounts.values()].some((count) => count !== 1) || cellCounts.size !== 90) throw new Error("Each selected level/topic cell must receive one story.");

const all = existing.concat(additions);
const duplicates = (field) => all
  .map((story) => story[field])
  .filter((value, index, values) => values.indexOf(value) !== index);
for (const field of ["id", "title", "text"]) {
  const found = [...new Set(duplicates(field))];
  if (found.length) throw new Error(`Duplicate ${field}: ${found.join(" | ")}`);
}
if (all.length !== finalCount || all.at(-1)?.id !== "s2000") throw new Error("Final sequence is not s001-s2000.");
fs.writeFileSync(storyPath, `${JSON.stringify(all, null, 2)}\n`);
console.log(`Added or refreshed ${additions.length} stories: ${additions[0].id}-${additions.at(-1).id}`);
