#!/usr/bin/env node
"use strict";

const fs = require("fs");
const path = require("path");

const root = path.resolve(__dirname, "..");
const storyPath = path.join(root, "stories.json");
const reviewedAt = "2026-09-14";
const topics = [
  "Fantasy/stories", "Nature and animals", "World affairs", "Everyday life", "History",
  "Science", "Famous books", "Mystery and adventure", "Travel and culture", "People and biography",
];
const contentTypes = {
  "Fantasy/stories": "narrative-fiction",
  "Nature and animals": "explanatory-nonfiction",
  "World affairs": "explanatory-nonfiction",
  "Everyday life": "narrative-fiction",
  History: "historical-narrative",
  Science: "explanatory-nonfiction",
  "Famous books": "classic-retelling",
  "Mystery and adventure": "mystery-fiction",
  "Travel and culture": "travel-vignette",
  "People and biography": "fictional-biography",
};
const e = (level, topic, title, text, subtopic, sourceWork = null) => ({
  level, topic, title, text: text.trim(), subtopic, sourceWork,
});

const entries = [
  // Level 1
  e(1, "Fantasy/stories", "The Pocket Cloud", `Mara finds a cloud in her coat. It is small and soft. The cloud is thirsty, so she gives it water. It rains into a blue cup. Then it grows. Mara opens the window. The cloud floats out and joins the wide sky.`, "small magic and care"),
  e(1, "Nature and animals", "A Bee Carries Dust", `A bee lands on a flower. Yellow dust sticks to its body. The bee flies to another flower. Some dust moves with it. This dust is pollen. Moving pollen can help a plant make seeds. The bee gets food, and the flower gets help.`, "bees and pollination"),
  e(1, "World affairs", "A School Table for All", `This is a fictional policy example. A school has no lunch room. Some children bring food, but some do not. Families, cooks, and teachers make a plan. The town pays part of the cost. A farm gives fresh food. Soon every child can eat before afternoon class.`, "fictional school meal policy"),
  e(1, "Everyday life", "The Last Clean Spoon", `Niko wants soup, but every spoon is dirty. He starts to wash one. Then he sees the full sink. Niko washes all the spoons and puts them away. His sister dries the bowls. Their soup is a little cold, but the kitchen is ready for morning.`, "shared household work"),
  e(1, "History", "The Stone with Three Scripts", `A large old stone was found in Egypt in 1799. The same order was written on it in three scripts. One was ancient Greek. People could still read Greek, so it helped them study the other signs. The stone became an important key for reading Egyptian writing.`, "the Rosetta Stone"),
  e(1, "Science", "Noon beneath the Tree", `A tree makes a long shadow in the morning. Near noon, the shadow is shorter. Later, it grows long again. The Sun seems to move across the sky because Earth turns. The light reaches the tree from a new direction, so the shadow changes too.`, "sunlight and shadows"),
  e(1, "Famous books", "Mary Opens the Secret Garden", `Mary comes to a large house in England. She feels lonely and angry. Then she finds a locked garden. A bird helps her find the key. Mary, Dickon, and Colin care for the hidden place. As the garden grows, the children become stronger and happier too.`, "growth and friendship", "The Secret Garden"),
  e(1, "Mystery and adventure", "The Wet Red Hat", `A wet red hat is on the library floor. Jo sees no owner. A line of drops goes to the back door. Outside, a child stands under a tree. The wind took his hat through the open door. Jo gives it back, and the child laughs.`, "a lost object clue"),
  e(1, "Travel and culture", "Soup at Moon Bay", `Moon Bay is an imaginary town. Aya walks by its small boats. Rain begins, and she runs under a food tent. A cook gives her warm bean soup. Aya helps move the chairs away from the rain. When the sky clears, they eat together.`, "an imaginary harbor meal"),
  e(1, "People and biography", "Oren Fixes the Park Gate", `Oren is a fictional park worker. A gate is hard to open. Parents with small children ask for help. Oren cleans the metal and moves the handle lower. He tests it with the families. The gate now opens with one hand, and more people can use the park.`, "fictional accessible park work"),

  // Level 2
  e(2, "Fantasy/stories", "The Shoes That Waited", `Two silver shoes wait outside Imani's door. When she puts them on, they walk toward anyone who needs help. They take her to a man with heavy bags, a lost child, and a dog behind a fence. At sunset, the shoes bring Imani home. The next morning, they are gone.`, "enchanted shoes and kindness"),
  e(2, "Nature and animals", "An Otter Holds On", `A sea otter floats on its back. It may wrap itself in kelp while it rests, so moving water does not carry it far away. Otters also eat animals such as sea urchins. When otters limit these plant eaters, kelp forests can have a better chance to grow.`, "sea otters and kelp forests"),
  e(2, "World affairs", "Water at the Bus Stop", `This fictional town has very hot summers. People wait for buses in full sun. The town cannot build a large shelter at every stop. Riders mark the busiest places on a map. Workers add shade and water there first. They also plant trees where roots will not block the path.`, "fictional heat and transit planning"),
  e(2, "Everyday life", "The Quiet Phone Basket", `Lena's family keeps looking at phones during dinner. Her little brother puts an empty basket on the table. Everyone agrees to leave phones there for twenty minutes. At first, the room feels too quiet. Then their father tells a funny story. The basket stays on the table the next night.`, "family attention and devices"),
  e(2, "History", "Roads Built in Layers", `Roman road builders often prepared the ground before placing the top stones. The exact design changed from place to place. Some roads had several layers, side ditches, and a raised center that helped water move away. These roads linked towns, forts, farms, and ports across the empire.`, "Roman road construction"),
  e(2, "Science", "Sound from a String", `Kai pulls a string tight between two cups. He speaks into one cup while Mei holds the other. His voice makes the first cup move a little. The string carries that movement to the second cup. It makes the air there move, and Mei hears Kai's words.`, "vibration and sound"),
  e(2, "Famous books", "Dorothy Follows the Yellow Road", `A great wind carries Dorothy and her house to Oz. She wants to return home. On a yellow road, she meets a scarecrow, a tin man, and a lion. Each wants something too. They face danger together. In the end, Dorothy learns that her silver shoes can carry her home.`, "home and courage", "The Wonderful Wizard of Oz"),
  e(2, "Mystery and adventure", "Three Bells after Closing", `The bakery is closed, but a bell rings three times inside. Mina checks the front door. It is locked. She walks around the building and hears the sound again. A loose spoon is hanging near an open window. Each wind moves it against a glass jar. Mina closes the window.`, "a sound clue after dark"),
  e(2, "Travel and culture", "Painted Doors in Luma", `Luma is an imaginary hill village with doors painted in bright colors. Taro asks why two blue doors have white circles. A shopkeeper explains that her family chose the sign many years ago. Other families use leaves, birds, or lines. Taro draws the doors but does not copy the private names beside them.`, "imaginary village art and respect"),
  e(2, "People and biography", "Sela Starts a Seed Shelf", `Sela is a fictional library worker. Gardeners often ask where they can share extra seeds. She clears one shelf and makes simple paper bags. Each bag shows the plant name and the year. Neighbors take only what they need and bring seeds back later. Sela checks the labels every Friday.`, "fictional community seed sharing"),

  // Level 3
  e(3, "Fantasy/stories", "The Map beneath the Paint", `Ari buys an old table and begins to sand its top. Under the green paint, thin gold lines appear. They form a map of streets that do not exist. That night, one line moves toward his window. Ari follows it to a closed garden and finds a box of letters. The map fades after he returns the letters to their owner.`, "a changing map and returned letters"),
  e(3, "Nature and animals", "The Owl's Quiet Wing", `Owls cannot fly without sound, but several feather features can reduce it. A comb-like edge on the front of the wing breaks up moving air. Soft surfaces and fringed edges also change the noise. Quiet flight may help an owl hear prey and approach it, especially in darkness. Different owls do not use these features in exactly the same way.`, "owl feathers and flight noise"),
  e(3, "World affairs", "A Clinic on Market Day", `This fictional district has villages far from its only clinic. Building ten new clinics would take years. Residents suggest a smaller first step: a health van that visits on market days. Nurses choose the route with village groups and publish the timetable. After three months, they change two stops because older patients cannot reach them safely.`, "fictional mobile health service"),
  e(3, "Everyday life", "The Recipe with No Number", `Mara finds her grandmother's soup recipe, but it says only “some beans” and “enough water.” She tries to measure everything. The first pot is too thick. Instead of giving up, she cooks beside her grandmother and watches the color and movement of the soup. Mara adds her own notes without changing the old card.`, "learning an unwritten family recipe"),
  e(3, "History", "Books Hidden in Family Chests", `For centuries, Timbuktu was a center of trade and learning. Families and libraries kept manuscripts on law, religion, language, science, and daily affairs. During the 2012 conflict in Mali, local workers moved many volumes away from danger. The rescue was difficult, and some material was damaged, but thousands of manuscripts survived through careful local action.`, "Timbuktu manuscript preservation"),
  e(3, "Science", "Three Ways to Make a Rock", `Rocks are often grouped as igneous, sedimentary, or metamorphic. Melted rock that cools can become igneous rock. Pieces of older material can collect, press together, and form sedimentary rock. Heat and pressure can change a rock without fully melting it, making metamorphic rock. Over long periods, one kind can change into another.`, "the rock cycle"),
  e(3, "Famous books", "Pinocchio Wants to Be Real", `Geppetto makes a wooden puppet named Pinocchio. The puppet can walk and talk, but he often ignores good advice. He leaves school, follows false friends, and tells lies. His choices bring trouble to himself and Geppetto. After Pinocchio learns to care for others and act bravely, he is changed into a real boy.`, "truth and responsibility", "The Adventures of Pinocchio"),
  e(3, "Mystery and adventure", "The Key in the Bird Feeder", `Every Monday, a brass key appears in the park's bird feeder. Nia watches from a bench but sees only birds and runners. Then she notices a groundskeeper filling the feeder from an old tin. A hole in the tin's pocket drops the key each week. It opens a tool shed, not a treasure box, and Nia returns it.`, "a repeated park clue"),
  e(3, "Travel and culture", "The Long Table of Neris", `Neris is an imaginary farming town. On the first cold evening of autumn, families carry one dish to a long outdoor table. A visitor named Bo thinks he must bring something expensive. His host asks him to slice apples instead. During the meal, Bo learns that helping with the work matters more than arriving with a perfect gift.`, "an imaginary harvest gathering"),
  e(3, "People and biography", "Mavi Draws the Night Route", `Mavi is a fictional bus driver who finishes after midnight. She notices that hospital workers must walk along a road with no lights. Mavi records where passengers get off and shares the notes with her manager. The company tests one later stop near the hospital gate. Mavi keeps asking riders whether the change actually helps.`, "fictional late-night transport improvement"),

  // Level 4
  e(4, "Fantasy/stories", "A Library for Lost Minutes", `Behind the station clock, Jun finds a room filled with glass jars. Each jar holds a minute that someone wasted and wished to recover. A keeper lets Jun borrow five minutes, but warns that he cannot add them to his own day. Jun gives one minute to a nurse who missed her train and four to a father racing to a school concert. The jars glow, then vanish. Jun still arrives home late, yet he no longer feels that the evening was lost.`, "time, generosity, and choice"),
  e(4, "Nature and animals", "Roots in Salt Water", `Mangroves grow where land and sea meet in warm regions. Their roots face salt, soft mud, tides, and water with little oxygen. Different species manage these conditions in different ways, including limiting salt at the roots or moving some salt into older leaves. Tangled roots can slow water and trap sediment. They also create shelter for young fish and other animals. Mangroves do not stop every storm, but healthy forests can reduce some wave energy and coastal erosion.`, "mangrove adaptations and habitat"),
  e(4, "World affairs", "Votes for a Small Park", `This fictional city gives one neighborhood a limited public budget. Residents may propose projects and vote, but the process first attracts mostly people with free evenings. Organizers add a weekend meeting, translated forms, child care, and paper ballots at the library. A shaded play area wins, while a costly fountain does not. The city publishes the vote and the final price. Participation remains imperfect, yet the changes allow more residents to shape the choice.`, "fictional participatory budgeting"),
  e(4, "Everyday life", "The Chair beside the Lift", `At her new office, Emi notices a chair beside the lift on every floor. She assumes the chairs are decoration until a colleague explains that he sometimes needs to sit while waiting. Emi had planned to remove them to make the hall look cleaner. Instead, she asks people who use the space. They move one chair away from a narrow doorway and keep the others. The hall becomes easier to cross without taking away a useful place to rest.`, "inclusive decisions at work"),
  e(4, "History", "Ink, Metal, and Many Pages", `Printing with movable type existed in East Asia before Johannes Gutenberg worked in Europe. In fifteenth-century Mainz, Gutenberg combined metal type, oil-based ink, a press, and skilled labor into an effective system for producing books. Printing did not make books instantly cheap or literacy universal. It did, however, allow workshops to produce many consistent copies more quickly than copying a whole book by hand. Printed works then moved through trade, schools, religious debates, and government.`, "Gutenberg and European printing"),
  e(4, "Science", "Leaves Build Sugar", `A green plant uses light energy to make sugars from carbon dioxide and water. This process is photosynthesis. It takes place mainly in structures called chloroplasts, which contain chlorophyll. Oxygen is released as part of the overall process. A plant later uses the stored chemical energy for growth and repair. Photosynthesis depends on several conditions, so more light does not always mean unlimited growth. Water, temperature, nutrients, and the plant's own biology also matter.`, "photosynthesis basics"),
  e(4, "Famous books", "Jim and the Island Map", `Jim Hawkins discovers a map in a dead sailor's chest. It appears to show where a pirate buried treasure. Jim joins a voyage to the island, but many crew members secretly follow Long John Silver and plan a mutiny. Silver can be friendly, clever, and dangerous at the same time. Jim takes bold risks, the loyal group survives the fighting, and some treasure is recovered. The journey ends, but the memory of the island continues to trouble Jim.`, "loyalty, greed, and courage", "Treasure Island"),
  e(4, "Mystery and adventure", "The Window That Lit at Noon", `An empty lighthouse flashes once every day at noon. Sami knows its lamp has been removed, so she watches from the opposite cliff. The flash appears again under a clear sky. She marks the angle, then visits with the harbor keeper. A broken mirror lies behind an upper window. For a few minutes each day, sunlight strikes it and reflects across the bay. They move the glass before it can confuse a boat.`, "reflected light as a clue"),
  e(4, "Travel and culture", "Paper Boats in Alder City", `Alder City is imaginary, but its river festival feels old to its residents. People fold paper boats and write a hope inside each one. Environmental rules now keep the boats out of the river. Instead, volunteers place them on long blue cloth through the square. Visitor Leila first thinks the change makes the event less real. After helping collect every boat for recycling, she sees how a custom can keep its meaning while changing its material.`, "an imaginary low-waste festival"),
  e(4, "People and biography", "Rafi Tests the Quiet Crossing", `Rafi is a fictional sound engineer who loses much of his hearing as an adult. Near his home, crossing signals use only beeps. He works with residents who have different needs and helps test a signal that also vibrates and shows a bright visual pattern. Early versions are confusing in rain, so the team changes the casing and timing. Rafi's most useful contribution is not a single invention; it is his insistence that the people using a system must be part of evaluating it.`, "fictional accessible street signals"),

  // Level 5
  e(5, "Fantasy/stories", "The Tailor of Borrowed Courage", `In a narrow shop, a tailor sews courage into coat linings. The courage is borrowed, not created, and must come from someone willing to share it. Ivo asks for enough to speak before the city council. The tailor offers a thread from a nurse's first night shift and another from a child learning to swim. Wearing the coat, Ivo begins his speech, but the borrowed courage fades after one minute. He continues anyway, voice shaking. When he returns the coat, the tailor finds a new silver thread inside. It belongs to Ivo and may now be lent to someone else.`, "courage shared through magic"),
  e(5, "Nature and animals", "A Butterfly across Generations", `Monarch butterflies in eastern North America make a remarkable seasonal journey. No single butterfly completes the entire yearly cycle. Several generations move north and reproduce during spring and summer. A later generation flies much farther south to central Mexico, where large numbers spend the winter. In spring, those butterflies begin the return, and their descendants continue it. The route depends on inherited behavior as well as environmental cues. Weather, habitat loss, and the availability of milkweed and nectar plants can affect survival along the way.`, "monarch butterfly migration"),
  e(5, "World affairs", "The Warning before the Flood", `This fictional coastal region has sirens, but fishers working offshore cannot hear them. Officials first propose louder equipment. Community groups point out that warnings also fail people who are deaf, speak another language, or lack reliable phones. The region adds radio messages, visual signals, marked high-ground routes, and local volunteers. A yearly drill reveals that one bridge becomes blocked by traffic. Planners change the route and publish the problem instead of calling the exercise a success. The warning system improves because residents test the full chain from forecast to safe action.`, "fictional inclusive early-warning system"),
  e(5, "Everyday life", "The Box Marked Someday", `When Dara moves apartments, she finds a box labeled “Someday.” It contains a language course, unused paints, a broken radio, and plans for a garden she never planted. Her first impulse is to feel guilty. Instead, she sorts the objects by the life she wants now. She gives the paints to a neighbor, repairs the radio, and recycles the course notes. The garden plan stays. Dara does not promise to become a perfect gardener; she buys one pot and plants herbs on the windowsill. The smaller beginning feels more honest than keeping a box of imagined futures.`, "changing goals and small beginnings"),
  e(5, "History", "Messages That Became Dots and Lines", `Electrical telegraph systems allowed messages to travel through wires as signals. In the 1830s and 1840s, several inventors developed workable designs in Europe and North America. Samuel Morse and Alfred Vail helped create a system that used coded patterns and was adopted widely in the United States. Telegraph networks changed how quickly news, business orders, and railway information could move. They still required wires, equipment, trained operators, and offices. The technology did not erase distance, but it separated the speed of a message from the speed of a horse, ship, or train carrying paper.`, "development of the telegraph"),
  e(5, "Science", "Continents on Restless Plates", `Earth's outer rocky layer is broken into moving tectonic plates. Their motion is usually slow, measured over years, but its effects accumulate over millions of years. At some boundaries, plates pull apart and new crust forms. Elsewhere, one plate may move beneath another, or two plates slide past each other. These interactions help explain many earthquakes, volcanoes, mountain ranges, and ocean basins. Plate tectonics is not a claim that continents drift freely across the sea floor. Continents are parts of plates, and the plates move within Earth's larger system as heat escapes from the interior.`, "plate tectonics"),
  e(5, "Famous books", "Toad Learns Too Slowly", `Mole leaves his spring cleaning and discovers the river with Rat. Their friend Badger values a quiet life, while Toad constantly seeks excitement. Toad becomes obsessed with motorcars, drives recklessly, steals a car, and lands in prison. He escapes in disguise, only to learn that weasels have taken Toad Hall. His friends help him win the house back. Toad promises to change, and for a time he behaves modestly. The story enjoys his energy while showing how often friendship must rescue him from the results of his own pride.`, "friendship and reckless pride", "The Wind in the Willows"),
  e(5, "Mystery and adventure", "The Museum's Missing Dust", `A museum guard notices a clean rectangle on a dusty shelf. Nothing is listed as missing, yet the mark is fresh. Investigator Nara compares old room photographs and sees that a plain wooden block once sat there. A label had fallen behind the cabinet years earlier, so staff assumed the block was packing material. It is actually the base for a small sculpture being studied in another room. No thief took it; poor records separated two parts of one object. Nara updates the catalog and asks the museum to photograph every piece before the next move.`, "a cataloging mystery"),
  e(5, "Travel and culture", "The Guest Who Asked First", `In the imaginary desert settlement of Selka, homes have painted inner courts that visitors rarely see. Photographer Ben is invited to tea by a local guide. The afternoon light forms beautiful patterns on the wall, and he lifts his camera. Then he lowers it and asks whether photographs are welcome. His host agrees to one picture of the wall but not of the family gathering. Ben enjoys the tea without documenting it. Later, the single permitted photograph matters more to him because it carries a clear memory of the conversation around it.`, "travel photography and consent"),
  e(5, "People and biography", "Nadia Counts the Empty Seats", `Nadia is a fictional theater manager. She notices that free community performances still have many empty seats. Rather than blaming the audience, she interviews people who reserved tickets but did not attend. Some lacked evening buses; others expected extra costs or did not know whether children were welcome. Nadia tests an afternoon show, clearer price information, and a small play area. Attendance rises, although not for every program. Her work shows that an open door is not the same as practical access. She keeps the failed ideas in her report so the next season begins with evidence rather than assumptions.`, "fictional access research in the arts"),

  // Level 6
  e(6, "Fantasy/stories", "The Archive of Unsaid Apologies", `Beneath the courthouse, Elian discovers an archive that stores apologies people prepared but never offered. Some are careful speeches; others are only three frightened words. The archivist explains that regret becomes heavier when preserved without action. Elian finds a page written in his own hand after an argument with his brother. He wants to revise it until it sounds wise, but the ink refuses to change. The page records what he truly understood at the time, including what he failed to understand. Elian takes it upstairs and speaks plainly. His brother does not forgive him at once. Still, the page becomes light enough to fold, which the archivist says is a beginning rather than an ending.`, "apology, memory, and responsibility"),
  e(6, "Nature and animals", "Gifts from Returning Salmon", `Many salmon hatch in fresh water, grow in the ocean, and later return to rivers to reproduce. During their lives at sea, they build body tissue from marine food. When salmon return, predators eat some of them, while others die after spawning. Their bodies and waste add nutrients to streams and nearby land. In some watersheds, scientists can trace marine nutrients in insects, plants, and animals far from the coast. The size of this effect varies with the river, salmon population, and local food web. Salmon are therefore more than travelers between habitats: they can also move material and energy from ocean ecosystems into inland ones.`, "salmon migration and nutrient movement"),
  e(6, "World affairs", "Lessons in the Temporary Hall", `This fictional country receives families displaced by a regional conflict. Local schools are already crowded, so officials propose separate tents with a short emergency curriculum. Parents from both new and established communities worry that separation will become permanent. The district converts a public hall into shared classrooms, hires additional teachers, and recognizes previous school records when evidence is available. It also offers language support without treating a child's first language as a problem. The arrangement is imperfect: travel remains difficult, and some students have missed years of school. Monthly meetings allow families and teachers to report barriers. The policy is judged not by enrollment alone, but by attendance, learning, safety, and whether students can move into stable education.`, "fictional inclusive education response"),
  e(6, "Everyday life", "The Meeting with an Empty Chair", `Priya's team schedules another meeting about delayed work. Everyone arrives prepared to defend a different explanation. Before they begin, Priya places an empty chair near the table and labels it “the person using our service.” The gesture feels artificial, yet it changes the first question. Instead of asking who missed a deadline, the team traces what a customer experiences when information arrives late. They discover that two departments request the same document in different formats. Removing that duplication saves more time than blaming either group. The chair does not solve future conflicts, and Priya refuses to treat it as magic. It simply reminds the team to examine the process from outside their own roles.`, "workplace perspective and process repair"),
  e(6, "History", "A Map around a Water Pump", `During a severe cholera outbreak in London in 1854, physician John Snow mapped deaths around Broad Street. Many cases clustered near a public water pump. Snow's investigation, together with local knowledge gathered by clergyman Henry Whitehead, supported the argument that contaminated water spread the disease. Officials removed the pump handle, although the outbreak was already declining and the action alone did not prove the theory. Snow's map was not an instant victory over all opposition. Its lasting importance comes from combining place, observation, interviews, and a testable explanation at a time when many people blamed unhealthy air.`, "John Snow and the Broad Street cholera investigation"),
  e(6, "Science", "How DNA Keeps a Copy", `DNA stores biological information in sequences of four chemical bases. In the familiar double helix, adenine pairs with thymine, while cytosine pairs with guanine. Before a cell divides, the two strands separate. Each old strand can guide the construction of a new partner through these pairing rules. The result is described as semiconservative replication because each new DNA molecule contains one strand from the earlier molecule and one newly made strand. Enzymes carry out and check the process, but copying is not perfectly error-free. Some changes are repaired; others remain as mutations. The simple pairing principle is essential, yet the full system depends on coordinated molecular machinery.`, "DNA base pairing and replication"),
  e(6, "Famous books", "The Traveler Sees Two Futures", `A scientist known only as the Time Traveller demonstrates a machine to skeptical dinner guests. He later returns exhausted and tells them that he journeyed far into Earth's future. There he met the gentle Eloi, who live above ground, and the Morlocks, who work below it. At first he mistakes one group for carefree heirs and the other for simple monsters. Gradually he sees that their divided world may have grown from inequalities in his own society. After escaping, he travels even farther forward and witnesses a dying Earth. He departs once more with flowers from the future as his only evidence, then never returns to explain where he went.`, "class division and deep time", "The Time Machine"),
  e(6, "Mystery and adventure", "The Ledger That Lost a Line", `Each evening, one line disappears from the harbor master's paper ledger. The missing entries concern different boats, so theft seems unlikely. Investigator Sora compares the book with its digital copy and finds that every lost line was written at low tide. She visits the office then and notices sunlight reflected from the water onto the desk. A clear plastic cover acts like a weak lens, heating a narrow strip where erasable ink was used. The mystery reveals two problems rather than a clever criminal: unsuitable pens and records stored in direct light. Sora recovers the entries from radio logs and recommends permanent ink, shaded storage, and routine comparison with arrival data.`, "vanishing records and physical evidence"),
  e(6, "Travel and culture", "The Word Missing from the Menu", `In the imaginary port of Daru, restaurants list fish by local names that visitor Mina cannot translate. She points to a picture and assumes the price includes the whole meal. The server pauses, then brings a small board showing portion size, side dishes, and common food allergies. Mina learns that the missing word describes a shared plate rather than one person's serving. She invites two travelers at the next table to join her. The misunderstanding becomes a generous dinner, but it also prompts the restaurant to revise its translated menu. Hospitality, Mina realizes, is not the absence of confusion; it is the patience to repair confusion without making anyone feel foolish.`, "an imaginary port and menu translation"),
  e(6, "People and biography", "Tomas Keeps the Failed Repairs", `Tomas is a fictional bicycle mechanic who opens a monthly repair table outside a community center. At first he displays only successful fixes. Visitors begin to assume that every damaged bicycle can be restored in minutes, and some feel ashamed when their own repair is difficult. Tomas creates a second table for cracked frames, missing parts, and attempts that did not work. He explains why certain bicycles are unsafe to ride and helps owners recover usable lights, baskets, and bells. The honest display makes the event less dramatic but more trustworthy. It also helps volunteers learn when to stop, ask for expert help, or recommend replacement rather than promise a repair they cannot make safely.`, "fictional repair education and safety"),

  // Level 7
  e(7, "Fantasy/stories", "The Bridge That Remembered Weight", `The oldest bridge in Veyra remembered everyone who crossed it. Heavy steps left dark marks; dancing feet made pale circles. When officials planned to replace the worn boards, the bridge showed them generations of traffic: market carts, funeral lines, fleeing families, and children returning after war. Some citizens demanded that every marked plank be preserved. Others needed a safer route immediately. Engineer Lale proposed a compromise. The strongest old boards would line a pedestrian path, while a new structure carried vehicles. One damaged plank went to the town archive with testimony from people who recognized its marks. The bridge lost part of its magical record, but memory ceased to be an excuse for danger. It became evidence that guided a living choice.`, "public memory and safe change"),
  e(7, "Nature and animals", "Elephants beyond Human Hearing", `Elephants communicate with calls that include very low frequencies. Some components fall below the usual lower limit of human hearing and can travel over substantial distances under favorable conditions. Researchers study these rumbles with microphones, behavioral observations, and measurements of ground vibration. A call does not carry a fixed message like a written sentence; its meaning depends on context, the caller, and the responses of other elephants. Families may use vocal contact while separated, and individuals can distinguish certain callers. Claims about exact range must be treated cautiously because wind, temperature, terrain, vegetation, and background noise all affect transmission. The science is powerful precisely because it joins instruments with long observation rather than translating every sound into a human phrase.`, "elephant low-frequency communication"),
  e(7, "World affairs", "A Budget Written in Plain Language", `This fictional province publishes a thousand-page annual budget that almost no resident can interpret. A new administration promises transparency by placing the document online, but disability groups, local journalists, and rural councils argue that access to a file is not the same as access to meaning. The finance office produces a plain-language summary, machine-readable tables, audio explanations, and notes showing where estimates remain uncertain. It also preserves the full accounts so simplification cannot hide inconvenient detail. When an error is found in a chart, the office corrects it publicly and retains a revision history. Trust does not rise immediately. Still, questions at public meetings become more specific, and officials can no longer dismiss disagreement as mere confusion.`, "fictional accessible public budgeting"),
  e(7, "Everyday life", "The Favor That Became a Schedule", `After Ken's mother injures her ankle, relatives repeatedly say, “Call if you need anything.” She rarely calls because each request feels like a new negotiation. Ken creates a shared schedule for meals, transport, and short visits, but his first version assigns tasks without asking. One cousin cannot drive at night; another is caring for a child. They rebuild the plan around firm offers rather than vague goodwill. Ken also asks his mother which help she wants and which tasks she prefers to keep. The schedule does not eliminate fatigue or family tension. It does, however, turn care from a performance of concern into visible, limited commitments that people can accept, decline, and revise.`, "family care and sustainable coordination"),
  e(7, "History", "Rails Meeting at Promontory", `In May 1869, tracks of the Union Pacific and Central Pacific railroads met at Promontory Summit in Utah Territory. The event marked completion of the first transcontinental railroad connection across the United States, though travelers still used other rail and ferry links and the network continued to change. The project depended heavily on Chinese workers in the west and immigrant labor in the east, alongside many other workers whose risks were often minimized in celebration. Rail travel accelerated migration, commerce, and communication. It also intensified the seizure of Indigenous lands, disrupted bison herds, and extended federal and corporate power. The famous ceremonial photograph therefore records both an engineering achievement and a transformation whose benefits and harms were distributed unequally.`, "the first U.S. transcontinental railroad"),
  e(7, "Science", "What Immune Memory Remembers", `Vaccination presents the immune system with an antigen, or instructions that allow the body to produce one, without requiring the full danger of the targeted disease. The initial response activates specialized cells and can leave memory B cells, memory T cells, and longer-lived antibody-producing cells. If the pathogen appears later, these components may respond faster or more effectively. Protection is not an on-off shield: its strength and duration vary with the vaccine, pathogen, person, and outcome being measured. Some vaccines mainly reduce severe disease rather than preventing every infection. Boosters can refresh or broaden protection when evidence supports them. Describing vaccination as immune training is useful, provided the metaphor does not hide this biological variation.`, "vaccination and immune memory"),
  e(7, "Famous books", "Hester Refuses to Disappear", `In Puritan Boston, Hester Prynne is condemned for adultery and forced to wear a scarlet letter A. She raises her daughter Pearl while refusing to name the child's father. The respected minister Arthur Dimmesdale carries the hidden guilt, and Hester's estranged husband, Roger Chillingworth, devotes himself to exposing and tormenting him. Over the years, Hester's skill and service complicate the community's judgment of the letter. Dimmesdale finally acknowledges his connection to Hester and Pearl before dying. Chillingworth, deprived of revenge, soon dies as well. Hester later returns and continues wearing the symbol by choice, transforming without fully escaping the meaning imposed upon her.`, "shame, secrecy, and public judgment", "The Scarlet Letter"),
  e(7, "Mystery and adventure", "The Tunnel Drawn after the Fire", `A fire inspection uncovers a wall map showing a tunnel beneath the concert hall. No modern plan includes it, and the city fears an unknown exit could compromise security. Archivist Dev follows construction invoices rather than the dramatic map. He learns that the line represented a proposed heating duct that was never funded. Yet one invoice lists bricks delivered below street level. Ground radar reveals not a passage, but a sealed coal room connected to an old chute. The distinction matters: opening the space requires ventilation and structural review, not a police search for a hidden route. The map told a possible future; the receipts and physical survey revealed what builders actually completed.`, "plans, records, and a hidden room"),
  e(7, "Travel and culture", "A Quiet Morning in Orsa", `Orsa is an imaginary city known for a dawn music walk. Visitors expect a parade, but residents gather in small groups and stop at courtyards where one musician plays without amplification. Traveler Hana films the first performance until a guide explains that some households open their gates only on the condition that no recording occurs. She puts away her phone and begins noticing softer details: a kettle behind a window, pigeons lifting at the final note, and neighbors using hand signs to guide late arrivals. The walk leaves almost no shareable evidence. That absence becomes part of its value, reminding Hana that cultural participation can ask for attention without demanding possession.`, "an imaginary no-recording music walk"),
  e(7, "People and biography", "Imani Redesigns the Form", `Imani is a fictional benefits officer who processes housing support applications. She notices that many rejected forms come from applicants who qualify but misunderstand one question about household income. Her supervisor suggests adding a warning in red. Imani instead observes people completing the form, consults legal staff, and invites community advisers to rewrite the section in plain language. A pilot version separates wages, irregular work, and support from relatives, while explaining why each item is requested. Error rates fall, but one group still struggles with online identity checks. Imani reports that unresolved barrier rather than presenting the redesign as complete. Her work treats administrative clarity as part of the service, not a courtesy added after policy is decided.`, "fictional plain-language public service design"),

  // Level 8
  e(8, "Fantasy/stories", "The City That Taxed Prophecies", `After a run of accurate prophecies, the city of Merrow licenses anyone who claims to see the future. Officials argue that predictions influence markets and elections, so prophets should carry responsibility for the consequences. The law produces an unexpected industry: wealthy clients buy private forecasts, while poor neighborhoods receive only public warnings stripped of detail. Eda, a civil servant with no prophetic gift, audits the system. She finds that failed predictions quietly disappear and vague ones are counted as successes. Rather than banning prophecy, she requires every forecast to be registered before the event, stated in testable terms, and reviewed with its uncertainty visible. Accuracy falls sharply once memory can no longer edit the record. Citizens are disappointed, but they begin making plans that remain useful across several possible futures.`, "prediction, accountability, and uncertainty"),
  e(8, "Nature and animals", "When Coral Loses Its Color", `Reef-building corals live in partnership with microscopic algae that provide much of their energy through photosynthesis. Under stress, especially unusually warm water, corals may expel these algae or lose their pigments. The pale tissue then reveals the white skeleton beneath, creating the appearance called bleaching. A bleached coral is not necessarily dead, and it may recover if stressful conditions ease. Prolonged or severe bleaching, however, raises the risk of disease, reduced growth, and death. Local pressures such as pollution and destructive fishing can weaken reefs, while global ocean warming increases the frequency of mass heat stress. Restoration projects can help particular sites, but they do not substitute for addressing the conditions driving widespread bleaching.`, "coral bleaching and heat stress"),
  e(8, "World affairs", "The Food Report That Included Waste", `This fictional national food plan celebrates rising agricultural output while omitting what happens after harvest. Municipalities point to spoiled produce in markets; households report confusing date labels; charities warn that surplus donation cannot replace reliable income and access to food. The government creates a measurement framework that distinguishes loss during production and transport from waste in shops, restaurants, and homes. It funds cold storage in some regions, tests smaller retail portions, clarifies labels, and requires large institutions to publish prevention plans. Redistribution remains useful for edible surplus, but prevention comes first. The plan also tracks labor, energy, and packaging so a lower weight of discarded food does not conceal other harms.`, "fictional national food-loss strategy"),
  e(8, "Everyday life", "A Promotion with Two Prices", `When Luis is offered a senior role, the salary increase looks decisive. The job also brings evening calls, a longer commute, and responsibility for dismissing staff during a planned restructure. His partner asks him to calculate not only income but time, uncertainty, and the work he wants to become good at. Luis speaks with the previous manager and learns that some duties can be shared, while others are fixed. He negotiates one remote day and clearer authority over hiring, but the company will not change the travel requirement. Accepting the promotion remains a trade-off rather than a victory. Luis chooses it for two years and schedules a review, turning an identity-defining decision into a commitment with boundaries.`, "career decisions and hidden costs"),
  e(8, "History", "Petitions before the Nineteenth Amendment", `The Nineteenth Amendment, ratified in 1920, prohibited denying United States citizens the vote on account of sex. It followed decades of organizing through petitions, conventions, state campaigns, court arguments, journalism, civil disobedience, and competing political strategies. The amendment did not make voting equally accessible to all women. Discriminatory laws, violence, citizenship restrictions, and administrative barriers continued to exclude many Black, Indigenous, Asian American, and other women. Some activists who advanced women's suffrage also supported racist positions or accepted exclusionary compromises. Remembering the amendment as both a major constitutional change and an incomplete victory makes the history more accurate than a single triumphant date.`, "U.S. women's suffrage and the Nineteenth Amendment"),
  e(8, "Science", "The Atmosphere's Useful Blanket", `Earth absorbs energy from sunlight and emits energy back toward space as infrared radiation. Greenhouse gases, including water vapor, carbon dioxide, methane, and nitrous oxide, absorb and re-emit some infrared radiation. This natural greenhouse effect keeps Earth's surface much warmer than it would otherwise be. Human activities have increased the concentration of several long-lived greenhouse gases, strengthening the effect and altering the planet's energy balance. Calling the atmosphere a blanket can help introduce the idea, but the atmosphere does not trap a fixed layer of heat like cloth. Energy continues to move through radiation, convection, evaporation, and circulation. Climate change emerges from shifts in that dynamic balance, amplified or moderated by feedbacks.`, "greenhouse gases and Earth's energy balance"),
  e(8, "Famous books", "Dorian Bargains with His Portrait", `Basil Hallward paints an unusually beautiful portrait of Dorian Gray. Influenced by Lord Henry Wotton's praise of youth and sensation, Dorian wishes that the portrait would age while he remains young. The wish appears to come true: his face stays unchanged as the image records cruelty, corruption, and time. Dorian hides the painting and increasingly treats other people as material for his desires. When Basil confronts him, Dorian murders the artist. Years later, hoping to destroy the evidence and perhaps his conscience, he stabs the portrait. Servants find an aged, ruined man on the floor and the painting restored to its original beauty.`, "beauty, influence, and moral evasion", "The Picture of Dorian Gray"),
  e(8, "Mystery and adventure", "The Election Box with Extra Weight", `A neighborhood association discovers that one sealed ballot box weighs more than the others. Accusations spread before counting begins. Auditor Keiko photographs the seals, records who handled each box, and weighs unused materials. The heavy box came from a building where voters received thick accessibility guides in several formats. Staff placed completed request slips in the same container, following an ambiguous instruction. The ballots themselves match the voter register, but the chain of custody has been weakened. Keiko separates and documents the materials in view of observers, then recommends identical packing lists and dedicated containers. The investigation finds no manufactured votes, yet it refuses the comforting conclusion that procedure did not matter.`, "election procedure and chain of custody"),
  e(8, "Travel and culture", "Winter Rooms of Talven", `Talven is an imaginary northern town where families once moved into shared winter houses during the darkest months. Modern heating ended the practical need, but residents now open community rooms for evening meals, repairs, and storytelling. Researcher Amara arrives expecting a preserved tradition. She instead finds debates: some residents want formal costumes for visitors, while others reject turning ordinary cooperation into a performance. Amara attends a repair night without recording interviews and later asks who wishes to be quoted. Her article describes the disagreement rather than inventing a unified local voice. The town's culture appears not as a fixed inheritance, but as an argument about which parts of the past should serve the present.`, "an imaginary town negotiating tradition"),
  e(8, "People and biography", "Elias Publishes the Null Result", `Elias is a fictional education researcher testing whether a new reading app improves comprehension. The first analysis shows a small benefit, but it disappears when he applies the method specified before data collection. A sponsor suggests highlighting the favorable comparison as exploratory. Elias agrees to report it only if the distinction is unmistakable. He publishes the planned analysis, confidence intervals, missing-data limits, and the exploratory finding together. The result does not prove that the app is useless; the study may be too small or the intervention too brief. It does show that the promised effect was not established. By treating an uncertain result as information rather than embarrassment, Elias gives future researchers a clearer basis for designing the next trial.`, "fictional research transparency"),

  // Level 9
  e(9, "Fantasy/stories", "The Court of Reversible Decisions", `In Aven, every public decision must survive one night in a court where time can be reversed. The rule was designed to expose unintended harm: if a bridge displaced a market or a tax closed a workshop, judges could restore yesterday and demand another plan. Over time, officials became addicted to reversibility. They postponed hospitals, homes, and flood barriers because no design was free of loss. Mara, the court's youngest clerk, notices that reversal itself has consequences. People remember erased futures as dreams and begin distrusting commitments. She proposes a harder standard: reverse decisions made without evidence, consent, or a repair process, but allow accountable experiments with defined limits. The court loses its promise of perfect safety. In exchange, the city learns to distinguish caution from paralysis and correction from pretending that nothing happened.`, "reversibility, governance, and accountable experiments"),
  e(9, "Nature and animals", "Peat Built by Incomplete Decay", `Peatlands form where waterlogged conditions slow the decomposition of plant material, allowing partially decayed organic matter to accumulate. Although they occupy a modest share of Earth's land surface, peatlands store a disproportionately large amount of soil carbon. Drainage exposes peat to oxygen, accelerating decomposition and releasing carbon dioxide; dry peat can also burn. Rewetting damaged sites can reduce some emissions and restore peat-forming conditions, but outcomes depend on hydrology, vegetation, land use, and the rights of people who live there. Methane may rise after rewetting even as long-term carbon losses fall, so a single short-term measure can mislead. Protecting intact peatlands usually avoids damage more reliably than attempting to reconstruct their slow ecological history.`, "peatland formation, carbon, and restoration"),
  e(9, "World affairs", "The Heat Map with Missing Homes", `This fictional metropolis directs cooling funds toward districts that appear hottest in satellite images. Tenant unions object that the map overlooks indoor heat, night-shift workers, informal housing, and people who cannot afford electricity. The city combines surface-temperature data with building surveys, health-service reports, tree cover, energy insecurity, and resident testimony. Officials publish the weighting choices and test how rankings change when assumptions shift. Some affluent commercial zones remain physically hot, yet neighborhoods with older housing and fewer coping options rise in priority. The revised index is still a model, not a neutral photograph of need. By exposing uncertainty and allowing challenges, the program turns mapping from a final answer into a structured public argument about vulnerability and resources.`, "fictional urban heat vulnerability policy"),
  e(9, "Everyday life", "Inheritance in Twelve Boxes", `After their father dies, three siblings inherit twelve boxes of tools, letters, photographs, and unfinished projects. Monetary value is the simplest question; emotional ownership proves harder. One sister wants to preserve every note, one brother wants an immediate sale, and the youngest quietly removes objects connected to painful memories. They pause the division and create three categories: items anyone may claim, items that require a shared decision, and materials to digitize before release. Each sibling receives a veto over public sharing of private letters, but not unlimited power to delay everything. The process cannot make grief equal or orderly. It does make the rules visible enough that disagreement concerns choices rather than suspicions about what vanished.`, "family memory, grief, and fair process"),
  e(9, "History", "Earthrise from Apollo 8", `In December 1968, Apollo 8 carried Frank Borman, James Lovell, and William Anders around the Moon, the first crewed mission to do so. During lunar orbit, the astronauts saw Earth rising above the Moon's horizon and photographed it. Anders took the color image later known as “Earthrise,” while the crew had already noticed and photographed the scene in black and white. The picture was not the first image of Earth from the vicinity of the Moon, but its human viewpoint, timing, and wide circulation gave it unusual cultural force. It presented a vivid planet above a barren foreground and became associated with environmental awareness, even though no single photograph created that movement.`, "Apollo 8 and the Earthrise photograph"),
  e(9, "Science", "A Result Needs Its Uncertainty", `A measurement without an account of uncertainty can suggest more knowledge than an experiment provides. Uncertainty does not mean that the result is a guess or a mistake. It expresses the range and quality of values reasonably associated with what was measured, given the method, calibration, sampling, environment, and model. Repeating a measurement helps reveal random variation, but repetition alone does not remove a systematic bias. Likewise, reporting many decimal places cannot create precision that the process lacks. Scientists may combine uncertainty components and state a coverage interval under explicit assumptions. Readers should then ask what quantity was measured, how the interval was constructed, and whether important sources of uncertainty were omitted.`, "measurement uncertainty and scientific reporting"),
  e(9, "Famous books", "Dorothea Revises Her Idea of a Great Life", `Dorothea Brooke enters marriage hoping to assist the scholar Edward Casaubon in important work. She gradually discovers that his project is sterile and his emotional authority restrictive. Her sympathy for Will Ladislaw deepens, yet Casaubon's will attempts to control her even after his death. Around her, the ambitious doctor Tertius Lydgate finds his medical ideals compromised by debt, marriage, and the politics of Middlemarch. The novel refuses to separate private motives from social networks: generosity may carry vanity, reform may depend on money, and respectable opinion can distort judgment. Dorothea eventually chooses Will and a less publicly grand life. The ending locates moral consequence in countless effects on others rather than celebrated achievement.`, "idealism, marriage, and social interdependence", "Middlemarch"),
  e(9, "Mystery and adventure", "The Voice in the Flood Archive", `After a flood damages a municipal archive, conservators hear a faint recorded voice whenever one particular box is moved. Rumors suggest a hidden testimony. Investigator Noor first stabilizes the wet documents, refusing to open them for the sake of drama. An audio engineer traces the sound to a damaged greeting card lodged beneath the box; pressure completes its circuit. Yet the card leads to a family name absent from the catalog. Cross-referencing donation forms reveals that two collections were mixed during emergency evacuation. The voice contains no secret confession, but it exposes a break in provenance that could corrupt future research. Noor's solution is therefore procedural: separate the records, document uncertainty, and preserve the accidental clue that revealed the error.`, "archival provenance after a disaster"),
  e(9, "Travel and culture", "Three Voices beside Each Object", `In the imaginary island capital of Enna, a new museum displays navigation tools collected during colonial rule. Its first labels describe only materials, dates, and foreign collectors. Local sailors argue that the objects are being treated as dead technology; descendants of makers question whether some should be displayed at all. Curator Sol invites three forms of interpretation: archival records, community accounts, and notes about unresolved ownership. Visitor Celia initially finds the labels confusing because they do not produce one authoritative story. By the final room, she understands that the disagreement is itself evidence. The museum has not surrendered accuracy. It has become more precise about which facts are documented, which meanings are living, and who has the standing to decide access.`, "an imaginary museum and contested heritage"),
  e(9, "People and biography", "Juno Audits the Helpful Algorithm", `Juno is a fictional data scientist reviewing a system that directs housing inspections. The model appears efficient because it finds more violations than random selection. She asks a different question: which neighborhoods have enough historical reports to become visible to the model? Areas with active complaint networks receive repeated inspections, while poorly connected tenants disappear from the data. Juno tests outcomes by building age, landlord history, language access, and prior enforcement, then documents where proxy variables reproduce earlier patterns. She does not claim that removing one feature creates fairness. The agency adds random audits, tenant outreach, an appeal route, and regular comparison between model predictions and observed hazards. Efficiency becomes one criterion within an accountable process rather than a license for automated certainty.`, "fictional algorithmic accountability in housing"),

  // Level 10
  e(10, "Fantasy/stories", "The Ministry of Almost Certain Things", `The Ministry never predicted what would happen; it certified what was almost certain. Merchants delayed voyages when storms received a red seal, courts released defendants when guilt fell below an approved percentage, and couples requested forecasts before marrying. The system reduced some avoidable disasters, then quietly redefined uncertainty as disobedience. Analyst Senn discovered that each department used a different threshold while displaying the same seal. Worse, consequences were absent from the calculation: a modest chance of catastrophic flooding appeared safer than a high chance of a minor delay. Senn leaked the tables, expecting the Ministry to collapse. Instead, citizens demanded richer forecasts, documented assumptions, and named officials responsible for acting on them. The new reports were harder to read and impossible to worship. Almost certainty survived, diminished from an oracle into a tool whose value depended on the decisions surrounding it.`, "uncertainty, institutions, and public judgment"),
  e(10, "Nature and animals", "Wolves, Elk, and the Limits of a Cascade", `The return of gray wolves to Yellowstone in the 1990s renewed interest in trophic cascades: ecological effects that move across levels of a food web. Wolves kill elk and alter the risks elk face, while carcasses feed scavengers. Changes in browsing can affect willow or aspen in some places, which may influence beavers and streamside habitat. The popular version presents a simple chain in which wolves transformed rivers. Research supports important cascading effects but also identifies other drivers, including elk numbers, hunting outside the park, climate, water availability, topography, and the behavior of other predators. Effects vary across sites and decades. Yellowstone is therefore not proof that one species mechanically controls an ecosystem; it is a case study in how predation interacts with history and landscape.`, "Yellowstone wolves and trophic cascades"),
  e(10, "World affairs", "A Debt Test for the Sea Wall", `This fictional island government receives competing offers to finance a sea wall. The cheapest loan assumes uninterrupted port revenue for thirty years; a climate-linked bond delays payments after severe storms but uses a trigger based on a narrow wind-speed index. Economists model cash flow, while coastal residents ask who will be protected and whose shoreline will be sacrificed. The cabinet publishes scenarios for construction overruns, displaced erosion, maintenance failure, currency shocks, and storms that cause damage without activating the bond clause. It also compares smaller barriers, restored wetlands, relocation support, and staged investment. No option eliminates risk. By treating financing terms, ecological effects, and distributional choices as one decision, the government avoids presenting concrete as adaptation and debt as a neutral source of money.`, "fictional climate adaptation finance"),
  e(10, "Everyday life", "The Friendship Maintenance Window", `Mara and Leon have been friends for twenty years, yet their conversations increasingly consist of apologies for delayed replies. Mara proposes a monthly call, converting affection into a calendar item. Leon resists because scheduled intimacy feels administrative. Their disagreement reveals different fears: she worries that unplanned contact will disappear; he worries that obligation will replace desire. They test a “maintenance window” with permission to cancel without explanation and an agreement that urgent needs require a direct request. The arrangement produces neither perfect spontaneity nor equal effort. It does, however, make expectations discussable. When they eventually miss two months, the lapse no longer serves as evidence that the friendship has failed. It becomes information that the current design needs revision, much like any other shared practice.`, "long friendship and explicit expectations"),
  e(10, "History", "A Continent Reserved for Peace and Science", `The Antarctic Treaty was signed in 1959 and entered into force in 1961. It established that Antarctica would be used for peaceful purposes, guaranteed freedom of scientific investigation, promoted exchange of research information, and prohibited nuclear explosions and disposal of radioactive waste. It also set aside disputes over territorial claims without resolving them. The treaty did not freeze Antarctic governance permanently; later agreements, including the Environmental Protocol, expanded the system. Nor does scientific cooperation erase geopolitical interest, unequal access, tourism pressure, fishing disputes, or the global causes of climate change. The treaty's durability lies partly in its carefully bounded compromises, but evaluating it requires attention to who participates, what remains outside its scope, and how institutions respond to conditions their founders did not anticipate.`, "the Antarctic Treaty system"),
  e(10, "Science", "CRISPR as a Guided Molecular Tool", `CRISPR genome editing adapts components of microbial defense systems. In a common laboratory design, a guide RNA directs a Cas enzyme toward a DNA sequence that matches the guide and lies beside a required recognition motif. The enzyme cuts the DNA, after which cellular repair processes produce the eventual edit. Repair may disrupt a gene, insert supplied material, or create unintended changes at the target or elsewhere. Newer approaches can alter bases or regulate genes without making the same kind of double-strand cut, but they introduce their own constraints. Accuracy depends on molecular design, cell type, delivery, detection methods, and the biological question. CRISPR is therefore a versatile platform rather than a perfect pair of genetic scissors, and clinical use demands evidence about benefit, off-target effects, durability, consent, and equity.`, "CRISPR mechanisms and limits"),
  e(10, "Famous books", "The Karamazov Brothers Face a Father's Death", `Fyodor Pavlovich Karamazov is a neglectful, corrupt father whose sons embody conflicting temperaments. Dmitri quarrels with him over money and desire; Ivan subjects faith and morality to relentless intellectual challenge; Alyosha seeks compassionate action under the influence of the elder Zosima. Their possible half-brother Smerdyakov lives within the household's contempt and ambiguity. When Fyodor is murdered, circumstantial evidence and Dmitri's own threats make him the accused, although Smerdyakov tells Ivan that he committed the act. Ivan must confront the relationship between ideas, wishes, and responsibility, while Dmitri faces conviction. The novel refuses a tidy distribution of innocence and guilt, setting legal judgment beside spiritual rebellion, family cruelty, freedom, and the possibility of love enacted without certainty.`, "guilt, freedom, faith, and family", "The Brothers Karamazov"),
  e(10, "Mystery and adventure", "The Observatory's Impossible Transit", `An automated observatory records a dark object crossing a star at exactly the same local time for six nights. The regularity suggests an orbit, but no plausible body should match the pattern as the observing schedule shifts. Astronomer Vale preserves the raw files before changing the instrument. She compares detectors, dome position, temperature, and maintenance logs, then asks whether the event follows the sky or the building. The signal appears only when a ventilation louver opens; a cable casts a narrow moving shadow across the flat-field screen used for calibration. The pipeline transformed that defect into an apparent stellar transit. The episode does not discredit automation. It demonstrates why discovery claims require independent observations, alternate instruments, and tests designed to make an attractive explanation fail.`, "instrumental error in an astronomy mystery"),
  e(10, "Travel and culture", "The Return Ticket to Varos", `Varos is an imaginary city rebuilt after a long civil conflict. Diaspora visitor Nela arrives with childhood stories inherited from her parents, only to find renamed streets, new residents, and memorials that emphasize one community's suffering. A guide offers a heritage route designed for returning families, but Nela leaves it to meet an archivist collecting contradictory maps and oral histories. She recognizes her grandmother's house in one account and another family's loss in the same building. The discovery does not invalidate her belonging; it makes exclusive belonging harder to claim. Before leaving, Nela donates copies of family photographs with restrictions on public use. Her return becomes neither sentimental recovery nor exposure of a false past, but an encounter with several legitimate memories competing for space.`, "an imaginary post-conflict return journey"),
  e(10, "People and biography", "Mei Designs the Exit before the Pilot", `Mei is a fictional public-interest technologist leading a digital identity pilot. Most project plans describe enrollment and scale; she begins with refusal, error, and withdrawal. Residents must be able to access essential services through a non-digital route, challenge a false match, learn which agency viewed their data, and leave the pilot without losing benefits. Contractors call these requirements obstacles to innovation. Mei treats them as evidence that the system carries public power. During testing, the tool speeds verification for many users but repeatedly fails people whose records contain transliteration differences. She pauses expansion, funds correction of source data, and publishes the error pattern. The pilot's success is measured not only by average speed, but by whether the people most burdened by failure can obtain remedy without extraordinary persistence.`, "fictional rights-respecting digital identity design"),
];

const storyEdits = {
  "The Pocket Cloud": {
    text: `A child finds a cloud in a coat. It is small and soft. The cloud needs water, so the child gives it a drink. Rain falls into a blue cup. The cloud gets big. The child opens the window. Up it goes to the wide sky.`,
  },
  "A School Table for All": {
    text: `This story is not real. A school has no room for lunch. Some kids bring food, but some do not. Homes, cooks, and teachers make a plan. The town pays some of the cost. A farm gives fresh food. Soon all the kids can eat before class.`,
  },
  "The Last Clean Spoon": {
    text: `A boy wants soup, but he has no clean tool to eat it with. He starts to wash just one. Then he sees the full sink. He does all the work and puts each thing away. His sister helps with the plates. The soup is a little cold, but the room is ready for the next day.`,
  },
  "Soup at Moon Bay": {
    text: `This town is not real. A girl walks by its small boats. Rain starts, and she runs under a food tent. A cook gives her hot bean soup. The girl helps move chairs out of the rain. When the sun comes back, they eat together.`,
  },
  "Oren Fixes the Park Gate": {
    title: "A Park Worker Fixes the Gate",
    text: `This park worker is not a real person. A gate is hard to open. People with small kids ask for help. The worker oils the metal and puts the handle lower. Many people try it. The gate now opens with one hand, so more people can use the park.`,
  },
  "An Otter Holds On": {
    title: "A Duck Stays Dry",
    subtopic: "duck feathers and water",
    text: `A duck has many feathers. It uses its bill to put oil on them. The outer feathers help keep water away from the skin. Air under the feathers also helps the duck stay warm. The duck still needs clean water and time to care for its body.`,
  },
  "Water at the Bus Stop": {
    text: `This town is not real. Its hot days make bus stops hard to use. The town cannot build a big roof at every stop. People mark the stops used most on a map. Workers add shade and water there first. They plant trees where the roots will not block the path.`,
  },
  "The Quiet Phone Basket": {
    text: `A family keeps looking at phones during dinner. The youngest boy puts an empty basket on the table. All agree to leave phones there for twenty minutes. At first, the room feels too quiet. Then their father tells a funny story. The basket stays on the table the next night.`,
  },
  "Three Bells after Closing": {
    text: `A food shop is closed, but a bell rings three times inside. A girl checks the front door. It is locked. She walks around the shop and hears the sound again. A metal tool hangs near an open window. Wind moves it against a glass. She closes the window.`,
  },
  "Painted Doors in Luma": {
    title: "Painted Doors on the Hill",
    text: `This hill town is not real. Its doors have many bright colors. A guest asks why two blue doors have white circles. A woman says her family chose the sign long ago. Other homes use leaves, birds, or lines. The guest draws the doors but not the private names beside them.`,
  },
  "Sela Starts a Seed Shelf": {
    title: "A Shelf for Shared Seeds",
    text: `This library worker is not a real person. People often ask where they can share extra seeds. The worker makes one open shelf and adds small paper bags. Each bag shows the plant name and year. People take what they need and bring seeds back later. The worker checks the bags each week.`,
  },
  "The Owl's Quiet Wing": {
    title: "Warm Air under Feathers",
    subtopic: "birds, feathers, and body heat",
    text: `A bird has many feathers around its body. Air stays between them. This layer of air slows the loss of body heat. On a cold day, a bird may lift its feathers and look round. That makes the warm air layer thicker. Feathers must also stay in good shape, so birds spend time cleaning and placing them.`,
  },
  "Books Hidden in Family Chests": {
    text: `Timbuktu was a city of trade and study. Families in Timbuktu kept many old books written by hand. The books covered law, faith, words, stars, and daily work. During fighting in Mali in 2012, local teams moved many books away from danger. Some were hurt or lost, but careful work helped a great number survive.`,
  },
  "Three Ways to Make a Rock": {
    title: "Ice, Water, and Steam",
    subtopic: "changes of state in water",
    text: `Water can be solid, liquid, or gas. Ice is solid water. When ice gets enough heat, it melts into liquid water. When liquid water gets more heat, some can turn into water gas. Cooling can change the gas back into drops. Freezing can make the liquid solid again. The water is still made of the same kind of small parts.`,
  },
  "Pinocchio Wants to Be Real": {
    text: `A wood worker named Geppetto makes a boy from wood and calls him Pinocchio. The boy can walk and talk. Pinocchio wants to do well, but he often follows bad advice. He leaves school and tells lies. His poor choices also hurt Geppetto. At last, Pinocchio learns to work, help others, and tell the truth. He becomes a real boy.`,
  },
  "The Key in the Bird Feeder": {
    title: "The Key in the Seed Box",
    text: `Each Monday, a brass key appears in a box of bird seed at the park. A girl waits on a seat but sees only birds and people. Then she sees a worker fill the box from an old tin. A hole in his coat drops the key each week. It opens the tool room, not a treasure box, and she gives it back.`,
  },
  "The Long Table of Neris": {
    title: "The Long Table in Autumn",
    text: `This farm town is not real. On the first cold night of fall, each family brings food to one long table. A guest thinks he must bring a costly dish. His host asks him to cut apples instead. During the meal, he learns that help with the work matters more than a perfect gift.`,
  },
  "Votes for a Small Park": {
    text: `This story is about a made-up city. One area gets a small amount of public money. People may offer ideas and vote, but at first only those with free nights come to meetings. The city adds a weekend meeting, child care, clear forms, and paper votes at the library. A play area with shade wins. The city shares the vote count and final cost. More people can now help make the choice.`,
  },
  "Ink, Metal, and Many Pages": {
    text: `People in East Asia printed with type that could be moved before Gutenberg worked in Europe. In the 1400s, Gutenberg and his team used metal type, oil ink, a press, and careful hand work to make books. The method did not make books cheap at once. It did help a shop make many clear copies faster than writing a whole book by hand. Books then moved through trade, schools, churches, and state offices.`,
  },
  "Leaves Build Sugar": {
    title: "Why a Metal Spoon Feels Cold",
    subtopic: "heat transfer through materials",
    text: `A metal spoon and a wood spoon sit in the same room. Both may be at the same temperature. Yet the metal one can feel colder. Metal moves heat away from a warm hand faster than wood does. The hand senses that quick loss of heat. If both spoons sit in hot water, the metal one can also carry heat to the hand faster. The material changes the speed of heat flow, not the room temperature.`,
  },
  "Rafi Tests the Quiet Crossing": {
    title: "A Better Street Signal",
    text: `This street worker is not a real person. He cannot hear well. Street signals near his home use only sound, so he asks other people what would help. The team tests a signal that also shakes and shows a bright light. Rain makes the first form hard to use. They change the cover and timing. The worker's best idea is simple: people who use a system should help test it.`,
  },
  "The Tailor of Borrowed Courage": {
    text: `In a narrow shop, a tailor puts courage inside coats. The courage must come from someone who wants to share it. A young man asks for enough to speak before the city council. He receives one thread from a nurse and one from a child learning to swim. During the speech, the gift lasts for only a minute. The young man keeps talking even as his voice shakes. When he returns the coat, a new thread lies inside. It is his own courage, ready to be shared.`,
  },
  "A Butterfly across Generations": {
    text: `Monarch butterflies in eastern North America make a long trip each year. One butterfly does not finish the whole yearly path. Several groups move north and lay eggs during spring and summer. A later group flies much farther south to central Mexico for winter. In spring, those butterflies start back, and their young continue the trip. The path is part of their natural behavior, but weather and places to feed also matter. Loss of milkweed, where young monarchs eat and grow, can make the journey harder.`,
  },
  "Toad Learns Too Slowly": {
    text: `Mole leaves his spring cleaning and finds the river with Rat. Their friend Badger likes a quiet life, while Toad always wants a new thrill. Toad becomes wild about fast cars, drives badly, takes a car, and lands in prison. He gets out in a false dress and learns that enemies have taken his home. His friends help him win it back. Toad says he will change, and for a while he acts with care. The story enjoys his energy while showing how often friendship must save him from his pride.`,
  },
  "Lessons in the Temporary Hall": {
    text: `This made-up country receives families who fled a nearby war. Local schools are already full, so officials first suggest separate tents and short lessons. Parents fear that this quick answer will last for years. The area turns a public hall into shared class rooms and adds teachers. It accepts old school records when they can be found and offers help with language. Travel is still hard, and some children have missed much school. Each month, families and teachers report what blocks attendance, learning, and safety.`,
  },
  "How DNA Keeps a Copy": {
    text: `DNA holds biological information in a long chain built from four chemical bases. The bases match in two fixed pairs. Before a cell makes a new copy, the two sides of the chain open. Each old side then acts as a guide for a new partner. Each new DNA unit keeps one old side and gains one new side. Proteins carry out and check the work, but copies are not always perfect. Some changes are fixed; others remain. The matching rule is simple, while the full process requires many parts working together.`,
  },
  "Hester Refuses to Disappear": {
    text: `Hester Prynne lives in Puritan Boston and has a child outside marriage. The town forces Hester to wear a red letter A, but Hester will not name the father. The minister Dimmesdale hides his part in the story. Hester's lost husband returns under the name Chillingworth and tries to learn the truth. He uses that knowledge to hurt Dimmesdale. Over time, Hester's work and care change how some people see her. Dimmesdale finally speaks in public before he dies. Hester later returns and wears the letter by her own choice, though she can never fully control what it means.`,
  },
  "The Atmosphere's Useful Blanket": {
    text: `Earth takes in energy from sunlight and sends energy back toward space as heat radiation. Certain gases in the air can take in and send out part of that radiation. They include water vapor, carbon dioxide, methane, and nitrous oxide. This natural greenhouse effect keeps Earth's surface warmer than it would otherwise be. Human activity has raised the amount of several long-lived greenhouse gases, adding to the warming effect. A blanket is a helpful first image, but air does not hold a fixed layer of heat like cloth. Energy keeps moving through light, air, water, and weather. Climate changes when the balance of those flows changes over time.`,
  },
  "Peat Built by Incomplete Decay": {
    text: `Peat forms where wet ground slows the breakdown of dead plants. Partly broken plant matter then builds up over long periods. Peatlands cover a small part of Earth's land but hold a very large store of soil carbon. Draining the ground lets in more oxygen, speeds decay, and releases carbon dioxide. Dry peat can also burn. Bringing water back can reduce some long-term carbon loss, but results depend on water flow, plants, land use, and local rights. Methane may rise after the land becomes wet again. One short measure can therefore give the wrong picture. Keeping healthy peatlands wet is usually safer than trying to rebuild them after major damage.`,
  },
};

for (const story of entries) {
  const edit = storyEdits[story.title];
  if (!edit) continue;
  Object.assign(story, edit);
  story.text = story.text.trim();
}

const stories = JSON.parse(fs.readFileSync(storyPath, "utf8"));
const baseStories = stories.filter((story) => {
  const match = /^s(\d+)$/.exec(String(story.id || ""));
  return match && Number(match[1]) <= 1810;
});
if (baseStories.length !== 1810) throw new Error(`Expected 1,810 reviewed base stories, found ${baseStories.length}.`);
if (entries.length !== 100) throw new Error(`Expected 100 new entries, found ${entries.length}.`);

for (let level = 1; level <= 10; level += 1) {
  for (const topic of topics) {
    const count = entries.filter((story) => story.level === level && story.topic === topic).length;
    if (count !== 1) throw new Error(`Expected one entry for Level ${level} / ${topic}, found ${count}.`);
  }
}

const existingIds = new Set(baseStories.map((story) => story.id));
const existingTitles = new Set(baseStories.map((story) => story.title));
const additions = entries.map((story, index) => {
  const id = `s${String(1811 + index).padStart(3, "0")}`;
  if (existingIds.has(id)) throw new Error(`ID already exists: ${id}`);
  if (existingTitles.has(story.title)) throw new Error(`Title already exists: ${story.title}`);
  return {
    id,
    level: story.level,
    topic: story.topic,
    title: story.title,
    text: story.text,
    wordCount: story.text.split(/\s+/).filter(Boolean).length,
    subtopic: story.subtopic,
    contentType: contentTypes[story.topic],
    editorialStatus: "published",
    factChecked: true,
    reviewedAt,
    sourceWork: story.topic === "Famous books" ? story.sourceWork : null,
    vocabularyVersion: "v2",
  };
});

fs.writeFileSync(storyPath, `${JSON.stringify([...baseStories, ...additions], null, 2)}\n`);
console.log(`Added or refreshed ${additions.length} fact-checked stories: ${additions[0].id}-${additions.at(-1).id}`);
