const fs = require("fs");
const path = require("path");

const root = path.join(__dirname, "..");
const storyPath = path.join(root, "stories.json");
const topics = [
  "Fantasy/stories",
  "Nature and animals",
  "World affairs",
  "Everyday life",
  "History",
  "Science",
  "Famous books",
  "Mystery and adventure",
  "Travel and culture",
  "People and biography",
];

const entry = (level, topic, title, text, subtopic, contentType, sourceWork = null) => ({
  level,
  topic,
  title,
  text: text.trim(),
  subtopic,
  contentType,
  sourceWork,
});

const entries = [
  // Level 1
  entry(1, "Fantasy/stories", "A Room Inside Mina's Coat", `Mina finds a small door in her coat. It has a blue key. She opens the door and sees a warm room. A mouse sits by a fire. He gives Mina a tiny cup of tea. Then the bell rings. Mina closes the door. At home, the blue key is still in her hand.`, "magical objects and transformations", "narrative-fiction"),
  entry(1, "Nature and animals", "A Crab Finds Shade", `The sun is hot on the beach. A small crab walks over the sand. It looks for a cool place. A shell is too small. A rock is too warm. Then it finds sea grass by a pool. It stays there until the water comes back. The cool pool keeps it out of the strong sun.`, "coasts and ocean life", "explanatory-nonfiction"),
  entry(1, "World affairs", "Two Streets Share a Bus", `Two streets need one small bus. People meet at the town hall. One group wants an early bus. The other wants a late bus. A driver has an idea. The bus can go early on work days and late on rest days. Both streets agree to try the plan.`, "transport and public services", "explanatory-nonfiction"),
  entry(1, "Everyday life", "Lunch for the New Student", `Ken puts rice and eggs in his lunch box. Then he sees a second box on the table. His sister is sick, so the box is not hers. Ken asks his father. The extra lunch is for a new child at school. Ken carries both boxes and meets a new friend.`, "food and home", "narrative-fiction"),
  entry(1, "History", "Marks in Wet Clay", `Long ago, people made marks in wet clay. The marks helped them count food and animals. They used a cut piece of plant as a tool. The clay became hard in the sun. Many years later, people could still read some of the old marks.`, "ancient history", "historical-narrative"),
  entry(1, "Science", "The Cup That Sweats", `Aya puts cold water in a cup. Soon, small drops sit on the outside. The cup does not have a hole. Water in the air meets the cold cup. It turns into drops. Aya wipes the cup, but new drops soon appear.`, "water, weather, and materials", "explanatory-nonfiction"),
  entry(1, "Famous books", "Peter Comes Home", `Peter goes into a garden. He eats green plants, but a man sees him. Peter runs fast. He loses his shoes and coat. At last, he gets under the gate. Peter is tired when he reaches home. His mother puts him to bed with warm tea.`, "animal tales", "classic-retelling", "The Tale of Peter Rabbit"),
  entry(1, "Mystery and adventure", "A Kitten Behind the Wall", `A bell rings in the empty house. Leo looks in every room. No one is there. The bell rings again near the stairs. Leo opens a little door. A kitten sits inside with a red bell on its neck. The mystery is over, and the kitten has a new home.`, "household mysteries", "mystery-fiction"),
  entry(1, "Travel and culture", "Breakfast at the River Stop", `Nora gets off the boat at a small river town. Shops are opening. A baker gives her warm bread with fruit. People sit outside and watch the boats. Nora cannot speak much of their language. She smiles and points to the bread. The baker smiles too.`, "food and local markets", "travel-vignette"),
  entry(1, "People and biography", "Lena Fixes Small Things", `Lena repairs lamps in a small shop. She keeps every screw in a clear box. One day, a child brings a broken toy train. Lena has never fixed a train. She looks, listens, and tries. The train moves again. After that, her shop has a new sign: Small Things Welcome.`, "craft, business, and technology", "fictional-biography"),

  // Level 2
  entry(2, "Fantasy/stories", "The Cloud Baker", `Every morning, Sami makes bread in a tower. He uses flour, water, and one piece of cloud. The bread stays soft for seven days. One windy morning, all the clouds move away. Sami cannot finish his work. He ties white cloth to the tower. Birds see it and carry small pieces of cloud to him. Sami thanks them with warm bread.`, "everyday magic", "narrative-fiction"),
  entry(2, "Nature and animals", "Why Otters Hold Hands", `Sea otters often rest on the water. Waves and wind can move them apart. Sometimes two otters hold paws while they float. A group may also rest among sea plants. The plants help keep them in one place. Holding on does not happen every time, but it can help partners stay close while they sleep. The sea is always moving. Staying close can help the group feel safe and find one another when they wake.`, "animal behavior", "explanatory-nonfiction"),
  entry(2, "World affairs", "The Library After Dark", `Workers in one town finish late. The public library closes before many of them can visit. At a town meeting, a nurse asks for one late evening each week. The library cannot pay for more hours every day. It moves some morning hours to Thursday night. After a short test, more workers and students use the library.`, "education and public services", "explanatory-nonfiction"),
  entry(2, "Everyday life", "A Quiet Table for Grandfather", `Maya has dinner with her grandfather. He cannot hear well when many people talk at once. Maya first puts him near the kitchen, but the dishes are loud. She moves a small table away from the noise. Everyone takes turns sitting with him. Now he can hear their stories, and the whole family can enjoy the meal together.`, "family and communication", "narrative-fiction"),
  entry(2, "History", "A Road Across the Andes", `The Inca built roads across high mountains in South America. People carried messages by running from one station to the next. They did not use horses or carts on these roads. Rope bridges crossed deep low land between mountains. The great road system joined farms, towns, and large rooms that held food. A runner gave each message to a new runner, so news could move far. Parts of the old roads remain today.`, "roads and exchange", "historical-narrative"),
  entry(2, "Science", "A Spoon Looks Bent", `Put a spoon in a clear glass of water. From the side, it may look bent. Light moves through air and water at different speeds. Its path changes at the surface of the water. Your eyes follow the changed light, so the spoon seems to be in a new place. It is still straight. The light, not the metal, has changed its path.`, "light and seeing", "explanatory-nonfiction"),
  entry(2, "Famous books", "The Lion and the Small Helper", `A lion finds a mouse and holds it under one paw. The mouse asks to go free and promises to help one day. The lion laughs but lets it go. Later, the lion is caught in a rope net. The mouse hears his call. It cuts the rope with its small teeth until the lion can get free. A small friend can give great help.`, "fable", "classic-retelling", "Aesop's Fables"),
  entry(2, "Mystery and adventure", "Water Marks in the School Hall", `Wet footprints cross the school hall, then stop at a wall. A girl follows them after class. There is no door or window nearby. She looks up and sees drops on a pipe. The wet shoes of a school worker made the first marks. Then he went up some high steps to fix the pipe. The last marks are on those steps.`, "school mysteries", "mystery-fiction"),
  entry(2, "Travel and culture", "The Red Thread Market", `In a mountain village, Jun visits a market full of cloth. Each family uses colors in a different way. A seller shows Jun how red thread becomes a simple band. Jun tries to copy her hands, but his first band is loose. She helps him begin again. He buys the second band, not because it is perfect, but because he made it there.`, "crafts and local markets", "travel-vignette"),
  entry(2, "People and biography", "Omar and the Talking Map", `Omar drives a bus in a busy town. New riders often miss their stops because the street signs are small. He records short stop names in three languages and asks a student to add them to a simple map. Riders can press a button to hear the next stop. Omar did not build a new bus. He made the old one easier to use.`, "transport and community service", "fictional-biography"),

  // Level 3
  entry(3, "Fantasy/stories", "Moon-Walking Beans", `Tala planted beans beside her window. Each morning, the little garden stood in a different part of the yard. First it moved near the gate. Then it appeared beside the well. Tala stayed awake to watch. At midnight, the bean plants pulled their roots from the soil and walked toward the moonlight. Tala placed silver stones along a safe path. After that, the garden still traveled, but it never stepped on her father's flowers.`, "enchanted plants and places", "narrative-fiction"),
  entry(3, "Nature and animals", "The Frog's Winter Room", `When cold weather comes, some frogs rest under mud, leaves, or logs. Their bodies become slow, so they need very little food. A frog may take in some air through its skin while it waits. It does not sleep in a warm bed, and it may not move for weeks. When the ground warms and insects return, the frog becomes active again and leaves its winter shelter.`, "seasonal survival", "explanatory-nonfiction"),
  entry(3, "World affairs", "The Empty Water Tanks", `Three villages share tanks that hold rainwater. During a dry month, the first village uses more than expected. The other villages fear that the tanks will soon be empty. Their leaders meet and compare daily use. They agree to repair two leaks, water gardens at night, and post the tank levels in public. The plan does not create rain, but it makes the remaining water last longer and helps people trust the rules.`, "environment and resources", "explanatory-nonfiction"),
  entry(3, "Everyday life", "Niko Learns to Repair", `A broken toaster sat in Niko's cupboard for a year. He did not know how to fix it, and a new one cost too much. Then a neighbor opened a repair table at the community room. People brought lamps, toys, and loose chair legs. A volunteer showed Niko how to replace a damaged wire safely. The toaster worked again. Niko returned the next Saturday to help sort screws and tools for other visitors.`, "repair and community", "narrative-fiction"),
  entry(3, "History", "Messages on the Silk Roads", `The Silk Roads were not one single road. They were many land and sea routes that linked parts of Asia, Africa, and Europe. Traders often carried goods for only one part of the journey. Silk, glass, spices, stories, and ideas passed from person to person. Travel was slow and sometimes dangerous. Yet these routes helped distant communities learn about one another long before trains or planes existed.`, "trade and cultural exchange", "historical-narrative"),
  entry(3, "Science", "How Soap Moves Grease", `Water alone does not easily carry away oil. Soap helps because each soap particle has two different ends. One end is drawn to water, while the other can join with oil and grease. Many soap particles gather around a small drop of oil. The water can then lift the covered drop from a plate or from your hands. Rubbing and warm water help the soap reach more of the dirty surface.`, "chemistry and materials", "explanatory-nonfiction"),
  entry(3, "Famous books", "Mary Opens the Hidden Garden", `Mary lives in a large, quiet house and often feels lonely. One day, a robin leads her to a key in the soil. She finds a door hidden by plants and enters a garden that has been closed for years. Mary begins to clear the paths and care for the roses. She shares the secret with two boys. As the garden grows stronger, the children also become healthier, kinder, and more hopeful.`, "gardens and personal growth", "classic-retelling", "The Secret Garden"),
  entry(3, "Mystery and adventure", "The Map in the Flour", `After the bread shop closes, a strange pattern appears in flour on the floor. It looks like a map with a circle near the oven. Sora and Ben search the room but find nothing unusual. Then Ben sees a tiny ant beside the marks. The circle is not treasure. It is a small bit of cookie that the ant walked around. Their grand mystery ends when they clean the floor and laugh.`, "clue-based mysteries", "mystery-fiction"),
  entry(3, "Travel and culture", "A Song for the Ferry", `Leah takes an evening ferry between two islands. Most passengers are tired after a day at the market. An older man opens a small drum and taps a steady beat. A woman across the deck answers with a song. Soon, other travelers join the easy chorus. Leah does not know every word, but she learns the final line. When the ferry reaches the dark harbor, the passengers leave as if the trip were shorter.`, "music and shared journeys", "travel-vignette"),
  entry(3, "People and biography", "Mei Builds a Seed Shelf", `Mei works at a neighborhood garden. She sees that people often buy the same seeds while rare local plants disappear. She asks older neighbors which beans and plants used in food they remember. Together they dry seeds, label small paper bags, and build a shelf in the library. Anyone may take seeds after promising to return some later. The project begins with six boxes. Within two years, the shelf holds plants from every street in the area.`, "gardening and community knowledge", "fictional-biography"),

  // Level 4
  entry(4, "Fantasy/stories", "The Ferryman of Sleeping Words", `On a river that appeared only at dusk, Ivo carried forgotten words from one bank to the other. People came with words they had almost lost: a grandmother's nickname, the name of a childhood street, a promise made years ago. Ivo placed each word in a paper boat and pushed it across the silver water. One evening, he could not remember his own name. The travelers searched their pockets and memories. At last, a woman found it in a song he had taught her as a child. She sang “Ivo,” and every paper boat turned toward him.`, "memory and enchanted journeys", "narrative-fiction"),
  entry(4, "Nature and animals", "A Forest Made by Elephants", `Elephants change the land as they search for food and water. They push over small trees, open paths, and dig in dry riverbeds. These actions can create grassland and water holes used by other animals. Their dung also carries seeds to new places. The results are not the same in every habitat, and too many elephants in a limited area can damage trees. In a balanced system, however, their daily movement helps shape a varied home for birds, insects, and grazing animals.`, "ecosystems and large animals", "explanatory-nonfiction"),
  entry(4, "World affairs", "A Vote for the Old Station", `The town's empty train station needed costly repairs. Some residents wanted to sell it to a hotel company. Others hoped to turn it into a health center and public hall. The council published the price of each plan and invited questions before a local vote. Young people could not vote, so they made models showing how each design would affect the square. The health center plan won by a small margin. Because the debate had been open, most residents accepted the result and joined a group that watched the budget.`, "local government and public space", "explanatory-nonfiction"),
  entry(4, "Everyday life", "Three Ways to Say Sorry", `Riku borrowed his roommate's bicycle without asking and returned it with a flat tire. His first apology was quick: “Sorry about that.” It did not help. His second apology explained that he had been late for work. That sounded like an excuse. Finally, Riku listened to why the bicycle mattered, paid for a new tube, and asked before using it again. The useful apology was not longer because of special words. It worked because he named the harm, repaired what he could, and changed his behavior.`, "relationships and communication", "narrative-fiction"),
  entry(4, "History", "The Coffeehouses of London", `In seventeenth-century London, coffeehouses became places where customers could hear news, discuss trade, and argue about public events. Different houses attracted sailors, writers, merchants, or people interested in science. Printed papers and letters were often read aloud because not everyone could read them. These rooms were not open equally to all parts of society, but they created new spaces for exchanging information. Some businesses that later became important grew from meetings held over cups of coffee.`, "social and cultural history", "historical-narrative"),
  entry(4, "Science", "Why Bridges Need Room to Move", `A bridge may look completely still, but its materials expand in heat and contract in cold. A long metal section can change length enough to damage the road if it has nowhere to move. Engineers leave small gaps called expansion joints between sections. The joints allow controlled movement while wheels can still cross safely. Wind and traffic also make bridges bend a little. Good design does not fight every movement. It guides that movement so the structure can remain strong.`, "engineering and materials", "explanatory-nonfiction"),
  entry(4, "Famous books", "Dorothy and Three Travelers", `A storm carries Dorothy and her house to the strange land of Oz. She wants to return to Kansas, so she follows a yellow road toward the Emerald City. Along the way, she meets a Scarecrow who wants a brain, a Tin Woodman who wants a heart, and a Lion who wants courage. They face dangers together and discover that they already show the qualities they seek. Dorothy finally learns that the power to go home has been with her during the journey.`, "quests and friendship", "classic-retelling", "The Wonderful Wizard of Oz"),
  entry(4, "Mystery and adventure", "The Lighthouse Without a Keeper", `During a sailing trip, Ana sees a lighthouse flash an unusual pattern. The island station is meant to work by itself, so no keeper lives there. A storm is approaching, but the light repeats three short flashes and one long flash. Ana records the pattern and radios the coast office. On the island, workers find that a loose panel is blocking the turning lamp at regular points. The signal was not a secret message, yet noticing it prevents ships from trusting a damaged light during the storm.`, "coastal mysteries", "mystery-fiction"),
  entry(4, "Travel and culture", "The Courtyard Cinema", `In a crowded neighborhood, Salma follows a hand-painted sign through a narrow doorway. Inside, families have placed chairs around a white wall. The weekly film will begin after sunset. Before it starts, two teenagers translate the introduction for visitors who speak different languages. A shopkeeper sells tea, while children trade seats so older neighbors can sit near the front. Salma had expected a formal theater. Instead, she finds a cinema built for one evening from a wall, a projector, and many small acts of cooperation.`, "community arts and public space", "travel-vignette"),
  entry(4, "People and biography", "Theo Counts the Night Sky", `Theo teaches mathematics at a rural school. His students can see many stars, but the school owns no telescope. He begins with cardboard tubes and simple star maps. Students record where bright stars appear at the same time each week. Theo sends their observations to a university project, which lends the class a small camera. The camera is useful, but Theo keeps the cardboard tubes. They remind the students that careful questions and repeated notes can begin real scientific work before expensive tools arrive.`, "science and education", "fictional-biography"),

  // Level 5
  entry(5, "Fantasy/stories", "Mara's Ticket to the Dream Museum", `At the end of a street that appeared on no map, Mara found a museum with one room for every dream people had abandoned. A dusty violin played half a song. An empty frame held the first line of a painting. A model bridge stopped just before reaching the other side. The guide gave Mara no tour. He simply handed her a ticket bearing the name of the bakery she had once planned to open.

Behind a glass door, she saw a warm kitchen with one cold oven. Mara could not carry the room home, but she copied the bread recipe pinned to its wall. The next morning, she baked one loaf in her apartment and shared it downstairs. The museum did not demand that she finish her old dream exactly. It only returned the part that still felt alive.`, "dreams and second chances", "narrative-fiction"),
  entry(5, "Nature and animals", "The Night Work of Moths", `Bees and butterflies are well-known visitors to flowers, but many plants receive help after sunset. Moths fly between pale or strongly scented flowers that are easier to find in darkness. As a moth drinks nectar, pollen can cling to its body and travel to another flower. This nighttime work supports both wild plants and some crops. Many people never see it because they are asleep while these insects move from plant to plant.

Outdoor lights can interrupt the pattern. A moth circling a bright lamp may spend less time feeding or finding a mate. Researchers compare dark places with lighted ones to understand the effect. Turning off unnecessary lights, directing lamps downward, and using light only when needed can make nights safer for insects without leaving people entirely in the dark.`, "pollination and nocturnal wildlife", "explanatory-nonfiction"),
  entry(5, "World affairs", "The Market's Common Refrigerator", `Food sellers at an outdoor market lost vegetables whenever hot weather arrived. Each family wanted a refrigerator, but electricity and equipment were too expensive. The market group proposed one shared cold room. That raised new questions: who would pay, whose food would enter first, and what would happen during a power cut?

The sellers tested a simple system for one season. Fees were based on the space used, small farms received reserved shelves, and a public list showed the order of access. Solar panels reduced some electricity costs, while an emergency fund paid for repairs. The cold room did not remove every loss. Still, the clear rules kept a shared tool from becoming controlled by only the largest businesses.`, "food systems and shared infrastructure", "explanatory-nonfiction"),
  entry(5, "Everyday life", "Four Colors for Family Care", `When their mother needed several weeks of rest, three adult siblings promised to help. Their messages quickly became confusing. One person bought the same food that another had already delivered, while nobody remembered the clinic appointment. They placed a paper calendar on the refrigerator and used three colors: meals, travel, and quiet visits.

The calendar solved practical mistakes, but it also revealed a deeper problem. The youngest brother had agreed to too much because he felt unable to say no. During a family call, each person named what they could truly manage. A neighbor offered one weekly meal, and a cousin handled phone calls. Caring became less about heroic effort and more about honest, dependable pieces of work.`, "family care and planning", "narrative-fiction"),
  entry(5, "History", "When Maps Put South at the Top", `Modern maps often place north at the top, but this choice is a convention rather than a natural law. Mapmakers in different times and places have used many directions. Some medieval European maps placed east at the top because it carried religious meaning. Several Islamic map traditions showed south above north. Chinese maps also varied according to purpose and period.

A map's orientation can shape how viewers imagine the world. Places near the top may appear more important, even when the arrangement is only a design choice. Rotating a familiar map can therefore feel surprisingly uncomfortable. Looking at older maps reminds us that every map selects a viewpoint, a center, and a purpose; it does not simply copy the earth onto paper.`, "maps and worldviews", "historical-narrative"),
  entry(5, "Science", "The Memory in a Metal Clip", `Bend a metal paper clip slightly, and it often springs back. Bend it too far, and it keeps a new shape. The first change is elastic: atoms move a little from their usual positions, then return when the force ends. Beyond a certain point, layers inside the metal slide past one another and cannot fully return.

Engineers need to know where this limit lies. A bridge cable, bicycle frame, or aircraft part must handle repeated forces without slowly changing shape. Tests pull, press, and bend sample materials while machines record their response. The paper clip is not a perfect model of every metal, but it offers a small demonstration of why strength includes both resisting force and recovering afterward.`, "forces and materials", "explanatory-nonfiction"),
  entry(5, "Famous books", "Alice at the Queen's Game", `Alice enters a garden where playing cards paint white roses red. The Queen arrives and turns every small mistake into a threat of punishment. Soon, Alice is invited to a game of croquet played with live animals instead of proper equipment. No one follows the same rules, and the Queen changes them whenever she wishes.

At first, Alice tries to behave politely inside this nonsense. As the game becomes more unfair, she begins to question the Queen's authority. The loud commands still frighten everyone else, but they no longer seem reasonable to Alice. Her growing size matches her growing confidence: she is learning that a rule is not worthy of respect merely because a powerful person shouts it.`, "nonsense and authority", "classic-retelling", "Alice's Adventures in Wonderland"),
  entry(5, "Mystery and adventure", "Clocks Corrected the Wrong Way", `Every clock in the research station lost exactly one minute at noon. The digital clocks, wall clocks, and even two watches showed the same change. Priya suspected an electrical fault, but the battery clocks should not have been affected. She recorded the room with her phone and watched the time display carefully.

At noon, nothing jumped backward. Instead, an assistant entered each room during lunch and adjusted the clocks by hand. He believed they were running fast because his radio announced noon later. Priya checked the radio and found that it was playing a recorded program from another time zone. The station's clocks had never lost a minute. A helpful person had been correcting them toward the wrong signal.`, "technology mysteries", "mystery-fiction"),
  entry(5, "Travel and culture", "A Library on the Night Train", `On an overnight train, Elena noticed a narrow shelf between two carriages. It held novels, children's books, and travel guides with no price labels. A card explained the rule: take one for the journey, then leave it at another station or replace it with a different book.

Elena chose a collection of short poems. At breakfast, she met a student reading a mystery that had begun its trip hundreds of kilometers away. They compared the notes travelers had written inside the covers. Before leaving, Elena placed her own finished novel on the shelf. The moving library had no membership desk, yet each reader became both a borrower and a temporary keeper.`, "rail journeys and book exchange", "travel-vignette"),
  entry(5, "People and biography", "Amara Listens Before Building", `Amara trained as an engineer and returned to a town where heavy rain often flooded the lower streets. Her first idea was a high concrete wall beside the river. Before drawing it, she visited shop owners, school staff, and families who lived uphill. Their stories showed that blocked drains and paved gardens were sending water downhill faster than before.

Amara proposed several smaller changes: open soil around trees, repaired drains, a pond near the sports field, and raised doors for the lowest homes. The plan was less dramatic than one great wall, but it could be built in stages and checked after each rainy season. Her most valuable instrument was not a machine. It was the habit of listening before deciding what problem to solve.`, "engineering and community service", "fictional-biography"),

  // Level 6
  entry(6, "Fantasy/stories", "The Cartographer of Echoes", `Nalin made maps of sounds that had nowhere else to live. He marked the laughter beneath an abandoned bridge, the final note of a closed theater, and the soft knock that winter branches made against a school window. His maps were useless for finding roads, but people came when they feared a beloved sound had vanished.

One customer asked for her father's whistle, which she had not heard since childhood. Nalin searched the harbor where the man once worked, yet wind and engines covered every trace. Finally, he asked what the whistle had meant. “He was calling me home,” she said. Nalin drew a path from the harbor to her old front door and left the map silent. She followed it at sunset. Halfway home, she remembered the tune well enough to whistle it herself.`, "memory and magical crafts", "narrative-fiction"),
  entry(6, "Nature and animals", "How Trees Share a City Block", `A street tree does more than decorate a sidewalk. Its leaves cast shade, release water vapor, catch some airborne particles, and slow rain before it reaches drains. Roots create spaces in the soil where water can enter. Birds and insects may use the branches for food or shelter. These benefits, however, depend on choosing a suitable species and giving it enough room.

Trees planted in tiny pits often struggle. Their roots may lift pavement while their crowns suffer from heat and dry soil. Cities increasingly treat groups of trees as connected infrastructure rather than isolated objects. Larger soil beds, rain gardens, and careful pruning allow roots and streets to coexist. The strongest urban forest is not simply the one with the most planting ceremonies; it is the one whose trees can remain healthy for decades.`, "urban ecology", "explanatory-nonfiction"),
  entry(6, "World affairs", "Who Owns the Weather Data?", `Farmers in a dry region relied on weather stations installed by a private company. The forecasts were useful, but detailed rainfall records were available only through an expensive subscription. Small farms could not afford the fee, even though public grants had paid for part of the equipment.

A farmers' group argued that basic data gathered with public money should remain open. The company replied that maintenance and improved forecasts required income. A new agreement separated the two products. Raw measurements became freely available through a public website, while the company continued selling specialized analysis and alerts. The compromise did not satisfy everyone, but it clarified an important distinction: access to shared facts need not eliminate the market for services built from them.`, "data access and agriculture", "explanatory-nonfiction"),
  entry(6, "Everyday life", "The Roommate Meeting Without a Winner", `Four roommates were arguing about noise, dishes, and guests. Each meeting ended with someone proving that another person had broken a rule. Their apartment grew quieter, but not more comfortable. At the next meeting, they tried a different question: what did each person need in order to rest and feel at home?

One roommate worked early shifts and needed silence after ten. Another studied music and needed practice time. They agreed on two practice hours before dinner, headphones later, and one shelf where unfinished dishes could wait briefly without filling the sink. The arrangement required adjustment after a week. It succeeded because the group stopped treating the conversation as a trial. A home could have boundaries without needing one person to defeat another.`, "shared homes and conflict", "narrative-fiction"),
  entry(6, "History", "The Strike of the Match Workers", `In 1888, many women and girls working at a London match factory walked out. Their work involved low wages, strict fines, and exposure to white phosphorus, a substance linked to severe illness. Newspaper reports and public support helped draw attention to conditions that workers had long understood from daily experience.

The strike ended with several important concessions, including changes to fines and the recognition of worker representatives. It did not solve every problem in the industry, and safer materials still had to be adopted. Yet the action challenged a common belief that poorly paid young women had little power. By organizing together and making their knowledge public, the workers influenced both their workplace and later debates about labor reform.`, "labor and social reform", "historical-narrative"),
  entry(6, "Science", "A Battery Made by Moving Ions", `A battery separates chemical reactions so that electrons must travel through an outside circuit. Inside the battery, charged atoms or molecules called ions move through a material that conducts them. Outside, electrons flow through a wire and can power a lamp, motor, or phone. When the useful chemical difference is exhausted, the flow stops.

Rechargeable batteries use reactions that can be pushed largely in reverse by an external source of electricity. Charging does not store loose electricity in a box; it restores chemical conditions that can later produce a current again. Heat, charging speed, and repeated use affect how well that process continues. Different battery designs balance energy, cost, weight, safety, and the availability of their materials.`, "electricity and chemistry", "explanatory-nonfiction"),
  entry(6, "Famous books", "Jim Hears the Apple Fall", `Jim Hawkins lives at an inn where a secret map comes into his hands. He joins a voyage to the island marked on it, but several crew members are pirates led by the clever Long John Silver. While hiding in an apple barrel, Jim overhears their plan to take the ship after the treasure is found.

The discovery forces Jim to act before the honest sailors are ready. He slips away, meets a man who has survived alone on the island, and takes dangerous risks that sometimes help his friends and sometimes alarm them. The adventure teaches him that courage is not the same as trusting everyone who seems friendly. Silver can be generous in one moment and threatening in the next, which makes judgment harder than any map suggests.`, "sea adventure and moral choices", "classic-retelling", "Treasure Island"),
  entry(6, "Mystery and adventure", "The Compass in the Archive", `A museum archive received a brass compass with no record of its owner. The needle pointed east instead of north, even when staff moved it away from metal shelves. A scratched date on the case matched a polar expedition, and one researcher imagined a dramatic failure in the ice.

Conservator Dalia tested the compass beside other instruments and found that its needle was magnetized correctly. The painted letters on the dial had been replaced in the wrong positions during an old repair. Wear around the screws confirmed that the face had been removed. The object had not guided explorers east by mistake. Its confusing direction came from a later attempt to make it look complete, reminding the team that repairs can become part of an artifact's mystery.`, "museum mysteries", "mystery-fiction"),
  entry(6, "Travel and culture", "The Mountain Post Office", `At the final stop of a mountain bus route, Dev found a post office inside a grocery shop. Letters arrived only three days a week. Residents collected mail for neighbors who lived along distant paths, and the shopkeeper kept a notebook showing who had taken each bundle.

Dev had come to photograph remote public services, but the notebook changed his plan. It revealed a system based on trust, memory, and repeated favors rather than speed. He asked permission before taking any pictures and spent a day walking with a farmer who delivered four letters beyond the road. The post office was small, yet its true service extended across the valley through people who treated another person's message as part of their own journey.`, "mountain communities and communication", "travel-vignette"),
  entry(6, "People and biography", "Rosa Makes Numbers Visible", `Rosa worked in a city housing office where residents often received pages of rent and repair data. The figures were public, but few people could understand what they meant for a particular building. She began turning the tables into simple maps that showed unfinished repairs, waiting times, and changes from one month to the next.

At first, managers worried that the maps would make the department look bad. Rosa argued that unclear data already damaged trust. She added notes explaining missing information and invited tenant groups to check the displays before publication. The maps exposed delays, but they also showed where new repair teams were improving results. Rosa's work did not replace difficult meetings. It gave everyone a common picture to question when those meetings began.`, "data and public service", "fictional-biography"),
  // Level 7
  entry(7, "Fantasy/stories", "Veyra Spends Its Spring", `Every winter, the city of Veyra borrowed one warm day from the coming spring. The borrowed sunlight melted ice from roofs and allowed families to repair what the storms had damaged. In return, one spring day arrived gray and cold. For generations, the exchange seemed harmless.

Then the council began borrowing extra days for festivals, elections, and important visitors. Spring became a brief season of rain and frost. Orchards flowered late, and birds arrived to find little food. A young calendar keeper named Sen discovered that the contract did not limit repayment to weather. The city could return time by giving up days of business.

Veyra closed its markets for a week. People planted trees, repaired nesting places, and shared meals without buying or selling. The lost spring days did not return at once. Yet when leaders next requested sunshine for a parade, citizens remembered the silent orchards and refused to sign.`, "time, weather, and civic choices", "narrative-fiction"),
  entry(7, "Nature and animals", "How Beavers Reshape a Valley", `A beaver dam slows a stream rather than stopping water completely. The pond that forms behind it spreads water across the valley floor, where sediment can settle and plants suited to wet ground can grow. Fallen branches create shelter for fish, insects, amphibians, and birds. During dry periods, water stored in the surrounding soil may help the area remain green.

The effects are not welcome everywhere. A new pond can flood a road, field, or building, and dams can block some fish movements. Land managers therefore use several approaches: protecting space where flooding is harmless, installing devices that control pond height, or moving animals when serious conflict cannot be reduced.

Calling beavers “ecosystem engineers” captures their large influence, but it does not mean every dam belongs in every place. Effective conservation depends on understanding both the wetland they create and the human structures already sharing the valley.`, "wetlands and ecosystem engineering", "explanatory-nonfiction"),
  entry(7, "World affairs", "The Price of a Free School Meal", `A regional government proposed free lunches for every primary-school student. Supporters argued that a universal program would reach children whose families avoided assistance because of shame or complicated forms. Critics said limited funds should be directed only toward households with low incomes.

The budget office compared more than the price of food. A targeted program required applications, staff to check income, and systems for collecting unpaid fees from everyone else. A universal program cost more in meals but less in administration. Schools also reported that shared access could reduce visible differences between students.

The final plan offered universal basic lunches while charging for optional extras. Researchers were asked to track attendance, food waste, health indicators, and total cost for three years. The decision did not prove that universal programs are always better. It showed why policy comparisons must include access, dignity, and administrative burden alongside the most obvious number.`, "education and social policy", "explanatory-nonfiction"),
  entry(7, "Everyday life", "The Family Photograph Nobody Wanted", `After their aunt died, cousins gathered to divide a box of family photographs. Everyone wanted the formal wedding portraits. Nobody chose a faded picture of five people washing dishes in a crowded kitchen. Maya took it because she recognized the apartment where her mother had grown up.

Later, she asked relatives about the scene. One cousin remembered the broken water heater. Another recalled that the family had cooked for neighbors after a storm. The youngest person in the photograph, now an old man, explained why everyone was laughing: a cake had fallen, and they had served it from a cooking pot.

The imperfect image produced more stories than the careful portraits. Maya scanned the whole collection and invited relatives to record short notes beside each picture. She learned that preserving a family history did not mean identifying the most beautiful objects. It meant keeping enough ordinary details for questions to begin.`, "family memory and archives", "narrative-fiction"),
  entry(7, "History", "Paper, Print, and the Korean Metal Type", `Centuries before movable metal type transformed European printing, printers on the Korean Peninsula were using cast metal characters. A surviving Buddhist book printed in 1377, known as the Jikji, demonstrates that the technique was established during the Goryeo period. Individual characters could be arranged, inked, pressed onto paper, and reused.

The system still demanded skill and resources. Written Korean commonly relied on a large set of Chinese characters, so printers needed many pieces of type. Woodblocks remained useful, especially when a work would be printed repeatedly. Metal type was therefore one method within a broader culture of books rather than a simple replacement for everything that came before.

This history complicates stories that present printing as a single invention at one moment. Technologies often develop in several places, and their impact depends on language, institutions, materials, and the readers a society is prepared to serve.`, "printing and knowledge systems", "historical-narrative"),
  entry(7, "Science", "Why Concrete Can Heal Small Cracks", `Concrete is strong under compression but can develop tiny cracks as it dries, carries weight, or changes temperature. Water entering those cracks may eventually damage steel reinforcement. Some researchers and builders use “self-healing” approaches to slow that process.

One method places inactive bacteria and nutrients inside the material. When water reaches a crack, the bacteria become active and help form minerals that fill part of the gap. Other systems use capsules containing repair agents, while some concrete can seal very narrow cracks through continued chemical reactions of unused cement.

Self-healing does not make a damaged structure immortal. Large cracks, design errors, and corrosion still require inspection and repair. The value lies in extending service life and reducing maintenance where small cracks are common. Engineers must compare the added cost and environmental effect with the resources saved over decades of use.`, "materials and sustainable engineering", "explanatory-nonfiction"),
  entry(7, "Famous books", "The Traveler from the Distant Future", `A Victorian inventor tells his skeptical guests that time is another direction through which a machine might travel. He later returns exhausted and describes a distant future divided between the gentle Eloi, who live above ground, and the Morlocks, who maintain machines below it.

At first, the traveler assumes the Eloi represent a peaceful, advanced society. Evidence gradually weakens that view. Their comfort has left them vulnerable, while the underground world reveals a darker relationship between the two groups. When the time machine disappears, he must enter the Morlocks' tunnels and reconsider every easy conclusion he has made.

His adventure is more than a tour of strange creatures. It extends the inequalities of his own age into an imagined future and asks what might happen when social divisions become biological ones. The machine moves through time, but the warning is directed toward the present.`, "social science fiction", "classic-retelling", "The Time Machine"),
  entry(7, "Mystery and adventure", "The Radio Call from Dry Land", `A rescue boat received a weak distress call that seemed to come from open water. The speaker reported rising waves, gave half a vessel name, and then disappeared. No registered boat matched the fragment. As the crew followed the signal, its direction shifted toward the coast rather than the sea.

Navigator Ellis compared the transmission times with the tide. The message repeated at irregular but familiar intervals. It was not a live call; a damaged coastal radio was replaying part of an old training exercise whenever water entered its power box. The station stood on land, yet reflections and changing signal strength had made the source difficult to locate.

The crew still treated the discovery seriously. A false call can draw rescuers away from real danger. They removed the radio and reported the failure, then searched the nearby water once more before returning. Solving the mystery did not mean assuming nobody needed help.`, "maritime rescue mysteries", "mystery-fiction"),
  entry(7, "Travel and culture", "The Language of Shared Gardens", `In a district shaped by several waves of migration, Eva visited a community garden where no single language dominated. The planting beds revealed histories that the signs did not: climbing beans from one family's childhood, bitter greens used in another household's soup, and flowers grown for a yearly remembrance.

Gardeners had developed practical ways to work together. Tool labels included pictures. Planting dates were marked with colors and moon shapes. When a precise explanation was needed, younger relatives often translated, but older growers also taught by placing a seed, measuring with a hand, and demonstrating how deeply it should be covered.

Eva arrived hoping to collect recipes. She left with a different understanding of cultural exchange. It was not simply the mixing of traditions into something new. It also involved protecting specific knowledge, accepting moments of confusion, and giving people time to show what they could not yet explain in shared words.`, "migration, food, and community gardens", "travel-vignette"),
  entry(7, "People and biography", "Jonas Opens the Workshop Door", `Jonas repaired farm machinery in a region where skilled mechanics were becoming scarce. Young apprentices often left because training meant months of cleaning and watching before they were trusted with real tasks. Jonas remembered nearly leaving for the same reason.

He reorganized the workshop around small, supervised projects. A beginner might diagnose a pump, explain the evidence, and complete one safe part of the repair. Mistakes were recorded in a shared notebook without the worker's name, so the team could discuss causes rather than blame. Experienced mechanics worried that teaching would slow production, and at first it did.

Within two years, fewer repairs returned with the same fault, and apprentices stayed longer. Jonas had not lowered the standard of the trade. He had made the path toward that standard visible, replacing a culture of silent endurance with one in which expertise included the ability to teach.`, "skills, work, and mentorship", "fictional-biography"),

  // Level 8
  entry(8, "Fantasy/stories", "The Ministry of Lost Shadows", `In Lume, every citizen registered a shadow at birth. Officials measured its length, stamped its outline on paper, and promised that the record would protect the owner from impostors. Most people forgot the registry existed until shadows began disappearing at noon.

The ministry blamed an unusual sun. Street vendors blamed thieves. Aya, a junior clerk, noticed that the missing shadows belonged to people whose records had been corrected too many times: a name changed after marriage, an address rewritten after a flood, a birth date copied badly from an old book. The registry had started treating imperfect files as imperfect people.

Aya could restore each shadow by deleting the conflicting entries, but that would erase parts of the owner's life. Instead, she persuaded the ministry to accept records that contained visible revisions. As clerks added notes rather than replacing old truths, shadows returned in varied shapes—some sharp, some faint, none matching the original forms exactly.

Citizens complained that the new archive looked untidy. Aya agreed. A truthful record, she said, was allowed to show that a life had changed.`, "identity, records, and magic", "narrative-fiction"),
  entry(8, "Nature and animals", "The Hidden Routes of Fungal Spores", `Fungi cannot walk toward a new habitat, yet their spores travel through remarkably varied routes. Some are lifted by air currents and cross long distances. Others cling to animal fur, survive passage through digestive systems, or ride inside soil moved by water and human activity. A mushroom's visible cap is therefore only one stage in a much larger system of dispersal.

Release can be precisely timed. Changes in humidity alter the tension of tissues around some spores, while certain cup fungi use sudden pressure to launch thousands at once. Even a slight difference in air temperature above a mushroom may help create currents that carry spores away from the still air near the ground.

Most spores land where they cannot grow. Successful establishment requires suitable moisture, food, temperature, and often a compatible partner. This enormous loss is not evidence of a failed strategy; producing many small travelers increases the chance that a few will reach rare opportunities. Fungal movement is less visible than migration by wings or feet, but it shapes forests, farms, and indoor environments.`, "fungal ecology and dispersal", "explanatory-nonfiction"),
  entry(8, "World affairs", "The Algorithm at the Housing Desk", `A city introduced software to rank applications for limited public housing. Officials hoped it would reduce waiting times and apply the same rules to everyone. Within months, however, legal-aid workers noticed that applicants with unstable addresses were repeatedly placed lower on the list.

The software did not contain a rule against homelessness. It treated missing mail, incomplete work records, and frequent address changes as signs that an application might require more staff time. Because the system had been designed to maximize administrative speed, it quietly favored people whose lives were already easier to document.

The city suspended automatic ranking and published the factors used by the model. Applicants gained a process for challenging inaccurate data, while staff reviewed whether efficiency was the right objective for each decision. Software still helped detect duplicate files and schedule appointments, but it no longer made the final order.

The case illustrated a wider lesson: consistent treatment is not necessarily fair treatment. An automated system can reproduce inequality without using an openly discriminatory category, especially when its chosen measure of success ignores the purpose of the service.`, "technology, housing, and public accountability", "explanatory-nonfiction"),
  entry(8, "Everyday life", "The Inheritance of Thirty Teacups", `When their grandmother moved into a smaller home, Nari and her brother were asked to divide thirty porcelain teacups. Some were valuable, most were not, and none formed a complete set. Their mother wanted to keep everything because each cup seemed connected to a visitor, holiday, or vanished kitchen.

The siblings first tried assigning prices, but money did not explain why a chipped green cup caused the strongest disagreement. Their grandmother finally admitted that she remembered buying only a few of them. Many stories attached to the cups had blended together over time.

They photographed the collection, recorded whatever memories remained, and invited each family member to choose one cup for use rather than display. A local theater took the rest as stage props. Months later, the green cup cracked completely while Nari was drinking tea. She repaired it enough to hold pencils.

The family did not preserve the collection intact. Instead, they separated memory from obligation. By allowing ordinary objects to continue changing, they kept the stories available without requiring every descendant to become a museum keeper.`, "family objects and letting go", "narrative-fiction"),
  entry(8, "History", "The Port That Quarantined Its Letters", `During outbreaks of plague in early modern Europe, some ports restricted not only people and goods but also letters. Paper was believed capable of carrying dangerous material. Officials cut small slits in folded correspondence and exposed it to smoke or vinegar before allowing it onward. The marks left by these practices can still be found in archives.

Such measures combined observation, fear, and incomplete theories of disease. Authorities understood that movement between places could spread illness, yet they lacked modern knowledge of bacteria, fleas, and transmission. Quarantine rules also affected trade, diplomacy, and private relationships, so enforcement varied according to political and economic pressure.

A treated letter is therefore more than evidence of an old medical mistake. It records an attempt to manage uncertainty with the tools available at the time. The cuts in the page reveal how governments balanced communication against perceived risk, while the surviving words remind us that people continued exchanging news, affection, and business even when every contact seemed suspect.`, "public health and communication", "historical-narrative"),
  entry(8, "Science", "Listening to a Bridge with Sensors", `A bridge responds continuously to traffic, wind, temperature, and changes in the ground beneath it. Most movement is tiny and expected. The challenge for engineers is distinguishing this normal behavior from patterns that may indicate damage.

Modern monitoring systems combine several kinds of sensors. Accelerometers record vibration; strain gauges measure slight deformation; temperature sensors explain seasonal expansion; and positioning instruments detect slow shifts. A single unusual reading rarely proves that a structure is unsafe. A heavy truck, strong gust, damaged sensor, or software error can produce a dramatic signal.

Engineers therefore compare measurements across time, locations, and operating conditions. A change that persists after temperature and traffic are considered deserves closer inspection. Statistical models can help identify patterns, but physical examination remains essential.

Monitoring does not replace maintenance, nor does it predict every failure. Its value is to make gradual change visible, allowing scarce inspection resources to focus where several kinds of evidence point to the same concern.`, "structural monitoring and data", "explanatory-nonfiction"),
  entry(8, "Famous books", "Elizabeth Doubts Her First Impression", `Elizabeth Bennet takes pride in reading character quickly. When the wealthy Mr. Darcy behaves coldly at a dance, she readily believes a charming officer's account of his selfishness. Darcy, meanwhile, judges Elizabeth's family by their social position and manners. Each mistakes confidence for understanding.

Darcy's unexpected proposal exposes both errors. He speaks as though loving Elizabeth should overcome the embarrassment of her connections; she refuses him and accuses him of harming others. His later letter does not demand forgiveness. It supplies information that complicates the story she has accepted, particularly the officer's claims and Darcy's role in separating another couple.

Elizabeth's change is neither instant romance nor simple surrender. She tests the letter against memory, recognizes where wounded pride shaped her interpretation, and observes Darcy behaving differently when no reward seems likely. Darcy must also change, learning to act with greater humility.

Their eventual understanding depends on revision. The novel treats judgment as necessary but fallible: maturity lies not in having no first impressions, but in examining them when evidence and self-knowledge make certainty uncomfortable.`, "judgment, class, and self-knowledge", "classic-retelling", "Pride and Prejudice"),
  entry(8, "Mystery and adventure", "The Glacier Camera", `A research team recovered a camera from the edge of a retreating glacier. Its memory card contained recent photographs, although the model had not been sold for twenty years. The final image showed a red tent beside a ridge that no longer matched the visible landscape.

Mountain guide Safiya rejected the obvious story of a long-lost expedition. The battery compartment was clean, and the file dates reset whenever power failed. She compared rock patterns in the photograph with old survey images. The ridge was not gone; it was being viewed from the opposite side through a narrow valley.

The team hiked to that position and found fragments of red fabric tied as route markers. A local photographer had placed the old camera in a weather box to document ice change, then stopped visiting after an injury. Meltwater had carried the box downhill.

The discovery still mattered, but not as a dramatic rescue clue. Once the owner was found, researchers obtained permission to use the image series. The misleading dates became a two-decade visual record, showing that evidence can remain valuable after its most exciting explanation disappears.`, "mountain and environmental mysteries", "mystery-fiction"),
  entry(8, "Travel and culture", "An Evening in the House of Wind", `On a hot plateau, Karim stayed in a restored house built around a shaded courtyard. A tall wind tower rose above the roof. Its openings caught moving air and directed it downward, while warm air escaped elsewhere. Water and thick walls helped moderate the indoor temperature.

The owner resisted presenting the building as a perfect answer from the past. The house had once depended on labor, wealth, and social arrangements that a brief architectural tour could easily ignore. Modern roads also brought noise and dust that earlier builders had not faced. Some rooms now used efficient fans during the hottest weeks.

At dinner, residents discussed which features could inform new housing: orientation, shade, shared courtyards, and ventilation that did not rely entirely on mechanical cooling. Copying the tower's shape without studying local wind would achieve little.

Karim left with no simple contrast between tradition and technology. The house was valuable because people continued testing its principles, adapting them without pretending that either the old building or the modern city existed outside history.`, "climate-responsive architecture", "travel-vignette"),
  entry(8, "People and biography", "Lin's Clinic on Wheels", `Lin managed a health clinic serving villages scattered across a wide farming region. A mobile van already visited each area, but missed appointments remained common. Administrators assumed residents were careless. Lin rode the full route and found a different pattern: market days changed with harvests, phone service failed in two valleys, and the van's printed schedule used place names that local families rarely used.

She invited drivers, nurses, shopkeepers, and patients to redesign the route. Appointments were announced through schools and food cooperatives as well as text messages. The schedule included familiar landmarks, and the van stayed later in places where seasonal work ended after sunset.

Attendance improved, yet Lin avoided describing the new route as finished. Floods, school terms, and crop cycles kept changing people's movement. The team reviewed missed visits monthly and asked what obstacle the service itself had created.

Lin's achievement was not bringing medicine to passive recipients. It was treating access as a relationship between a system and the lives around it, then accepting that the system also had a duty to move.`, "health access and rural services", "fictional-biography"),
  // Level 9
  entry(9, "Fantasy/stories", "The Republic of Second Names", `In the Republic, everyone received a second name after performing the act that supposedly revealed their true nature. A generous child might become Mira-Gives-Bread; a cowardly soldier could be recorded as Oren-Fled. The names appeared on contracts, doors, and voting lists. Citizens claimed the system rewarded character rather than birth.

Nessa's ceremony took place during a flood. She abandoned the official platform to pull a stranger from the water, but cameras recorded only her refusal to complete the test. The registry named her Nessa-Breaks-Oaths. Years of appeals failed because changing a second name required evidence from the ceremony, and the missing evidence was precisely the problem.

She became an archivist and began collecting cases in which a single public moment had hardened into identity. A judge named for mercy had later become cruel; a convicted thief quietly supported three families; a celebrated rescuer had caused the danger he resolved. Nessa did not argue that actions were meaningless. She argued that no action could finish a person.

When another flood damaged the central registry, officials asked her to reconstruct it. Instead of destroying the names, she added dates and spaces for later acts. The revised records grew complicated and difficult to display. Citizens initially missed the clarity of their old labels, but the inconvenience created room for change—and made every judgment visibly temporary.`, "identity, justice, and social memory", "narrative-fiction"),
  entry(9, "Nature and animals", "What Survives a Marine Heatwave", `When seawater remains unusually warm, corals may expel the microscopic algae living within their tissues. Because those algae provide much of a coral's energy and color, the colony turns pale in a process known as bleaching. Bleached coral is not necessarily dead, but prolonged stress raises the risk of starvation, disease, and loss.

Recovery varies sharply, even across one reef. Water depth, currents, prior exposure to heat, local species, and the arrival of coral larvae all influence what happens next. Herbivorous fish can help by limiting algae that would otherwise occupy open surfaces. Pollution, destructive fishing, and sediment from land add pressures that make recovery harder.

Restoration projects sometimes grow coral fragments in nurseries and attach them to damaged areas. Such work can protect genetic diversity or rebuild specific sites, but it cannot cool an entire ocean. Nor should a planted reef be judged only by the number of fragments that survive. A functioning ecosystem needs varied corals, fish, invertebrates, and continuing reproduction.

Local protection therefore matters alongside global action on warming. The two approaches are not substitutes: reducing nearby stress can preserve a reef's capacity to recover, while limiting climate change addresses the rising disturbance that repeatedly tests that capacity.`, "coral reefs and climate stress", "explanatory-nonfiction"),
  entry(9, "World affairs", "The Border River During Drought", `Two countries depended on a river whose flow had fallen after several dry winters. An old treaty divided water by fixed volumes, assuming the river would remain within its historical range. As reservoirs shrank, fulfilling the treaty left too little water for wetlands and downstream towns.

Upstream officials insisted that legal certainty protected farmers who had planned crops around promised deliveries. Downstream leaders argued that a rule designed for ordinary years could not justify empty drinking-water systems. Environmental groups added a third concern: if every remaining unit were allocated to immediate human use, damage to the river could reduce future supply for everyone.

Negotiators replaced part of the fixed allocation with percentages that changed according to total flow. They established a minimum ecological reserve, shared reservoir data in near real time, and created emergency funds for farmers paid to reduce water-intensive planting. A joint panel could recommend temporary adjustments but had to publish its reasoning.

The agreement did not make scarcity painless, nor did it remove unequal bargaining power. Its achievement was to treat the river as a changing system rather than a pipe carrying a predictable amount. Durable cooperation required rules capable of responding to conditions their original authors had not imagined.`, "water diplomacy and climate adaptation", "explanatory-nonfiction"),
  entry(9, "Everyday life", "The Cost of Being the Reliable Friend", `For years, Hana was the person friends called when plans failed. She collected children from school, covered work shifts, proofread applications, and listened through late-night crises. Her reliability became part of how she understood herself. Declining a request felt not merely unhelpful but dishonest.

The strain became visible when she forgot a promise to her younger sister. Hana responded by designing a stricter calendar, yet better organization only made room for more demands. A counselor asked her to distinguish generosity from permanent availability. The difference sounded selfish until Hana noticed how often resentment entered favors she had technically chosen.

She began answering requests after a short pause rather than immediately. Sometimes she offered a smaller form of help; sometimes she said that she could not help at all. A few relationships cooled. Others became more balanced when friends learned details about Hana's own needs for the first time.

Her new boundaries did not turn care into a calculation. They made consent part of it. Reliability stopped meaning that others could predict her surrender, and came to mean that her “yes” described a commitment she had enough energy to keep.`, "friendship, boundaries, and care", "narrative-fiction"),
  entry(9, "History", "The Census and the Making of Categories", `A census appears to count facts that already exist, yet every form must decide which distinctions deserve a box. Across different countries and periods, officials have classified people by occupation, language, religion, race, household role, disability, and citizenship. Categories have been added, divided, renamed, or removed as governments and social movements changed.

These choices produce practical consequences. Population totals can determine political representation, public funding, or legal recognition. A group absent from the form may become difficult to identify in policy, while a rigid category can flatten identities that people understand as overlapping or fluid. Historical census records are therefore valuable evidence, but they also preserve the assumptions of the institutions that created them.

Respondents have never been entirely passive. Some resisted questions, selected unexpected labels, or campaigned for new ones. Enumerators also interpreted answers, especially when literacy or language differences shaped the exchange.

Reading a census critically does not mean dismissing its numbers. It means asking how the measurement was constructed: who defined the terms, who was missed, what purpose the count served, and how the act of classification may have altered the society it claimed merely to describe.`, "states, identity, and statistics", "historical-narrative"),
  entry(9, "Science", "The Uncertainty Inside a Flood Map", `Flood maps often display a clean boundary between areas considered at risk and those outside it. The underlying calculation is far less exact. Engineers combine elevation data, rainfall records, soil behavior, drainage capacity, river flow, and models of how water moves across a surface. Each input contains uncertainty, and future land use or climate may differ from the past used to estimate it.

A line labeled as a one-percent annual flood zone does not mean flooding occurs once every hundred years on a reliable schedule. It describes an estimated probability in any given year. Over the life of a building, repeated exposure to that annual chance can become substantial. Nor does property just beyond the boundary have zero risk; model results change gradually even when regulations require a sharp administrative line.

Better maps increasingly show depth, possible routes, and several scenarios rather than a single outline. Communicating uncertainty, however, creates a dilemma. Too little detail encourages false confidence, while too much can make residents feel that experts know nothing.

The goal is not to eliminate uncertainty before acting. It is to reveal which conclusions are robust, update models as evidence changes, and design safety measures that still work when the water does not respect the printed boundary.`, "risk modeling and climate science", "explanatory-nonfiction"),
  entry(9, "Famous books", "Ahab and the Meaning of the White Whale", `Ishmael joins the whaling ship Pequod expecting an ordinary commercial voyage. Its captain, Ahab, soon reveals a private purpose: he intends to hunt Moby Dick, the white whale that destroyed his leg. He converts the ship's shared work into an instrument of personal revenge, using charisma, money, fear, and ritual to bind the crew to his pursuit.

The whale carries no single stable meaning. To Ahab, it becomes the visible surface of everything that limits or injures human will. Other sailors see an animal, a source of profit, an omen, or a danger best avoided. Ishmael's wide-ranging narration resists the captain's narrow certainty by filling the voyage with different cultures, kinds of knowledge, and ways of interpreting the sea.

Ahab's obsession is powerful partly because he transforms ambiguity into an enemy. Every warning becomes proof that fate challenges him; every chance to turn homeward appears cowardly. The crew's practical dependence on hierarchy makes resistance harder, even for those who recognize the danger.

When the final pursuit destroys the ship, Ishmael survives on a coffin that had been prepared for his friend Queequeg. The object designed for death becomes a means of rescue, preserving the novel's refusal to let symbols obey only one commanding interpretation.`, "obsession, authority, and interpretation", "classic-retelling", "Moby-Dick"),
  entry(9, "Mystery and adventure", "The Archive with Two Midnights", `A digital archive showed that confidential files had been opened at midnight by a researcher who was documented on another continent. The security log contained her correct account, device name, and access code. Administrators prepared to report stolen credentials, but analyst Mateo noticed that the records contained two midnights only forty minutes apart.

The archive stored some events in local server time and others in Coordinated Universal Time. A recent software update had converted timestamps twice when displaying activity from the night of a seasonal clock change. The researcher had accessed public files during the afternoon; the interface had moved her actions into a false midnight window.

That explained the timing but not the confidential documents. Mateo compared file identifiers rather than titles and found that several records had been renumbered during migration. The log pointed to old identifiers now assigned to restricted files, although the researcher had opened their public predecessors.

No intrusion had occurred. Still, the investigation exposed a serious weakness: a system meant to establish accountability could produce persuasive but incorrect accusations when time standards and identifiers changed. The archive preserved the flawed logs, added explicit conversion fields, and required future investigations to verify raw events before interpreting the display.`, "digital forensics and archives", "mystery-fiction"),
  entry(9, "Travel and culture", "The Festival After the Tour Buses", `A coastal town's lantern festival had once been organized mainly for residents, marking the end of a fishing season. Photographs attracted growing numbers of visitors, and tour companies began advertising front-row viewing areas that did not officially exist. Local families found their usual paths blocked, while temporary vendors sold decorations imported from elsewhere.

The town could have restricted outsiders entirely, but tourism supported guesthouses and restaurants during a quiet month. Organizers instead created a reservation system for the narrow harbor, limited bus arrivals, and directed part of visitor fees toward cleanup and fishing-safety programs. Residents received spaces through neighborhood groups rather than by competing online for tickets.

Not everyone approved. Some feared that formal management turned a shared custom into a product; others argued that unmanaged popularity had already done so. Younger residents used the new funding to record songs and boat-making techniques, while also changing parts of the event that they found exclusionary.

The festival remained neither untouched tradition nor pure tourist performance. Its future depended on who could make decisions, who absorbed the inconvenience, and whether visitors learned to encounter a living community rather than a scene arranged solely for their cameras.`, "tourism, festivals, and community control", "travel-vignette"),
  entry(9, "People and biography", "Nadia Designs for Repair", `Nadia began her career designing inexpensive kitchen appliances. Her employers praised low manufacturing costs, but repair shops complained that glued cases and uncommon screws made minor failures impossible to fix. Customers replaced entire machines when one switch wore out.

After joining a smaller company, Nadia proposed a modular mixer. Its motor, controls, cord, and shell could be separated with ordinary tools. Managers worried that easy repair would reduce new sales and make the product look bulky. She responded with a broader cost model that included warranty returns, material recovery, customer trust, and future rules on electronic waste.

The first version was not an instant success. Replacement parts were poorly labeled, and repair instructions assumed too much technical knowledge. Nadia invited independent technicians and home users to test the next design. Their feedback changed the connectors, diagrams, and parts-distribution system more than it changed the machine's appearance.

Her work reframed durability as an ongoing relationship rather than a claim printed on packaging. A repairable object required accessible parts, understandable information, and institutions willing to support it after the initial sale. Design continued long after the product left the factory.`, "product design and circular economy", "fictional-biography"),

  // Level 10
  entry(10, "Fantasy/stories", "The Parliament Beneath the Orchard", `The villagers discovered the parliament when an old apple tree fell, exposing a staircase braided from roots. Below the orchard, generations of seeds sat in crescent rows, each speaking for the plant it might become. Their debates were slow because no delegate could know whether it would germinate next spring or remain dormant for a century.

The human council had recently approved a reservoir that would drown the valley. Engineers promised replacement orchards on higher ground, but the underground parliament objected that an orchard was not a collection of interchangeable trees. Its soil contained fungi, insects, forgotten varieties, and the consequences of countless seasons of selection. The villagers dismissed this as botanical poetry until the seed delegates presented records: flavors no nursery sold, resistance to a disease not seen for eighty years, and family grafts preserved nowhere else.

Stopping the reservoir would leave neighboring towns vulnerable to drought. The seed parliament, despite its attachment to place, refused to pretend that memory outweighed thirst. It proposed a delay of three growing seasons. During that time, villagers mapped roots, gathered cuttings, moved soil in careful layers, and planted several new orchards instead of one symbolic replacement.

Some trees failed after the valley flooded. The surviving orchards differed from the original and from one another. At their first joint harvest, the human council asked whether the parliament had been saved. A young tree replied that preservation was the wrong measure. They had protected enough variety for the argument about what came next to continue.`, "ecology, memory, and collective choice", "narrative-fiction"),
  entry(10, "Nature and animals", "Rewilding Without an Imagined Past", `Rewilding is often described as allowing nature to manage itself, sometimes through the return of large animals or the restoration of natural processes. The phrase is appealing, but it raises an immediate question: which version of nature should guide the effort? Landscapes have long histories of climate shifts, human settlement, hunting, farming, fire, and species movement. Selecting a baseline can quietly privilege one period over another.

Projects that focus on processes rather than exact historical scenes attempt to address this problem. Their goals may include renewed grazing patterns, freer rivers, connected habitats, and ecosystems able to respond to future change. Large herbivores or predators can play important roles, yet introducing them also affects livelihoods, public safety, and existing conservation priorities.

Local participation is therefore more than a strategy for winning acceptance. Residents may hold practical knowledge about seasonal water, animal behavior, and land use that ecological models miss. At the same time, local preferences are not uniform; landowners, Indigenous communities, tourists, and younger residents may value the same landscape differently.

Rewilding succeeds poorly when it treats people as contamination or treats any animal release as restoration. A defensible project states its chosen goals, monitors unexpected effects, shares authority, and remains willing to revise its methods. The aim is not to recreate a frozen past, but to expand the capacity of ecological and human communities to live with change.`, "rewilding and environmental governance", "explanatory-nonfiction"),
  entry(10, "World affairs", "Debt Relief After the Cyclone", `After a cyclone destroyed roads, clinics, and crops, a heavily indebted country faced payments that consumed much of its emergency budget. Creditors offered new loans for reconstruction, but civil-society groups argued that borrowing to repair repeated climate damage would deepen a cycle the country had done little to create.

Suspending payments could release money quickly, yet it might also raise future borrowing costs or shift losses onto pension funds and other ordinary investors. Complete cancellation raised questions about which debts were legitimate, how relief should be shared among creditors, and whether funds would reach affected communities. A simple dispute between generous lenders and irresponsible borrowers failed to describe the network of contracts and unequal risks.

Negotiators adopted a package: immediate payment pauses triggered by disasters, partial reduction of older debt, grants for public infrastructure, and transparent reporting overseen by domestic and international groups. Some repayments would fall further if independently measured recovery targets were missed because of another extreme event.

The arrangement did not resolve the underlying injustice of countries facing climate losses beyond their fiscal capacity. It did, however, recognize that resilience cannot be built through finance that becomes least flexible at the moment of crisis. Effective relief joined accountability to room for recovery instead of treating them as opposing principles.`, "climate finance and disaster recovery", "explanatory-nonfiction"),
  entry(10, "Everyday life", "A Marriage Measured in Invisible Work", `When Inez and Paul argued about housework, both believed they were doing more than half. They listed visible tasks—cooking, cleaning, laundry, repairs—and assigned each an estimated number of hours. The spreadsheet reduced some disagreement but intensified another. Inez had included remembering vaccinations, noticing that soap was low, planning meals around allergies, and anticipating which relative needed a birthday call. Paul considered these thoughts too vague to count.

For one month, they recorded not only completed tasks but also who noticed, planned, and followed up. The exercise revealed that a five-minute appointment could depend on weeks of background attention. It also showed work Paul performed without naming it, such as monitoring the car and negotiating with service providers.

They resisted converting every act of care into a transaction. Instead, each took full responsibility for several domains, including the planning nobody saw. They scheduled a short weekly review and accepted that equal effort would not produce identical minutes during illness or demanding work periods.

The lasting change was epistemic as much as practical: they stopped assuming that unobserved labor did not exist. Fairness became a process of making responsibilities discussable, revising them as circumstances changed, and recognizing that attention itself can be work even when nothing appears on a finished checklist.`, "relationships and invisible labor", "narrative-fiction"),
  entry(10, "History", "The Archive Left by a Colonial Survey", `Colonial surveys measured land, classified populations, standardized place names, and translated complex systems of use into administrative categories. Their maps and tables can provide detailed evidence unavailable elsewhere, which makes them indispensable to many historians. The same precision, however, served taxation, military movement, resource extraction, and claims of political control.

Reading such an archive requires attention to both what it records and what its methods made difficult to see. Seasonal grazing may appear as empty land; overlapping rights may be reduced to a single owner; local names may be altered to fit an outsider's spelling system. Communities also responded strategically, withholding information, adapting categories, or using survey procedures to advance their own claims.

The archive's authority often survived the administration that produced it. Postcolonial governments inherited borders, property records, and statistical divisions that could stabilize public systems while continuing earlier exclusions. Correcting them was never as simple as discarding every map.

A critical historian therefore avoids two symmetrical errors: treating the survey as a neutral window onto the past, or treating it as useless because power shaped its creation. By comparing official records with oral histories, material evidence, local documents, and the survey's own contradictions, researchers can use the archive while keeping its conditions of production in view.`, "colonialism, mapping, and archives", "historical-narrative"),
  entry(10, "Science", "What a Model Means When It Fails", `Scientific models are deliberately incomplete representations. A climate model, epidemic model, or model of a protein keeps some relationships while simplifying others, allowing researchers to test consequences that cannot be isolated easily in the world itself. Its value therefore cannot be judged by asking whether it reproduces every detail.

Failure can take several forms. A prediction may miss because input data were poor, because a parameter changed, because an important process was omitted, or because the model was applied beyond the conditions for which it was designed. These causes have different implications. Adjusting a parameter may improve calibration, whereas adding complexity can reduce clarity or make the model fit past noise rather than future behavior.

Researchers evaluate models against observations not used to build them, compare multiple structures, and examine sensitivity to uncertain assumptions. They also ask whether the model is fit for a particular decision. A rough forecast may be adequate for choosing between broad strategies but unsafe for locating an individual evacuation route.

When a model fails, the honest response is neither blind defense nor wholesale rejection. The mismatch is evidence about both the model and the system. Progress comes from identifying which expectations were violated, revising the representation where justified, and communicating the boundaries within which its conclusions remain useful.`, "models, evidence, and uncertainty", "explanatory-nonfiction"),
  entry(10, "Famous books", "A Creature Asks for Responsibility", `Victor Frankenstein pursues the power to animate life, imagining glory in the achievement but giving little thought to the being who will awaken. The moment the creature opens its eyes, Victor recoils from the result and abandons it. His failure is not simply that he crossed a scientific boundary; it is that he refuses the responsibility created by his success.

The creature learns language and moral feeling by secretly observing a family. He approaches human society hoping that sympathy might overcome his appearance, only to meet fear and violence. Rejection does not make his later murders inevitable or innocent, but it shapes the grievance through which he justifies them. When he asks Victor to create a companion, he frames the request as both a right to relationship and a threat of revenge.

Victor destroys the unfinished companion, fearing a future population he cannot control. The decision may be prudent, yet he again acts alone and conceals the danger from those most exposed to it. Creator and creature become locked in reciprocal pursuit, each interpreting suffering as permission to inflict more.

The novel offers no simple verdict on knowledge. It asks what obligations follow creation, how isolation distorts judgment, and whether remorse without accountable action is morally sufficient. Victor's tragedy lies as much in failed care and secrecy as in forbidden ambition.`, "creation, responsibility, and isolation", "classic-retelling", "Frankenstein; or, The Modern Prometheus"),
  entry(10, "Mystery and adventure", "The Expedition That Reached Camp Twice", `Satellite messages from a desert expedition showed the team reaching its base camp on two consecutive evenings from opposite directions. The first arrival included a routine equipment report. The second carried an urgent request for water, although supplies should have been waiting at camp. Because the device transmitted valid coordinates and authentication codes, rescuers initially feared that one message had been forged.

Analyst Ren mapped the raw coordinates with their stated reference systems. The expedition's older receiver used one geodetic datum, while the new emergency platform assumed another. Normally the difference would shift a point only modestly, but a software conversion had also reversed latitude and longitude after a manual export. Two separate errors placed a remote waypoint almost exactly on the mapped camp.

The “first arrival” had actually come from the waypoint, where the team discovered its water cache damaged. The second message was the genuine arrival at base the following day. Both had entered the central log out of order because the older receiver waited for a satellite connection before sending stored reports.

Rescuers delivered water without further delay. Later, investigators resisted labeling the incident mere user error. The interface had accepted incompatible coordinate formats, displayed no transmission delay, and converted uncertain data into a precise-looking map. The mystery arose not from a single false statement but from several systems each concealing a different kind of ambiguity.`, "navigation and data mysteries", "mystery-fiction"),
  entry(10, "Travel and culture", "The Museum Returned to the Neighborhood", `A city museum occupied a former warehouse in a district whose residents had supplied much of its collection: factory tools, protest posters, family photographs, and recordings of migration stories. As property values rose, admission prices and polished exhibitions attracted visitors from elsewhere while long-term residents increasingly described the building as foreign territory.

The museum responded first with free local tickets, but use changed little. Community groups explained that access was not merely a question of price. Exhibition labels treated residents as historical subjects rather than present-day interpreters, events were scheduled for tourists, and donated objects could not easily be borrowed for neighborhood ceremonies.

A new agreement created a resident council with authority over part of the program and budget. The museum digitized records but also established procedures for temporary returns, contested descriptions, and withdrawal of culturally sensitive material. Curators worried that shared authority would weaken scholarly standards; residents replied that unexplained institutional control was itself a claim about expertise.

The resulting exhibitions contained more disagreement, not less. Labels sometimes presented several accounts side by side, making uncertainty visible. Visitor numbers alone could not measure success. The deeper change was that the museum ceased treating community participation as content supplied to an unchanged institution and began allowing the relationship to alter how the institution worked.`, "museums, memory, and community authority", "travel-vignette"),
  entry(10, "People and biography", "Elias and the Ethics of a Useful Forecast", `Elias developed crop forecasts for a cooperative serving thousands of small farms. His model combined weather observations, soil data, and satellite images to estimate planting dates and likely yields. Early trials improved decisions in ordinary years, and lenders began using the forecasts when setting credit terms.

That expansion troubled him. A tool designed to guide collective storage was now influencing which farmer received a loan. Fields with irregular boundaries or tree cover produced noisier satellite signals, so the system appeared less confident precisely where poorer farms were common. Some lenders treated uncertainty as evidence of risk rather than a limitation of measurement.

Elias persuaded the cooperative to separate advisory forecasts from eligibility decisions. Outputs included ranges and explanations of missing data, while farmers could challenge records through local offices. An independent group tested whether errors clustered by region, farm size, or land practice. The revised system sometimes withheld a prediction rather than presenting weak evidence as precision.

The change made the product less impressive in demonstrations, where a single number had looked authoritative. It made the forecast more useful in practice. Elias came to define accuracy not only as closeness to an eventual harvest, but also as honesty about who was visible to the model, how its results would be used, and what recourse existed when an estimate acquired power over a person's choices.`, "agricultural technology and data ethics", "fictional-biography"),
];

const stories = JSON.parse(fs.readFileSync(storyPath, "utf8"));
const baseStories = stories.filter((story) => {
  const match = /^s(\d+)$/.exec(String(story.id || ""));
  return match && Number(match[1]) <= 1610;
});
if (baseStories.length !== 1610) {
  throw new Error(`Expected the 1,610-story reviewed base, found ${baseStories.length}.`);
}
const existingIds = new Set(baseStories.map((story) => story.id));
const existingTitles = new Set(baseStories.map((story) => story.title));

if (entries.length !== 100) {
  throw new Error(`Expected 100 new entries, found ${entries.length}.`);
}

for (let level = 1; level <= 10; level += 1) {
  for (const topic of topics) {
    const count = entries.filter((story) => story.level === level && story.topic === topic).length;
    if (count !== 1) throw new Error(`Expected one entry for Level ${level} / ${topic}, found ${count}.`);
  }
}

const additions = entries.map((story, index) => {
  const id = `s${String(1611 + index).padStart(3, "0")}`;
  if (existingIds.has(id)) throw new Error(`ID already exists: ${id}`);
  if (existingTitles.has(story.title)) throw new Error(`Title already exists: ${story.title}`);
  return {
    id,
    level: story.level,
    topic: story.topic,
    title: story.title,
    text: story.text,
    wordCount: story.text.split(/\s+/).filter(Boolean).length,
    subtopic: story.subtopic,
    contentType: story.contentType,
    editorialStatus: "published",
    factChecked: false,
    reviewedAt: "2026-09-14",
    sourceWork: story.sourceWork,
    vocabularyVersion: "v2",
  };
});

fs.writeFileSync(storyPath, `${JSON.stringify([...baseStories, ...additions], null, 2)}\n`);
console.log(`Added or refreshed ${additions.length} stories: ${additions[0].id}-${additions.at(-1).id}`);
