'use strict';
const fs=require('fs'),path=require('path'),crypto=require('crypto');
const root=path.resolve(__dirname,'..'),read=p=>JSON.parse(fs.readFileSync(path.join(root,p),'utf8'));
const write=(p,v)=>fs.writeFileSync(path.join(root,p),JSON.stringify(v,null,2)+'\n');
const sha=s=>crypto.createHash('sha256').update(s).digest('hex');
const policy=require('../learning-policy'),gate=require('./review_release_gate');
const stories=read('stories.json'),reviews=read('content/review-progress.json'),prov=read('content/current-provenance.json'),audits=read('learning_audit_records.json');
const decisions={
 s884:{reason:'The surface-tension contrast explains why pepper moves away from the soapy contact point. “Skin” is identified as an analogy, and the closing line prevents interpreting it as pepper avoiding soap intentionally.',sources:['https://pubs.acs.org/doi/10.1021/ed400316a','https://www.acs.org/education/resources/k-8/science-activities/characteristicsofmaterials/soapdetergent.html']},
 s885:{reason:'Use starch rather than “hard parts,” identify ethylene by name, and say the bag may speed the banana’s ripening rather than promising both banana and apple ripen faster. Avoid a general cold-storage prescription.',text:'A green banana is firm and not very sweet. As it ripens, some of its starch turns into sugar. Its skin often turns yellow, and the fruit becomes softer.\n\nRipening fruit gives off a gas called ethylene. A paper bag holds some of that gas near the fruit. A banana in a bag with an apple may ripen faster than one left on the table.\n\nThe banana may look still, but changes are taking place inside it.',sources:['https://extension.oregonstate.edu/sites/extd8/files/2023-08/pnw612.pdf','https://www.ars.usda.gov/research/publications/publication/?seqNo115=142687']},
 s886:{reason:'The cup-and-string example correctly connects voice, cup vibration and taut string. The Exploratorium confirms the string needs to vibrate freely; clarify this instead of saying the sound has a “clear path” without explanation.',text:'Mina and Jo made a telephone from two paper cups and a long string. They made a hole in each cup and tied the string inside.\n\nJo held one cup and walked across the room. When the string was tight, Mina spoke into her cup. Her voice made the cup shake a little. The movement traveled along the string and made Jo’s cup shake too. Jo heard her words.\n\nWhen they let the string hang loose or touched it in the middle, the sound became hard to hear. The string had to move freely.',sources:['https://annex.exploratorium.edu/science-explorer/ear_guitar.html']},
 s1021:{reason:'The old clues never explain how the notebook returns. Let Xena follow the wet, leafy pages to the student who borrowed the rehearsal notebook, and acknowledge water damage.',text:'The theater group could not find its rehearsal notebook. Xena asked who had used it last. A student said he had taken it outside to practice by the river.\n\nXena walked the path with him. Under a bench, they found the notebook. Its pages were wet, and dry leaves stuck to the cover. The student had left it there when rain began.\n\nThey took it back to the theater and spread the pages to dry. Xena wrote down where the group would keep the notebook next time.',subtopic:'everyday investigation'},
 s1022:{reason:'The old “missing whistle” is a sound made by an air pipe, not an object that can be recovered, and the market title contradicts the bakery. Make the noise a specific loose window shutter with a testable cause.',title:'The Bakery Whistle',text:'Each evening, a whistle sounded in Eli’s bakery after he closed the door. He looked for a toy whistle but found none.\n\nOn a windy day, Eli stood still and listened. The sound came from a narrow gap beside a window. When he pressed the loose shutter against the frame, the sound stopped. He let it go, and the whistle returned.\n\nEli asked a repair worker to fix the shutter. The next evening the bakery was quiet. The wind made the sound as it moved through the gap.',subtopic:'everyday investigation'},
 s1024:{reason:'The original dates do not explain the missing seed box. A note on the shelf leads Pia to a worker who moved the seeds before rain; the box is found in a dry room.',text:'Pia helped sort seeds in an orchard shed. One morning, the wooden box of spring seeds was gone. A note lay on its shelf: “Move the seeds before rain.”\n\nPia asked the farm workers about the note. One worker said she moved the box to a dry room when a storm came. She forgot to tell the others where she put it.\n\nPia went to the room and found the box beside the planting tools. They added the room’s name to the note on the shed door.',subtopic:'everyday investigation'},
 s1025:{reason:'The mask never goes missing in the old passage; light only changes its expression, and the post office setting has no role. Focus on a theater mask that seems to smile under a second lamp.',title:'The Mask’s Changing Smile',text:'At the theater, Nia hung a mask on the wall. During practice, its mouth seemed to smile. When she came back after lunch, it looked sad. No one had touched it.\n\nNia asked the stage worker to turn off one lamp. The shadow below the mouth moved, and the smile returned. When the worker turned the lamp on again, a new shadow made the same mouth look different.\n\nThe mask had not changed. Nia marked the lamp positions so the actors could choose the look they wanted.',subtopic:'theater mystery'},
 s1026:{reason:'A radio in a museum and a walking group “trying a help signal” leave the object’s route unexplained. Make it a missing loan radio at a trail station and use the signed loan list as a real clue.',title:'The Trail Radio',text:'Noah helped at a mountain trail station. One of the loan radios was missing from its shelf. He checked the list beside the door. A walking group had signed for it that morning but had not marked it as returned.\n\nNoah called the group leader. She said the group was back safely and the radio was in her bag. She brought it to the station that afternoon.\n\nNoah checked that it worked, then wrote its return time on the list.',subtopic:'outdoor adventure'},
 s1027:{reason:'“A window words” is ungrammatical and words cannot be both gone and safe. Put the writing on a bakery pane where warm steam reveals older finger marks on a cold morning.',title:'Words on the Bakery Window',text:'Ivan cleaned the bakery window before closing. The glass looked clear. The next cold morning, a few words appeared on it: “Bread is ready.”\n\nIvan asked the baker if anyone had written there. She said a child had traced those words on the glass the week before. The marks became hard to see when the pane was dry.\n\nIvan breathed gently on one corner. Water from his breath made another old letter appear. He wiped the pane again and watched the words fade as it dried.',subtopic:'everyday investigation'},
 s1028:{reason:'A heavy farm gate cannot disappear into a room. Show its open position, a hair caught near the hook and a donkey lifting the loose latch. End with the farmer securing it.',text:'Gus found the apple farm’s gate standing open. He had shut it the evening before. In the loose hook, he saw a short gray hair. The farm’s old donkey stood nearby.\n\nGus watched from a distance. The donkey pushed the hook up with its nose and opened the gate. Gus called the farmer and showed her what he had seen.\n\nShe moved the donkey to a safe field and asked a worker to fit a latch it could not lift. The next morning the gate stayed shut.',subtopic:'farm mystery'},
 s1029:{reason:'A high pin on the music roll explains a changed note, not a missing music box. Center the mystery on the extra note and confirm it with a prior repair record.',title:'The Music Box’s Extra Note',text:'Uma turned the handle of her grandmother’s music box. The tune had one high note she did not remember. She opened the lid and saw a small new pin on the roll inside.\n\nHer grandmother found a note from a repair shop. Years ago, a worker had replaced a broken pin but put the new one a little higher. That change made the high sound.\n\nUma played the tune again. Now she could hear where the extra note came from, and she decided to keep it.',subtopic:'everyday investigation'},
 s1030:{reason:'Moonlight on wet white seeds is a reflection, not a missing “lake light” that can be returned. Use a moving reflection of a path lamp, confirmed by changing viewpoint.',title:'The Moving Lake Light',text:'Sara saw a bright spot move across the lake after dark. There was no boat on the water. She called her brother to look.\n\nThey walked along the shore. From one place the spot looked far away. From another it lay beside a line of small waves. Sara noticed a lamp on the path behind them. When her brother stood in front of it, the bright spot grew dim.\n\nThe lamp’s light was reflecting from the moving water. The lake had no lamp of its own.',subtopic:'outdoor investigation'},
 s1031:{reason:'Fine metal dust alone does not establish that a compass is missing. Center the actual fault on a needle that points the wrong way and compare its direction after moving it away from a magnet.',title:'The Compass That Pointed West',text:'At the old mill, Sora found a compass pointing the wrong way. She carried it outside. The needle moved, but it still pointed oddly when she brought it near a box of tools.\n\nInside the box lay a small magnet. Sora put the magnet farther away and tested the compass again. Its needle now settled toward north.\n\nThe mill worker had stored the compass beside the magnet. Sora marked a new shelf for it. She checked the direction with a second compass before trusting it.',subtopic:'everyday investigation'},
 s1032:{reason:'A blue mark at an unrelated door does not lead to a stage worker’s key. Make the blue tape on the key ring match the hook in the next room, then verify with the worker.',text:'June helped set up a school play. The key to the costume room was missing from its hook. A blue piece of tape lay below the hook. June knew the key ring had blue tape on it.\n\nShe asked the stage worker if he had used the room. He had, and he thought he had hung the key up afterward. They looked in the room where he carried the costumes. The key was on a hook there, with its tape partly torn.\n\nThey returned it to the costume room and put a label beside its usual hook.',subtopic:'theater mystery'},
 s1033:{reason:'A branch touching the bell rope can keep the bell from ringing but cannot make the bell itself “not where it should be.” Show the stuck rope and have a maintenance worker clear it.',title:'The Silent School Bell',text:'The school bell did not ring at noon. Hana went to the clock tower with a teacher. From the doorway, they saw that a branch had caught the bell rope after the night’s wind.\n\nThe teacher called the school’s maintenance worker. He closed the area, cleared the branch and checked the rope. Then he rang the bell once to test it.\n\nThe worker asked everyone to keep away from the tower until he finished. The bell rang at the next break.',subtopic:'school mystery'},
 s1034:{reason:'The violin was moved from rain, but a string by a chair does not reveal its location. Show a damp floor near the window and ask the student who had carried it to a dry cupboard.',text:'Vera helped arrange music at the old school. A red violin was missing from its place beside the window. Rain had blown onto the floor there.\n\nShe asked the students who had used the room. One said she had seen the rain and moved the violin into a cupboard before it got wet. Vera opened the cupboard and found it in its case.\n\nThe teacher checked the instrument. It was dry. Together they chose a safer shelf away from the window.',subtopic:'school mystery'},
 s1035:{reason:'Flour on a high shelf in a lost-property office does not explain where a recipe book went. Place the book in the community kitchen, use a flour handprint on the dry cupboard, and ask the cook.',text:'The recipe book was missing from the community kitchen table. Cal noticed a flour handprint on the door of a high cupboard.\n\nHe asked the cook if she had moved anything. She said rain had blown in through the open window while she worked. With flour on her hand, she had put the book in the dry cupboard.\n\nCal found it there, away from the wet table. He closed the window and put the book on a shelf the cooks could all reach.',subtopic:'everyday investigation'},
 s1036:{reason:'A square mark by itself cannot locate a thin ticket under a calendar. Show a visible ticket corner and let Ari lift the calendar to confirm, without a stock “safe again” line.',text:'Ari was helping at an art gallery. A silver ticket for the next show was missing from the desk. A paper calendar lay where the ticket lay earlier.\n\nAri noticed a small silver corner showing beneath the calendar. She lifted it and found the ticket. Someone had set the calendar down after looking at the show dates.\n\nAri put the ticket in a marked folder. The next worker could find it without searching the desk.',subtopic:'everyday investigation'},
 s1037:{reason:'New stones by a pond suggest a path project, but the old story never says where the missing map went. Have Nia ask the gardener and inspect the marked map in the tool shed.',text:'Nia came to help visitors find their way around a garden. The map was missing from its board. Near the pond, she saw new stones laid in a curve.\n\nShe asked the gardener if the path was changing. He showed her the map in the tool shed. He had taken it down to draw the new path but had forgotten to leave a note.\n\nTogether they checked the route. Then the gardener put the updated map back on the board.',subtopic:'everyday investigation'},
 s1038:{reason:'The station office has no connection to a museum coin, and sunlight cannot return a missing coin. Make a museum display seem to contain two coins because a glass pane reflects one; changing angle verifies it.',title:'The Second Museum Coin',text:'Lina helped at a museum. In a glass case, she saw what looked like two bright coins. The list beside the case said there was only one.\n\nLina called the curator. They looked from the side and saw a single coin on its stand. A second image appeared in the glass behind it when the lights were on.\n\nThe curator turned one lamp off. The extra image faded. Lina left the coin where it was and changed the light so visitors could see the display clearly.',subtopic:'museum mystery'}
};
const batch=[];
for(const [id,d] of Object.entries(decisions)){
 const s=stories.find(x=>x.id===id),p=prov.find(x=>x.id===id),a=audits.find(x=>x.id===id);
 if(!s||!p||!a||a.errors||s.level!==2||reviews.some(x=>x.id===id))throw Error('Unexpected source '+id);
 const before=structuredClone(s);
 if(d.title)s.title=d.title;
 if(d.text){s.text=d.text;s.wordCount=policy.countWords(s.text)}
 if(d.contentType)s.contentType=d.contentType;
 if(d.subtopic)s.subtopic=d.subtopic;
 if(d.topic)s.topic=d.topic;
 const changed=Boolean(d.title||d.text||d.contentType||d.subtopic||d.topic);
 if(changed){s.reviewedAt='2026-09-25';const check=policy.inspect(s);if(check.errors.length)throw Error('Learning policy '+id+': '+JSON.stringify(check));p.text_sha256=sha(s.text);p.status='editorial-revision-2026-09-25';p.evidence='content/editorial-batch-2.11.9p.json#'+id;p.note=d.reason;}
 batch.push({id,level:s.level,title:s.title,before,after:structuredClone(s),changed,reason:d.reason,sources:d.sources||[],review:'Individual full-text reading for language, source fidelity, logical order, level fit and fiction scope; AI-assisted editorial',beforeFlags:a.flags});
 reviews.push({id,contentDigest:gate.reviewDigest(s),language:'approved',facts:'approved',method:'AI-assisted-editorial',reviewedAt:'2026-09-25',note:d.reason,evidence:'content/editorial-batch-2.11.9p.json#'+id,warningDisposition:a.flags?`The ${a.flags} flag was evaluated in the complete text. ${d.reason}`:`No automatic flags. Full text checked. ${d.reason}`,origin:'editorial-batch-2.11.9p'});
}
reviews.sort((a,b)=>Number(a.id.slice(1))-Number(b.id.slice(1)));
write('stories.json',stories);write('content/current-provenance.json',prov);write('content/review-progress.json',reviews);write('content/editorial-batch-2.11.9p.json',batch);
console.log('Reviewed',batch.length,'changed',batch.filter(x=>x.changed).map(x=>x.id).join(','));
