'use strict';
const fs=require('fs'),path=require('path'),crypto=require('crypto');
const root=path.resolve(__dirname,'..'),read=p=>JSON.parse(fs.readFileSync(path.join(root,p),'utf8'));
const write=(p,v)=>fs.writeFileSync(path.join(root,p),JSON.stringify(v,null,2)+'\n');
const sha=s=>crypto.createHash('sha256').update(s).digest('hex');
const policy=require('../learning-policy'),gate=require('./review_release_gate');
const stories=read('stories.json'),reviews=read('content/review-progress.json'),prov=read('content/current-provenance.json'),audits=read('learning_audit_records.json');
const decisions={
 s1617:{reason:'The Peter Rabbit retelling follows garden, lost clothes, gate and home in the original. Change “warm tea” to the book’s chamomile tea, without presenting it as medical advice.',text:'Peter goes into a garden. He eats green plants, but Mr. McGregor sees him. Peter runs fast. He loses his shoes and coat. At last, he gets under the gate. Peter is tired when he reaches home. His mother puts him to bed and gives him chamomile tea.',sources:['https://www.gutenberg.org/files/14838/14838-h/14838-h.htm']},
 s1619:{reason:'Nora gets off the boat, meets the baker and uses pointing and smiling to buy bread despite a language gap. The order is clear and the town is not asserted as a specific real location.'},
 s1620:{reason:'Lena keeps screws sorted, studies the unfamiliar toy and repairs it. The sign “Small Things Welcome” follows from her successful repair and fits a fictional biography.'},
 s1712:{reason:'Bat Conservation International describes the assistance of dropping from a high roost before flight. This piece follows one bat and avoids saying every bat needs to fall; classify the scene as fictional animal narrative.',contentType:'narrative-fiction',sources:['https://www.batcon.org/where-the-upside-is-down/']},
 s1713:{reason:'The town hall’s three steps and a new ramp are a fictional town episode. Show a qualified worker designing and installing it, then describe specific users instead of informal volunteers building a public access structure.',contentType:'narrative-fiction',text:'The town hall has three steps. Some people cannot get inside easily. The town asks a building worker to plan a ramp. The worker checks the space and makes a plan. Other workers build the ramp and test it. On Friday, it opens. People who use wheelchairs can now enter by the ramp. Parents with baby strollers use it too.'},
 s1715:{reason:'Clay tablets with reed marks and records of goods are an explanatory overview supported by museum collections. Change the type from historical narrative to nonfiction explanation.',contentType:'explanatory-nonfiction',sources:['https://www.metmuseum.org/art/collection/search/327384']},
 s1716:{reason:'NASA confirms that the Moon reflects sunlight and that orbital geometry changes the sunlit portion visible from Earth. The simple language avoids implying the Moon generates light.',sources:['https://science.nasa.gov/moon/moon-phases/']},
 s1717:{reason:'In Heidi, Clara visits the mountain and learns to stand and walk with help. Preserve that literary event without treating mountain air itself as a medical cure.',sources:['https://www.gutenberg.org/cache/epub/1448/pg1448-images.html']},
 s1719:{reason:'Eli buys soup, sits near the harbor and sees a man gesture toward sunset. Explain that the man offers his own bread so “shares” is not read as taking Eli’s food.',text:'Eli walks beside a small harbor. People bring in their fishing boats. A woman sells warm soup from a stand. Eli buys a bowl and sits on a low wall. He does not know anyone there. An old man sits nearby. The man points to the sunset and offers Eli a piece of his bread. Eli thanks him.'},
 s1720:{reason:'Road markings and sign placement need town approval; let Pia collect observations and have road staff plan and paint. Do not guarantee all drivers slow, and show a follow-up when rain covers part of the crossing.',text:'Pia works near a school. Cars move fast on the road. She asks families where children cross. Pia shares their answers with the town road team. The team plans new signs and a crossing. Workers paint it after the plan is checked. Pia watches how people use it. When rain covers one part, she asks the team to look at that place again.'},
 s1812:{reason:'Smithsonian describes pollen carried between flowers and the role in making seeds. “Yellow dust” is immediately defined as pollen and the wording says “can help” rather than guaranteeing seed formation.',sources:['https://naturalhistory.si.edu/events/festivals-and-event-series/pollinators-plants']},
 s1813:{reason:'The story explicitly says it is made up, and lunch space does not explain eating “before class.” Classify it as fiction, keep the meal at lunchtime and avoid claiming one farm can supply all food indefinitely.',contentType:'narrative-fiction',text:'This school is made up. It has too little room for lunch. Some children bring food, and some do not. Teachers and families talk to the town. The town helps pay for a larger lunch room. Cooks plan simple meals. One farm sells some vegetables to the school. At lunch, children can sit and eat together.'},
 s1815:{reason:'The British Museum documents the 1799 discovery and three-script decree. Say the same message appears in three scripts instead of an ambiguous “same order.”',text:'A large old stone was found in Egypt in 1799. One message was written on it in three scripts. One script was ancient Greek. People could still read Greek, so it helped them study the other signs. The stone became an important key to reading ancient Egyptian writing.',sources:['https://www.britishmuseum.org/exhibitions/hieroglyphs-unlocking-ancient-egypt/egyptian-hieroglyphs-decipherment-timeline']},
 s1816:{reason:'The tree’s shadow changes with the apparent position of the Sun as Earth turns. Short sentences and “near noon” are adequate for a simple daylight observation.'},
 s1817:{reason:'The original Secret Garden has Mary’s buried key, robin, Dickon and Colin. The retelling’s physical garden and change in the children follow the novel’s major events.',sources:['https://www.gutenberg.org/files/17396/17396-h/17396-h.htm']},
 s1819:{reason:'The town is explicitly imaginary and the girl acts during rain before sharing a meal. Make the soup purchase explicit so the cook’s relation to the girl is not left as an unexplained gift.',text:'Moon Bay is not a real town. A girl walks by its small boats. Rain starts, and she runs under a food tent. She buys a bowl of hot bean soup. Then she helps the cook move chairs out of the rain. When the sun comes back, they sit down and eat together.'},
 s1820:{reason:'A fictional biography needs an identifiable subject. Name Rosa, show a park worker checking the gate with visitors and replacing the hard handle, but avoid claiming it is accessible to everyone from one test.',title:'Rosa Fixes the Park Gate',text:'Rosa works at a town park. The gate is hard to open. A parent with a small child asks her for help. Rosa checks the gate and asks a worker to fix its metal parts. They move the handle to a place the parent can reach. A few visitors try the gate. It opens more easily for them. Rosa plans to ask other visitors what they think too.'},
 s1913:{reason:'The town is explicitly imaginary. Label the episode as fiction and make the accessibility solution legible through route names and large type, not only color choices.',contentType:'narrative-fiction',text:'This town is not real. Its bus map is hard to read. Riders ask for bigger words and clear route names. The town makes a new map. Every route has a name as well as a color. A larger print version is available too. More riders can use the map to find a bus.'},
 s1916:{reason:'The USGS shows water from a plant collecting as drops inside a bag around leaves. The text explains transpiration and uses “may” for the visible result.',sources:['https://www.usgs.gov/media/images/experiment-shows-result-plant-transpiration']},
 s1917:{reason:'Another reviewed Peter Rabbit piece already covers his garden escape. Keep this retelling on a distinct original scene: Peter hides in a watering can, sneezes and is discovered. This also avoids labeling tea as treatment.',title:'Peter Hides in the Watering Can',text:'Peter Rabbit runs from Mr. McGregor. He goes into a shed and jumps into a watering can. There is water inside it. Peter gets very wet. Then he sneezes. Mr. McGregor hears the sound and runs toward the can. Peter jumps out and runs away. He still needs to find the garden gate.',sources:['https://www.gutenberg.org/files/14838/14838-h/14838-h.htm']}
};
const batch=[];
for(const [id,d] of Object.entries(decisions)){
 const s=stories.find(x=>x.id===id),p=prov.find(x=>x.id===id),a=audits.find(x=>x.id===id);
 if(!s||!p||!a||a.errors||s.level!==1||reviews.some(x=>x.id===id))throw Error('Unexpected source '+id);
 const before=structuredClone(s);
 if(d.title)s.title=d.title;
 if(d.text){s.text=d.text;s.wordCount=policy.countWords(s.text)}
 if(d.contentType)s.contentType=d.contentType;
 const changed=Boolean(d.title||d.text||d.contentType);
 if(changed){s.reviewedAt='2026-09-24';const check=policy.inspect(s);if(check.errors.length)throw Error('Learning policy '+id+': '+JSON.stringify(check));p.text_sha256=sha(s.text);p.status='editorial-revision-2026-09-24';p.evidence='content/editorial-batch-2.11.9k.json#'+id;p.note=d.reason;}
 batch.push({id,level:s.level,title:s.title,before,after:structuredClone(s),changed,reason:d.reason,sources:d.sources||[],review:'Individual full-text reading for language, source fidelity, logical order, Level 1 fit and fiction scope; AI-assisted editorial',beforeFlags:a.flags});
 reviews.push({id,contentDigest:gate.reviewDigest(s),language:'approved',facts:'approved',method:'AI-assisted-editorial',reviewedAt:'2026-09-24',note:d.reason,evidence:'content/editorial-batch-2.11.9k.json#'+id,warningDisposition:a.flags?`The ${a.flags} flag was evaluated in the complete text. ${d.reason}`:`No automatic flags. Full text checked. ${d.reason}`,origin:'editorial-batch-2.11.9k'});
}
reviews.sort((a,b)=>Number(a.id.slice(1))-Number(b.id.slice(1)));
write('stories.json',stories);write('content/current-provenance.json',prov);write('content/review-progress.json',reviews);write('content/editorial-batch-2.11.9k.json',batch);
console.log('Reviewed',batch.length,'changed',batch.filter(x=>x.changed).map(x=>x.id).join(','));
