'use strict';
const fs=require('fs'),path=require('path'),crypto=require('crypto');
const root=path.resolve(__dirname,'..'),read=p=>JSON.parse(fs.readFileSync(path.join(root,p),'utf8'));
const write=(p,v)=>fs.writeFileSync(path.join(root,p),JSON.stringify(v,null,2)+'\n');
const sha=s=>crypto.createHash('sha256').update(s).digest('hex');
const policy=require('../learning-policy'),gate=require('./review_release_gate');
const stories=read('stories.json'),reviews=read('content/review-progress.json'),prov=read('content/current-provenance.json'),audits=read('learning_audit_records.json');
const decisions={
 s617:{reason:'Fatima apologizes directly and sends the late card. The friend’s response supports the modest lesson about an imperfect but continuing friendship.'},
 s618:{reason:'A generic unnamed gadget and unspecified mistakes make the lesson hard to picture. Use a simple hand juicer with a clear error and correction, retaining the three tries.',subtopic:'learning everyday tasks',text:'Marcus got a hand juicer for his birthday. He wanted to make fresh orange juice. On his first try, he forgot to put a cup under it. Juice ran over the table.\n\nHe cleaned the table and read the guide again. On his second try, the cup was in place, but he pressed the orange too quickly and spilled some juice.\n\nOn his third try, he went slowly. He filled two cups and shared one with a friend. Now he knows how to use the juicer.'},
 s637:{reason:'Bertram and his town are declared invented, so classify as fiction. “Before towns had papers or radio” wrongly implies a universal sequence; frame it as one town before a local printed paper became common. Avoid guaranteeing trust from volume alone.',contentType:'narrative-fiction',subtopic:'town news long ago',text:'This story is made up. It is set in a town long ago.\n\nBertram worked as a town crier. He walked through the streets and called out news about market days and town rules. His voice was loud enough for people nearby to hear.\n\nAfter many years, more people began to read the town’s printed paper. Bertram had less news to call out. When he stopped working, his neighbors thanked him for the years he had spent sharing the news.'},
 s657:{reason:'Ice crystals melt as heat moves into ice cream. Fat and air also shape the texture, but “frozen water and fat begin to turn into liquid” overstates a single simple phase change. Use a level-appropriate account of lost shape.',text:'Ice cream stays firm when it is very cold. It contains tiny pieces of ice and pockets of air.\n\nOutside the freezer, heat moves from the warmer air into the ice cream. The ice begins to melt, and the soft mixture loses its shape. On a hot day, this often happens faster than on a cool day.\n\nThat is why ice cream can drip from a cone. Keeping it cold slows the change.'},
 s658:{reason:'Roots take up water with dissolved minerals, not “food from the soil”; plants make food using light. Remove the promise that water alone guarantees continuing growth.',text:'Plants take in water through their roots. Tiny root hairs help them take up water from the soil. The water can carry minerals that the plant needs.\n\nWater moves up the stem through very small tubes and reaches the leaves. Some water leaves the plant through tiny holes in the leaves. This helps draw more water upward.\n\nLeaves use light to help make food for the plant. Water is important, but plants also need light and other things to grow.',sources:['https://www.usgs.gov/water-science-school/science/evapotranspiration-and-water-cycle','https://www.usgs.gov/water-science-school/science/capillary-action-and-water']},
 s677:{reason:'The four aging animals travel toward Bremen but stop at the robbers’ house and stay there, as in the Grimm tale. The stack and noise clearly cause the thieves to flee.',sources:['https://www.gutenberg.org/cache/epub/2591/pg2591-images.html']},
 s678:{reason:'Collodi’s Talking Cricket warns Pinocchio; Pinocchio angrily throws a hammer. The current ending invents an immediate lesson and turns the scene into a moral conclusion. End with his refusal and consequence in the actual episode, in restrained language.',text:'Geppetto made a wooden boy and called him Pinocchio. One day, Pinocchio heard a small voice in the room. It came from a Talking Cricket.\n\n“Listen to your father and go to school,” the cricket told him. Pinocchio did not want to hear this. He wanted to play all day.\n\nThe cricket warned that leaving home without a plan could bring trouble. Pinocchio became angry. He picked up a wooden hammer and threw it at the cricket. The cricket fell silent.\n\nPinocchio was alone in the room. He still did not know what he would do next.',sources:['https://www.gutenberg.org/files/500/500-h/500-h.htm']},
 s709:{reason:'The tree’s tiny room and overnight branch are magical fiction. Replace a comparative claim about all river trees with an observable later change.',text:'Leo often walked past an old tree near the river.\n\nOne afternoon, he noticed a tiny door in the trunk. It was no higher than his knee. He opened it and saw a small room with a table, a chair, and a lamp.\n\nOn the table lay a letter. It said, “If you are reading this, please water the tree.”\n\nLeo carried a bucket of water from the river and poured it around the roots. The next day, the door was gone. A new green branch grew from the trunk.\n\nLeo never saw the little room again. He liked to sit in the shade of that tree.'},
 s710:{reason:'The grandmother’s warning, bell, barking dogs and white fox are a coherent fantasy sequence. The final restraint follows Mina’s experience.'},
 s711:{reason:'Jun is a named character who changes a gardening habit; classify as fiction and use a frog-and-garden label. More frogs and fewer pests follow in this imagined garden, without a broad guarantee for all gardens.',contentType:'narrative-fiction',subtopic:'frogs in gardens',text:'After a week of rain, Jun found a green frog near his garden pond. At night, he heard it call. His father said frogs often live near wet places and eat small insects.\n\nJun asked his father about the garden spray they sometimes used. Together they decided to stop using it near the pond. They also left some plants by the water.\n\nA month later, Jun saw two frogs there. He watched them without touching them. The garden was home to more than the vegetables his family grew.'},
 s712:{reason:'Cats can move their ears to locate sounds, and ear position may help indicate mood. Qualify any reading of fear or irritation because ears alone do not tell the whole state.',text:'A cat can turn its ears toward a sound. Small muscles help the ears move. If a noise comes from behind a chair, the cat may turn an ear before it turns its head.\n\nCats use their ears while they hunt and while they rest at home. The position of their ears can also give us clues about how they feel. Ears facing forward may show interest. Ears held back can be a sign of fear or discomfort.\n\nLook at the cat’s whole body too. Its ears alone do not tell us everything.'},
 s713:{reason:'The two towns and their agreement are an invented worked example, not reporting a particular real river dispute. Explicitly label the fiction and classify it as a narrative.',contentType:'narrative-fiction',text:'These two towns are made up. They use water from the same river.\n\nDuring a dry summer, farmers in one town want more water for their fields. The other town needs water for homes and shops. Their leaders meet and agree to measure the river each week. Farmers change some watering times. The second town repairs leaking pipes.\n\nNeither town gets everything it wants, but both use less water. When rain returns, they decide to keep checking the river together.'},
 s714:{reason:'The city, meetings and negotiated market move are a specific invented episode. Label it as fiction and remove the absolute claim that a consultation always works better; show this group’s mixed outcome.',contentType:'narrative-fiction',text:'This city is made up. It has a busy street market where people sell food and clothes. The city wants to move it into a new building. Some sellers worry about fees and fewer customers.\n\nAt meetings, the sellers ask for lower fees and a bus stop nearby. The city agrees to lower the fees and asks the bus team to look at the route.\n\nAt first, the new market is quiet. More customers come later. Some sellers like the indoor space; others still miss the street. The city plans another meeting to hear what is working.'},
 s715:{reason:'The wrong bus, helpful rider and return trip are coherent. Relabel the subtopic as transport and routines rather than work responsibility.',subtopic:'transport and routines'},
 s718:{reason:'This is a general explanation, not a historical narrative. Distinguish Viking longships used for carrying crews from other ships used for trade; verify narrow design, sail and oars against the Viking Ship Museum.',contentType:'explanatory-nonfiction',text:'Viking longships were long and narrow. They could carry a crew across the sea. Sailors used a sail when there was useful wind. They could also row when the wind was weak.\n\nTheir shape helped them move quickly. Some could travel near coasts and into shallow water. Viking people also used other kinds of ships to carry goods for trade.\n\nLongships helped crews travel far from home, sometimes to raid other places. Their design and the sailors’ skills both mattered.',sources:['https://www.vikingeskibsmuseet.dk/en/professions/education/the-longships/findings-of-longships-from-the-viking-age','https://www.vikingeskibsmuseet.dk/en/visit-the-museum/exhibitions/the-five-viking-ships/skuldelev-2']},
 s719:{reason:'The water-attracting and oil-attracting ends of soap molecules explain the removal of oily dirt, while rubbing and rinsing matter. CDC supports soap and friction lifting grease and microbes.',sources:['https://www.cdc.gov/clean-hands/data-research/facts-stats/index.html']},
 s720:{reason:'NASA confirms reflected sunlight and phases. Clarify that we see different portions of the lit half as the Moon orbits Earth; do not imply sunlight always lights a changing fraction of the Moon.',text:'The Moon does not make its own visible light. We see it because sunlight reaches it and reflects toward Earth.\n\nThe Sun lights about half the Moon at a time. As the Moon moves around Earth, we see different portions of that lit half. Sometimes the bright part looks like a thin curve. At other times, we see a full Moon.\n\nThe Moon is still round when it looks like a curve. Its changing appearance is called a phase. The phases follow a regular pattern.',sources:['https://science.nasa.gov/moon/moon-phases/']},
 s721:{reason:'The wish sequence, roughening sea and return to the first small home follow the Grimm tale. The wife’s final request is generalized as power over everything for this level.',sources:['https://www.gutenberg.org/cache/epub/2591/pg2591-images.html']},
 s722:{reason:'Andersen’s story ends with the girl dying on the cold street and imagining her grandmother. The current piece stops before that crucial ending and describes only reader lessons. Restore the outcome in gentle direct language.',text:'On a cold winter night, a poor girl walked through the streets selling matches. She was afraid to go home without money.\n\nShe sat in a corner and lit a match to warm her hands. For a moment, she saw a bright fire. When the match went out, the fire was gone. With another match, she saw food on a table.\n\nThen she saw her grandmother, who was always kind to her. The girl lit more matches, hoping her grandmother would stay.\n\nIn the morning, people found the girl. She had died in the cold. They did not know about the warm things she had seen in her last moments.',sources:['https://www.gutenberg.org/files/1597/1597-h/1597-h.htm']},
 s862:{reason:'The flying, size-changing boat is the magical object and the lake is Tom’s visible route home. Correct the non-existent “window” and the creature subtopic.',subtopic:'magical objects and transformations',text:'On the night of the full moon, Tom found a silver boat on the lake. It was small enough to hold in one hand. When he touched it, the boat grew as long as his house.\n\nTom climbed in. The boat rose from the water and sailed into the sky. It passed quiet birds and a sleeping cloud. Soon the Moon filled the sky ahead.\n\nTom worried that he might not find his way home. Then he saw the lake below, bright like a coin. He turned the boat toward it. By morning, the silver boat was small again, and Tom kept it beside his bed.'}
};
const batch=[];
for(const [id,d] of Object.entries(decisions)){
 const s=stories.find(x=>x.id===id),p=prov.find(x=>x.id===id),a=audits.find(x=>x.id===id);
 if(!s||!p||!a||a.errors||s.level!==2||reviews.some(x=>x.id===id))throw Error('Unexpected source '+id);
 const before=structuredClone(s);
 if(d.title)s.title=d.title;
 if(d.text){s.text=d.text;s.wordCount=policy.countWords(s.text)}
 if(d.contentType)s.contentType=d.contentType;
 if(d.subtopic)s.subtopic=d.subtopic;
 if(d.topic)s.topic=d.topic;
 const changed=Boolean(d.title||d.text||d.contentType||d.subtopic||d.topic);
 if(changed){s.reviewedAt='2026-09-24';const check=policy.inspect(s);if(check.errors.length)throw Error('Learning policy '+id+': '+JSON.stringify(check));p.text_sha256=sha(s.text);p.status='editorial-revision-2026-09-24';p.evidence='content/editorial-batch-2.11.9n.json#'+id;p.note=d.reason;}
 batch.push({id,level:s.level,title:s.title,before,after:structuredClone(s),changed,reason:d.reason,sources:d.sources||[],review:'Individual full-text reading for language, source fidelity, logical order, level fit and fiction scope; AI-assisted editorial',beforeFlags:a.flags});
 reviews.push({id,contentDigest:gate.reviewDigest(s),language:'approved',facts:'approved',method:'AI-assisted-editorial',reviewedAt:'2026-09-24',note:d.reason,evidence:'content/editorial-batch-2.11.9n.json#'+id,warningDisposition:a.flags?`The ${a.flags} flag was evaluated in the complete text. ${d.reason}`:`No automatic flags. Full text checked. ${d.reason}`,origin:'editorial-batch-2.11.9n'});
}
reviews.sort((a,b)=>Number(a.id.slice(1))-Number(b.id.slice(1)));
write('stories.json',stories);write('content/current-provenance.json',prov);write('content/review-progress.json',reviews);write('content/editorial-batch-2.11.9n.json',batch);
console.log('Reviewed',batch.length,'changed',batch.filter(x=>x.changed).map(x=>x.id).join(','));
