'use strict';
const fs=require('fs'),path=require('path'),crypto=require('crypto');
const root=path.resolve(__dirname,'..'),read=p=>JSON.parse(fs.readFileSync(path.join(root,p),'utf8'));
const write=(p,v)=>fs.writeFileSync(path.join(root,p),JSON.stringify(v,null,2)+'\n');
const sha=s=>crypto.createHash('sha256').update(s).digest('hex');
const policy=require('../learning-policy'),gate=require('./review_release_gate');
const stories=read('stories.json'),reviews=read('content/review-progress.json'),prov=read('content/current-provenance.json'),audits=read('learning_audit_records.json');
const decisions={
 s863:{reason:'The century-long sleep and flying dragon are openly fantastical. June brings milk after the dragon comes out, and the concluding flight resolves his waking.'},
 s864:{reason:'The magical pocket is an enchanted place with a tiny bird, not principally a magical creature. The seasonal green trees belong to fantasy and the caretaking actions are consistent.',subtopic:'enchanted places'},
 s865:{reason:'Correct “pirates went by boat the sea,” and include the fairy dust needed for Wendy and her brothers to fly in Barrie’s work. Keep the invitation and shadow episode.',text:'Wendy was getting ready for bed when Peter Pan came through the window. He had lost his shadow. Wendy found it and sewed it back to his foot.\n\nPeter told her about Neverland, where there were pirates and children who could fly. “Come with me,” he said. Wendy wanted her brothers, John and Michael, to come too.\n\nPeter said they could all go. He blew fairy dust over the children and told them to think happy thoughts. Soon they rose into the air and followed him through the night.',sources:['https://www.gutenberg.org/cache/epub/26654/pg26654-images.html']},
 s866:{reason:'In Twain’s story the guard expels Edward in Tom’s poor clothes while Tom remains inside in princely dress; correct the swapped identification and keep the later empathy cautiously stated.',text:'Tom lived in a poor part of London. Edward was a prince who lived in a palace. The boys looked very much alike.\n\nWhen they met, they tried on each other’s clothes. Edward went out to speak to a guard. The guard saw his poor clothes, thought he was Tom, and pushed him away from the palace. Tom was left inside in Edward’s fine clothes.\n\nEach boy faced a life he did not know. Tom had to act like a prince. Edward saw how hard life could be for poor people. Later, they found a way to tell the truth about who they were.',sources:['https://www.gutenberg.org/files/1837/1837-h/1837-h.htm']},
 s867:{reason:'Anne first meets Diana at Diana’s home and the girls vow friendship in the Barry garden. Replace the invented Diana visit and stream path with this actual scene.',text:'Anne was new to Green Gables. Marilla took her to meet a girl named Diana, who lived nearby.\n\nDiana’s mother sent the girls into the garden. At first, they stood quietly among the flowers. Then Anne began to talk. She had hoped for a close friend and wondered if Diana might like her.\n\nDiana listened and smiled. Before they went home, the girls promised to be friends. Anne had come to Green Gables by mistake, but now she had someone to share her days with.',sources:['https://www.gutenberg.org/files/45/45-h/45-h']},
 s868:{reason:'Porter’s book has the bare attic room, Pollyanna’s joy in its window view, and the glad game. The supplied rain scene and aunt opening curtains are invented; stay with the attested scene.',text:'Pollyanna came to live with her aunt. Her aunt gave her a small room under the roof. It had bare walls and no picture. Pollyanna felt sad at first.\n\nThen she went to the window. Outside, she could see trees and the land beyond them. “This is my picture,” she thought. She opened the window and felt the fresh air.\n\nPollyanna played a game of finding something to be glad about, even on a hard day. She still missed the things she had wanted for her room. But she was glad to have its view.',sources:['https://www.gutenberg.org/files/1450/1450-h/1450-h.htm']},
 s869:{reason:'Specify sea otters; stone tools and underarm pockets are documented. Remove the claim that hand-holding is the general safety mechanism and end with an observed rest among kelp. The piece remains a composite explanatory scene, without individual names.',title:'Sea Otters at Play',text:'Two young sea otters swam beside a rocky shore. One chased the other through the water. Then an otter floated on its back and held a shell against its chest.\n\nSome sea otters use a stone to break a hard shell. They can keep food in loose skin under their front legs while they swim.\n\nLater, the two otters rested near floating kelp. Their play and their search for food were different parts of a day at sea.',sources:['https://www.montereybayaquarium.org/animals-the-ocean/animals-a-to-z/sea-otter','https://www.usgs.gov/media/audio/what-you-otter-know-about-sea-otters-part-1']},
 s870:{reason:'Smithsonian supports wind-carried dandelion seeds. Replace “kids” as an anthropomorphic description of the new plants and avoid implying every seed in good conditions germinates.',text:'A dandelion grows a white, round head after its yellow flower is gone. Each soft part carries a seed.\n\nWhen the wind blows, the seeds can rise into the air. Their light tops work like little umbrellas. Some fall close to the old plant. Others travel across a road or over a wall.\n\nMany seeds never grow. A few may land where they have enough water and light. New plants can grow there. This is one way a plant spreads its seeds without moving itself.',sources:['https://gardens.si.edu/exhibitions/traveling/habitat/spreading-their-seeds/']},
 s871:{reason:'A talking bird and explicit lesson make this an animal fable rather than nonfiction marine biology. Correct classification and subtopic, and make the second bird’s later catch visible instead of asserting an unshown total.',contentType:'narrative-fiction',subtopic:'herons and fishing',text:'A heron stood still beside a river. Small fish moved near its legs, but it waited.\n\nAnother bird flew down and caught a little fish. “You are too slow,” it called.\n\nThe heron watched the water. At last, a larger fish swam close. The heron moved its head quickly and caught it.\n\nThe other bird came back with another small fish. Both birds had found food, though they had waited and moved in different ways.'},
 s872:{reason:'River Town and its expanding shelf are specific fictional events, not a documented library report. Mark the story as fiction and identify the language access subtopic.',contentType:'narrative-fiction',subtopic:'community languages'},
 s873:{reason:'The families and village response to flood form an invented event. Make the fictional scope explicit; the smaller harvest and shared food do not promise every family enough rice.',contentType:'narrative-fiction',text:'This village is made up. Heavy rain covers its rice fields. When the water goes down, many young plants are gone.\n\nFarmers meet in the school hall. One family has extra seed. Another lends a machine to prepare the fields. People from a village on higher ground bring food while the farmers work.\n\nThey plant again, though the season is already late. The harvest is smaller than usual. Families share what they can and talk about how to prepare for another flood.'},
 s874:{reason:'An invented island project should be fiction. A route away from one fishing ground does not prove ecological protection, and an undersea cable does not guarantee steady supply. Show consultation and backup without claiming zero impact.',contentType:'narrative-fiction',text:'This island is made up. It gets electricity from an old machine that needs fuel brought by ship. Storms sometimes delay the ships.\n\nThe island and a coastal town plan a cable under the sea. Engineers study where it might go. Fishers explain which places they use most, and the team changes part of its plan.\n\nAfter the cable is ready, the island can get power from the coast. It keeps the old machine for times when the cable cannot be used. People continue to watch how the new route affects fishing.'},
 s875:{reason:'Overseas voting rules vary by country, and delivery confirmation does not prove a ballot was accepted. Present Lina’s example as fictional and distinguish mailing from the count.',contentType:'narrative-fiction',text:'This election story is made up. Lina lives abroad but can vote by mail under her home country’s rules. She reads the instructions and puts her ballot in the required envelopes.\n\nLina sends it early and checks the letter’s delivery number. It reaches the election office before the deadline. She knows it must still be checked with the other ballots.\n\nOn election night, Lina calls her mother. They watch the results together, even though they live far apart.'},
 s876:{reason:'Emi and Mr. Ito discover they exchanged similar umbrellas and mark the handles before returning to their routines. The sequence is clear and self-contained.'},
 s877:{reason:'The volunteer repair table includes electrical and bicycle brake work that requires skill and safety checks. Narrow to a sewing volunteer, a trained electrician and a bike mechanic, and make the old clock’s repair plausible.',text:'Every Saturday, people brought broken things to a table outside the community hall. Mrs. Chen sewed torn bags. Omar, a trained electrician, checked lamps. A bicycle mechanic looked at brakes. They could not fix everything.\n\nOne boy brought a small clock that had belonged to his grandfather. A clock repairer at the table opened it and found a loose part. She fixed it, then tested the clock.\n\nWhen it began to tick, the boy held it close to his ear. He remembered hearing that sound in his grandfather’s house.'},
 s879:{reason:'Kai uses vegetables and beans in a plausible improvised soup. Specify cooked beans so the short preparation does not imply that dry beans become safe to eat after a brief simmer.',text:'Kai planned to cook soup, but he had forgotten to buy carrots. In the kitchen he found an onion, half a pumpkin, two tomatoes, and a can of cooked beans.\n\nHe cut up the vegetables and put them in a pot with the beans. The soup looked too thick, so he added water. It tasted flat, so he added salt and a little lemon.\n\nHis sister came home and asked for a bowl. “What kind is it?” she said.\n\nKai had no answer. The soup had no recipe and no name, but they both asked for more.'},
 s880:{reason:'This particular town and daily shared-oven process are not documented, although large medieval ovens existed. Mark it clearly as a fictional historical setting, keep the bread marks as a story detail, and correct its subtopic.',contentType:'narrative-fiction',subtopic:'shared bread oven',text:'This story is made up. It is set in a town long ago. Many families there use the same large bread oven.\n\nOne morning, each family makes its dough at home. They press a small mark on their loaves so they can tell them apart. A baker helps place the bread in the hot oven.\n\nLater, people return for their loaves. Neighbors talk while they wait. The oven belongs to the town, and this is the day they bake together.',sources:['https://historicengland.org.uk/listing/the-list/list-entry/1418336']},
 s881:{reason:'This explains iron gall ink ingredients and darkening over time; it is general nonfiction, not a dated narrative. Correct content type and subtopic. Oak galls arise after insects lay eggs and “iron salt” is better described simply as iron compound for this level.',contentType:'explanatory-nonfiction',subtopic:'iron gall ink',text:'People once made writing ink from small round growths on oak trees. Insects help make these growths, called oak galls.\n\nAn ink maker could soak broken galls in water. Then the maker mixed the liquid with an iron compound and a little tree gum. The ink often grew darker after it touched the air.\n\nWriters used this kind of ink for letters and records. The materials in the ink helped their words remain on paper for a long time.',sources:['https://www.metmuseum.org/ja/perspectives/materials-and-techniques-drawing-ink']},
 s882:{reason:'The keeper’s daughter and one storm are a fictional adventure. Fog bells can help give an audible warning but do not ensure every ship’s safe arrival; label fiction and end with one crew hearing the warning.',contentType:'narrative-fiction',subtopic:'harbor and fog',text:'This story is made up. A bell hangs above a small harbor. In thick fog, the tower keeper rings it so sailors know the shore is near.\n\nOne winter night, the rope breaks. His daughter hears a ship far out in the fog. She goes up the tower stairs with her father. He uses a hammer to ring the bell while she holds a lamp.\n\nThe sailors hear the sound and slow down. They wait for the fog to lift before coming into the harbor. The daughter helps her father carry the lamp home.'},
 s883:{reason:'These villagers and their well-maintenance plan are an invented local event rather than dated history. Mark fiction and replace a claimed water-quality outcome with the visible repair of its cover.',contentType:'narrative-fiction',subtopic:'community well',text:'This village is made up. Families share a well, so they make a plan to care for it. Each spring, workers check the stones and the wooden cover.\n\nOne year, several families move away. There are fewer people to help. The village agrees that each home can give time or money for the work. Some neighbors bring lunch for the workers.\n\nBy evening, the cover is repaired. The families plan to check it again the next spring.'}
};
const batch=[];
for(const [id,d] of Object.entries(decisions)){
 const s=stories.find(x=>x.id===id),p=prov.find(x=>x.id===id),a=audits.find(x=>x.id===id);
 if(!s||!p||!a||a.errors||s.level!==2||reviews.some(x=>x.id===id))throw Error('Unexpected source '+id);
 const before=structuredClone(s);
 if(d.title)s.title=d.title;
 if(d.text){s.text=d.text;s.wordCount=policy.countWords(s.text)}
 if(d.contentType)s.contentType=d.contentType;
 if(d.subtopic)s.subtopic=d.subtopic;
 if(d.topic)s.topic=d.topic;
 const changed=Boolean(d.title||d.text||d.contentType||d.subtopic||d.topic);
 if(changed){s.reviewedAt='2026-09-25';const check=policy.inspect(s);if(check.errors.length)throw Error('Learning policy '+id+': '+JSON.stringify(check));p.text_sha256=sha(s.text);p.status='editorial-revision-2026-09-25';p.evidence='content/editorial-batch-2.11.9o.json#'+id;p.note=d.reason;}
 batch.push({id,level:s.level,title:s.title,before,after:structuredClone(s),changed,reason:d.reason,sources:d.sources||[],review:'Individual full-text reading for language, source fidelity, logical order, level fit and fiction scope; AI-assisted editorial',beforeFlags:a.flags});
 reviews.push({id,contentDigest:gate.reviewDigest(s),language:'approved',facts:'approved',method:'AI-assisted-editorial',reviewedAt:'2026-09-25',note:d.reason,evidence:'content/editorial-batch-2.11.9o.json#'+id,warningDisposition:a.flags?`The ${a.flags} flag was evaluated in the complete text. ${d.reason}`:`No automatic flags. Full text checked. ${d.reason}`,origin:'editorial-batch-2.11.9o'});
}
reviews.sort((a,b)=>Number(a.id.slice(1))-Number(b.id.slice(1)));
write('stories.json',stories);write('content/current-provenance.json',prov);write('content/review-progress.json',reviews);write('content/editorial-batch-2.11.9o.json',batch);
console.log('Reviewed',batch.length,'changed',batch.filter(x=>x.changed).map(x=>x.id).join(','));
