'use strict';
const fs=require('fs'),path=require('path'),crypto=require('crypto');
const root=path.resolve(__dirname,'..'),read=p=>JSON.parse(fs.readFileSync(path.join(root,p),'utf8'));
const write=(p,v)=>fs.writeFileSync(path.join(root,p),JSON.stringify(v,null,2)+'\n');
const sha=s=>crypto.createHash('sha256').update(s).digest('hex');
const policy=require('../learning-policy'),gate=require('./review_release_gate');
const stories=read('stories.json'),reviews=read('content/review-progress.json'),prov=read('content/current-provenance.json'),audits=read('learning_audit_records.json');
const decisions={
 s1918:{reason:'The street and town are declared imaginary. The bakery exchange and shared food proceed in a clear order; no factual claim about a destination is implied.'},
 s1919:{reason:'The subject is explicitly fictional; the worker replaces a crowded sign with shorter words and pictures. Qualify the outcome as applying to the children who try the signs rather than promising independent access to every child.',text:'This sign maker is not a real person. A park sign has too many words. Children do not know which way to go. The worker asks what they need. He makes short signs with big letters and simple pictures. The children can now find the garden and the rest room more easily. The worker watches them try the signs and asks if anything is still hard to find.'},
 s334:{reason:'The magical event and its one-day limit are clear. Lowercase said after exclamation marks in dialogue tags.',text:`Tomás found an old hat in his grandmother's closet. The hat was blue and had a small star on it.\n\nHe put the hat on his head. Suddenly, a little bird flew out of the hat!\n\n"Wow!" said Tomás. He put the hat on again. This time, a small flower appeared in his hand.\n\nTomás was excited. He wanted to show his friends. He ran outside with the magic hat.\n\nHis friend Ana was playing near the tree. Tomás put on the hat again. A soft red ball rolled out onto the grass.\n\n"This hat is magic!" said Ana. They both laughed and played with the new things all afternoon.\n\nThat evening, Tomás put the hat back in the closet. He smiled, thinking about tomorrow's surprises.\n\nThe next day, he put the hat on again. But nothing happened. The magic hat was quiet now.\n\nTomás was not sad. He said, "Thank you, hat, for one wonderful day."\n\nHe kept the hat safe, hoping the magic would return again someday.`},
 s335:{reason:'Correct a capitalized dialogue tag and replace the small owl sheltering a child across town with an actionable warning about rain; preserve their friendship and the talking-owl premise.',text:`Every morning, Lily walked past a big tree on her way to school. One day, she heard a small voice.\n\n"Hello down there!" said the voice. Lily looked up. A small owl was sitting on a branch.\n\n"Can you talk?" asked Lily, very surprised.\n\n"Yes," said the owl. "My name is Oliver. I live in this tree."\n\nLily stopped to talk with Oliver before school. He told her stories about the forest. She told him about her classroom and her friends.\n\nOne morning, Oliver saw dark clouds. "Rain is coming," he said. Lily had left her umbrella at home. She ran back to get it before school.\n\nWhen the rain began, Lily stayed dry. That afternoon, she thanked Oliver for the warning.\n\nThey kept sharing stories by the tree. Years later, Lily still remembered her first friend there.`},
 s336:{reason:'The magic crown is explicitly part of the fantasy; the boy notices fatigue, asks the animals and stops ordering them. Dialogue and resolution are coherent.'},
 s347:{reason:'A named ant makes choices and learns a lesson in a fictional scene, so classify this as animal fiction and label its ant subject rather than plants or fungi.',contentType:'narrative-fiction',subtopic:'ants and cooperation'},
 s348:{reason:'This is a named-bee episode, so classify it as animal fiction. Foraging honey bee workers are female; use she, identify nectar and explain that pollen on the body can reach another flower instead of asserting a guaranteed seed outcome.',contentType:'narrative-fiction',subtopic:'bees and pollination',text:'A small bee named Buzz flew over a garden. She looked for nectar, a sweet drink from flowers. She landed on a yellow flower and drank.\n\nPollen, a fine powder, stuck to her body. Buzz did not notice it. She was busy collecting food for the bees at home.\n\nNext, she flew to another flower. Some pollen from the first flower touched it. This can help a flower make seeds.\n\nAt the end of the day, Buzz went back to her hive with food. She had visited many flowers too.',sources:['https://extension.psu.edu/bees-in-pennsylvania-diversity-ecology-and-importance','https://naturalhistory.si.edu/events/festivals-and-event-series/pollinators-plants']},
 s358:{reason:'The town is expressly invented, so mark it fiction. A fish farm needs continuing work and cannot guarantee food in rough seas or safety for everyone; make the outcome conditional and specific.',contentType:'narrative-fiction',text:'This seaside town is made up. Many people there catch fish for work. One year, they find fewer fish near the coast. Some families worry about food and money.\n\nAt a town meeting, people discuss a small fish farm. They ask a fish farmer for help choosing a place and caring for the fish. After several months, the farm has its first fish to sell.\n\nIt gives some families another way to earn money. The town holds a meal for everyone who helped. They know they will need to keep caring for the farm.'},
 s359:{reason:'Mia and the farmer take part in an explicitly made-up market episode. Correct the content type to fiction; the basket exchange and return next week are clear.',contentType:'narrative-fiction'},
 s360:{reason:'Daniel and Amir are characters in an expressly made-up neighbors story. Change the content type to fiction; the shared game supplies a concrete language-learning moment.',contentType:'narrative-fiction'},
 s370:{reason:'Mr. Chen approaches the unfamiliar dog cautiously, reads its tag and phones the owner. The return follows from that call, and the text fits the level.'},
 s371:{reason:'Remove the unqualified “safe knife” claim and awkward “closely to the pot”; tighten repeated dialogue and let the father cut vegetables while Sara helps with lower-risk tasks.',text:'Sara helped her father make vegetable soup. He washed the carrots and cut them into small pieces. Sara put them in a bowl.\n\n"Can I add the carrots?" she asked.\n\n"Yes. I will hold the pot," her father said. He put in potatoes and water too. Soon the kitchen smelled good.\n\nSara stirred the soup while her father watched. He added a little salt and some herbs. When the vegetables were soft, he poured the soup into bowls. Sara set the table.\n\n"This is good," she said as they ate. She was glad they had made dinner together.'},
 s372:{reason:'Use “might have fallen” for an uncertain past event and end with a practical habit, without predicting he never loses the key again.',text:'Ben came home from school but could not find his house key. He looked through his bag. Then he sat on the front step and thought about his day.\n\nHe had stopped at the park to tie his shoe. The key might have fallen there. Ben went back and looked near the bench. Soon he saw something bright in the grass. It was his key.\n\nBen put it in his bag. At home, his mother tied it to a bright red string. Ben chose a pocket for it so he would know where to look next time.'},
 s382:{reason:'The story states it is invented and offers no dated or named historical event. Reclassify the village bridge episode as fiction; maintenance after years follows its construction.',contentType:'narrative-fiction'},
 s383:{reason:'The family is part of an explicitly fictional past setting. Classify as fiction and use a subtopic about seasonal village work instead of war and social change.',contentType:'narrative-fiction',subtopic:'seasonal village life'},
 s384:{reason:'The town and its first train are made up. Change the content type and subtopic; narrow the outcome to some farmers and families rather than implying universal benefit.',contentType:'narrative-fiction',subtopic:'rail travel and town life',text:'This story is made up. It is not about a real person or event.\n\nMany years ago, a small town learned that a train line was coming. Many people there had never seen a train.\n\nWorkers spent months laying tracks across the fields. On the first day of service, a crowd waited at the new stop.\n\nThey heard a loud call from far away. Then a black train came toward them with white steam in the air. Children cheered as it stopped.\n\nIn the months that followed, some farmers used the train to take food to a city. Some families used it to visit people farther away. The town had a new way to travel.'},
 s394:{reason:'Official sleep guidance supports the limited claims about attention, memory and differing needs. The bedtime routine is framed as something that can help, not a guaranteed cure.',sources:['https://www.nhlbi.nih.gov/health/sleep-deprivation/health-effects']},
 s395:{reason:'The sun-warmed evaporation, condensation and rain sequence matches the USGS water-cycle explanation; the cyclic return is understandable at this level.',sources:['https://water.usgs.gov/edu/watercycle-kids-beg.html']},
 s396:{reason:'Limit leaf fall to many deciduous trees, distinguish existing yellow/orange pigments from red pigment formed in some leaves, and use the relevant tree-and-season subtopic.',subtopic:'trees and seasonal change',text:'Many trees grow green leaves in spring. The leaves use sunlight to help make food for the tree. A green material called chlorophyll helps them do this.\n\nIn fall, days grow shorter. In some trees, the green color breaks down. Yellow and orange colors that were already in the leaves become easier to see. Some leaves also make a red color.\n\nThe tree begins to close the place where each leaf joins a branch. A leaf can then fall. In winter, the tree has no leaves to keep warm or supply with water. New leaves may grow in spring.',sources:['https://www.fs.usda.gov/Internet/FSE_DOCUMENTS/stelprd3817419.pdf']},
 s406:{reason:'The text presents an adapted fable with an ant, a grasshopper, seasonal food and a gentler sharing ending. It is correctly marked as classic retelling, and the choices are clear.'}
};
const batch=[];
for(const [id,d] of Object.entries(decisions)){
 const s=stories.find(x=>x.id===id),p=prov.find(x=>x.id===id),a=audits.find(x=>x.id===id);
 if(!s||!p||!a||a.errors||![1,2].includes(s.level)||reviews.some(x=>x.id===id))throw Error('Unexpected source '+id);
 const before=structuredClone(s);
 if(d.title)s.title=d.title;
 if(d.text){s.text=d.text;s.wordCount=policy.countWords(s.text)}
 if(d.contentType)s.contentType=d.contentType;
 if(d.subtopic)s.subtopic=d.subtopic;
 const changed=Boolean(d.title||d.text||d.contentType||d.subtopic);
 if(changed){s.reviewedAt='2026-09-24';const check=policy.inspect(s);if(check.errors.length)throw Error('Learning policy '+id+': '+JSON.stringify(check));p.text_sha256=sha(s.text);p.status='editorial-revision-2026-09-24';p.evidence='content/editorial-batch-2.11.9l.json#'+id;p.note=d.reason;}
 batch.push({id,level:s.level,title:s.title,before,after:structuredClone(s),changed,reason:d.reason,sources:d.sources||[],review:'Individual full-text reading for language, source fidelity, logical order, level fit and fiction scope; AI-assisted editorial',beforeFlags:a.flags});
 reviews.push({id,contentDigest:gate.reviewDigest(s),language:'approved',facts:'approved',method:'AI-assisted-editorial',reviewedAt:'2026-09-24',note:d.reason,evidence:'content/editorial-batch-2.11.9l.json#'+id,warningDisposition:a.flags?`The ${a.flags} flag was evaluated in the complete text. ${d.reason}`:`No automatic flags. Full text checked. ${d.reason}`,origin:'editorial-batch-2.11.9l'});
}
reviews.sort((a,b)=>Number(a.id.slice(1))-Number(b.id.slice(1)));
write('stories.json',stories);write('content/current-provenance.json',prov);write('content/review-progress.json',reviews);write('content/editorial-batch-2.11.9l.json',batch);
console.log('Reviewed',batch.length,'changed',batch.filter(x=>x.changed).map(x=>x.id).join(','));
