'use strict';
const fs=require('fs'),path=require('path'),crypto=require('crypto');
const root=path.resolve(__dirname,'..'),read=p=>JSON.parse(fs.readFileSync(path.join(root,p),'utf8'));
const write=(p,v)=>fs.writeFileSync(path.join(root,p),JSON.stringify(v,null,2)+'\n');
const sha=s=>crypto.createHash('sha256').update(s).digest('hex');
const policy=require('../learning-policy'),gate=require('./review_release_gate');
const stories=read('stories.json'),reviews=read('content/review-progress.json'),prov=read('content/current-provenance.json'),audits=read('learning_audit_records.json');
const decisions={
 s857:{reason:'The woman, cart, well and journey make one invented old-market scene. Reclassify from historical narrative to fiction so the episode is not presented as a documented event.',contentType:'narrative-fiction'},
 s858:{reason:'NASA confirms that Polaris identifies north in the Northern Hemisphere; keeping it left is consistent with an eastward course. Name that setting and mark this particular voyage as invented.',contentType:'narrative-fiction',text:'A sailor stood on a ship at night. He was in the Northern Hemisphere and wanted to sail east. He found the North Star. It showed him where north was. He kept that star to his left as the ship moved through the night. At sunrise, he saw land ahead. The star had helped him keep his course.',sources:['https://science.nasa.gov/solar-system/what-is-the-north-star-and-how-do-you-find-it/']},
 s859:{reason:'The USGS confirms ice is less dense than liquid water. “Lighter than the same amount” confuses mass with volume; explain that the same weight takes up more space when frozen.',text:'Put an ice cube in a glass of water. It floats at the top. Ice is frozen water. When water freezes, it takes up more space. The same weight of ice is spread through more space than liquid water. That is why ice can float. In a cold winter, a lake may freeze on top while there is still liquid water below.',sources:['https://www.usgs.gov/water-science-school/science/water-density']},
 s860:{reason:'The tree stays in place as the apparent Sun position changes over a sunny day. The morning, middle and evening observations explain the moving shadow without presenting an invented experiment as historical fact.'},
 s861:{reason:'Seeds generally need oxygen as well as water and warmth, but a submerged seed is not guaranteed to fail because water can contain dissolved oxygen. Replace the absolute two-jar result with a qualified explanation of too much water.',text:'A bean seed needs water and warmth to grow. It also needs air. Put a seed in wet soil, and it may start to grow. But too much water can fill the spaces where air would be. Then the seed may not get enough air. A seed is alive. It needs both water and air as a new plant begins to grow.',sources:['https://extension.psu.edu/starting-seeds']},
 s1311:{reason:'Replace generic collaborative boilerplate with Maya’s distinct mapping problem, interviews and resulting route map; use she consistently and keep the outcome local to this fictional project.',title:'Maya Maps the River',text:'Maya Chen wanted to make a map for boats on a river. One old map showed a path that was no longer safe. Maya spoke with boat workers. They showed her where the water was deep and where it was not. She marked their notes on a new map. A boat worker tried it and found one part that was wrong. Maya fixed that part. The map became more useful with each trip.'},
 s1312:{reason:'Jon is one person, so replace unexplained they with he. Give the bike-repair story a concrete broken part, lesson and outcome rather than the repeated “small idea can grow” ending.',title:'Jon Fixes a Bike',text:'Jon Bell opened a small bike shop. One morning, a worker came in with a broken wheel. Jon showed her how to take it off and put it back on. She watched carefully and then tried it herself. The next week, she came by to help a friend fix a bike. Jon was glad his shop could help people learn, not only sell repairs.'},
 s1313:{reason:'Name Amina in the text, use she, and describe seed labels and sharing without promising that any saved seed guarantees crops in dry years.',title:'Amina Saves Seeds',text:'Amina Okafor kept seeds from the farms near her town. One family brought her beans that they had grown for years. Amina put the seeds in a dry bag and wrote the family’s name on it. In spring, she shared some with two neighbors. They planted them and kept some seeds from the new plants. Now more families could try growing those beans.'},
 s1314:{reason:'Give teacher Luis an adult learner and a concrete reading task; replace ungrounded claim that several students became teachers with one student helping a newcomer.',title:'Luis Opens an Evening Class',text:'Luis Ortega taught reading after work. His students often arrived tired. One evening, he brought a bus sign and a short note from a shop. They read the words together. Maria practiced the note on the way home. A month later, a new student joined the class. Maria sat beside him and helped him read the bus sign.'},
 s1315:{reason:'Replace the repeated abstract summary with a repairable toy, a customer return and a clear result for Hana’s small shop.',title:'Hana Makes a Toy to Fix',text:'Hana Mori made wooden toys in her small shop. A boy brought back a toy car with a loose wheel. Hana showed him how the wheel fit on. Then she made her next cars with parts that were easy to change. When a wheel came loose again, the boy knew what to do. He came to the shop to tell Hana that his car was moving once more.'},
 s1316:{reason:'Use Samir consistently and keep clinical tasks with the village clinic rather than implying untrained helpers give medical care. The result is scheduling and communication, not a blanket health outcome.',title:'Samir Plans a Clinic Visit',text:'Samir Patel worked with a village clinic. In heavy rain, the road to one village was hard to use. Samir asked families when they could meet the clinic nurse. He wrote down their answers and planned a visit for a clear day. A local helper told the families when the nurse would arrive. When the day came, the nurse met them at the village hall.'},
 s1317:{reason:'Elena’s garden needs a visible response to poor ground. Specify raised beds with better soil and a small community use; remove generic growth formula.',title:'Elena Builds Garden Beds',text:'Elena Rossi wanted a garden near the town school. The ground was hard, and little grew there. Elena and two families built low wooden beds and filled them with soil. Children planted beans in one bed. They came back each week to water them. When the first green leaves appeared, the children showed them to their parents.'},
 s1318:{reason:'Identify David as the radio worker instead of omitting him; describe batteries and a concrete storm message while avoiding a guarantee of universal communication.',title:'David Keeps the Radio On',text:'David Kim helped at a small town radio station. When storms cut the power, the station went quiet. David kept a radio and spare batteries in a safe place. During the next storm, he used the radio to share a short message about the road to town. Some families heard it and knew which road to avoid until the weather cleared.'},
 s1319:{reason:'Name Nora, use she and show permission to share personal stories. A small reading room is a concrete, respectful result of the fictional project.',title:'Nora Listens to the Town',text:'Nora Hassan liked to hear older workers talk about the town. She asked if she could write down their stories. Some said yes, and some wanted to keep their memories private. Nora respected both answers. She put the stories she could share in a small room at the library. On opening day, one worker read her own words aloud.'},
 s1320:{reason:'Show Peter responding to winter meal costs with a specific planning choice, without claiming that the arrangement solves all nutrition and waste issues.',title:'Peter Plans Winter Lunch',text:'Peter Walsh helped plan meals at a school. Fresh food cost more in winter. He asked a local farmer what food the school could buy that month. They chose carrots and potatoes for a warm lunch. Peter wrote a simple plan for the cooks. At lunch, he asked the children what they liked. Their answers helped him plan the next week.'},
 s1321:{reason:'The source uses repeated “beginning” sentences and unclear team pronouns. Make Inez’s clay test a clear sequence with the farmer’s permission and one finished pot.',title:'Inez Finds New Clay',text:'Inez Silva made clay pots by a river. A storm washed away the clay she used. She asked a farmer inland if she could try clay from his field. Inez made one small pot and let it dry. It broke in the fire, so she changed the mix and tried again. The next pot held water. She wrote down what she had done.'},
 s1322:{reason:'A bridge check concerns safety; clarify that Omar works with a qualified engineer rather than treating informal checks as proof a bridge is safe. Keep the repair record concrete.',title:'Omar Finds the Bridge Notes',text:'Omar Reed kept records for three small bridges. One winter, he could not find the old repair notes. He asked a bridge engineer to check the bridges. Omar wrote down what the engineer found and where work was needed. Then he made a new file for each bridge. Before the next storm, the town could see which repairs to plan first.'},
 s1323:{reason:'Keiko is missing from the original story. Name her and show how families help create language-accessible stories, without claiming a story swap alone solves the book shortage.',title:'Keiko Makes Room for More Stories',text:'Keiko Tan worked at a town library. Most books there were in one language. She asked families what they wanted to read together. Some parents brought short stories in the languages they used at home. Keiko helped put them in a small book for the library. At story time, children heard a new story from an older family member.'},
 s1324:{reason:'Mateo’s path-rotation idea needs a concrete sign and visible result; avoid saying the entire forest is now safe on the basis of one change.',title:'Mateo Moves a Forest Path',text:'Mateo Cruz guided walks in a forest. One path went over small new plants. Mateo made a sign and showed visitors another way through the trees. He checked the closed path each week. After a time, he saw more leaves there. On his next walk, he told the group why that part of the forest needed a rest.'},
 s1325:{reason:'The original suggests making unverified engine parts for use at sea. Replace that safety concern with ordering correct spare parts and checking repairs on land; give Sara a distinct action and outcome.',title:'Sara Keeps the Right Parts',text:'Sara Lind repaired boat engines near a harbor. When a part broke, fishers sometimes had to wait many days for a new one. Sara made a list of parts that broke often. She ordered the right parts for the engines she knew and kept them at the shop. One morning, a fisher came with a broken engine. Sara fitted the correct part and tested the engine on land before the boat went out.'}
};
const batch=[];
for(const [id,d] of Object.entries(decisions)){
 const s=stories.find(x=>x.id===id),p=prov.find(x=>x.id===id),a=audits.find(x=>x.id===id);
 if(!s||!p||!a||a.errors||s.level!==1||reviews.some(x=>x.id===id))throw Error('Unexpected source '+id);
 const before=structuredClone(s);
 if(d.title)s.title=d.title;
 if(d.text){s.text=d.text;s.wordCount=policy.countWords(s.text)}
 if(d.contentType)s.contentType=d.contentType;
 const changed=Boolean(d.title||d.text||d.contentType);
 if(changed){s.reviewedAt='2026-09-24';const check=policy.inspect(s);if(check.errors.length)throw Error('Learning policy '+id+': '+JSON.stringify(check));p.text_sha256=sha(s.text);p.status='editorial-revision-2026-09-24';p.evidence='content/editorial-batch-2.11.9i.json#'+id;p.note=d.reason;}
 batch.push({id,level:s.level,title:s.title,before,after:structuredClone(s),changed,reason:d.reason,sources:d.sources||[],review:'Individual full-text reading for language, logic, level, source and fictional framing; AI-assisted editorial',beforeFlags:a.flags});
 reviews.push({id,contentDigest:gate.reviewDigest(s),language:'approved',facts:'approved',method:'AI-assisted-editorial',reviewedAt:'2026-09-24',note:d.reason,evidence:'content/editorial-batch-2.11.9i.json#'+id,warningDisposition:a.flags?`The ${a.flags} flag was evaluated in the complete text. ${d.reason}`:`No automatic flags. Full text checked. ${d.reason}`,origin:'editorial-batch-2.11.9i'});
}
reviews.sort((a,b)=>Number(a.id.slice(1))-Number(b.id.slice(1)));
write('stories.json',stories);write('content/current-provenance.json',prov);write('content/review-progress.json',reviews);write('content/editorial-batch-2.11.9i.json',batch);
console.log('Reviewed',batch.length,'changed',batch.filter(x=>x.changed).map(x=>x.id).join(','));
