'use strict';
const fs=require('fs'),path=require('path'),crypto=require('crypto');
const root=path.resolve(__dirname,'..'),read=p=>JSON.parse(fs.readFileSync(path.join(root,p),'utf8'));
const write=(p,v)=>fs.writeFileSync(path.join(root,p),JSON.stringify(v,null,2)+'\n');
const sha=s=>crypto.createHash('sha256').update(s).digest('hex');
const policy=require('../learning-policy'),gate=require('./review_release_gate');
const stories=read('stories.json'),reviews=read('content/review-progress.json'),prov=read('content/current-provenance.json'),audits=read('learning_audit_records.json');
const decisions={
 s1039:{reason:'The old wax clue does not lead to a borrowed lamp, and a blue lantern is later called a lamp. A blue candle lantern leaves wax by the door; Zane confirms the neighbor took it to find a cat and returns it.',title:'The Blue Lantern at the Lodge',text:'The blue lantern was missing from a shelf at the mountain lodge. Zane saw a drop of candle wax beside the back door. He asked the lodge worker who used the back door.\n\nShe said a neighbor borrowed the lantern after a cat ran into the dark yard. Zane went next door. The neighbor had found the cat, but she had forgotten to return the lantern.\n\nShe brought it back and thanked the worker. They put a note beside the shelf asking people to sign when they borrowed a light.',subtopic:'everyday investigation'},
 s1040:{reason:'The harbor flag cannot be missing from a riverside park yet caught above its pole. Place it at a harbor, let a kite string hold it high, and have harbor staff free it safely.',title:'The Flag Above the Harbor',text:'Gus looked for the red flag at the harbor entrance. It was not on its usual pole. He saw a thin line stretching toward a high railing. The flag hung from it above the walkway.\n\nA child nearby said her kite string had caught the flag when the wind rose. Gus kept people away from the area and told the harbor worker. The worker used a long pole to bring the string down.\n\nThe flag was torn at one corner. The worker took it inside for repair, and the child collected her kite.',subtopic:'harbor mystery'},
 s1331:{reason:'Name the fictional textile worker explicitly and show one damaged cloth, a family photo for context, and a small tested repair rather than a generic claim that all history was saved.',title:'Leah Park and the Old Cloth',text:'Leah Park is a fictional cloth worker. A family brought her an old tablecloth with a tear beside an earlier repair. The thread from that repair was pulling at the cloth.\n\nLeah asked the family for a picture of the tablecloth in their grandmother’s home. Then she tried a new thread on a small edge. It held without pulling. She used that method on the tear and wrote down what she had done.\n\nThe family could now store the cloth with its story.',subtopic:'cloth repair'},
 s1332:{reason:'Replace repeated “work” sentences with a fictional transport planner who watches one missed shift and tries a limited night route with the team, not a guaranteed permanent service.',title:'Ravi Mehta Checks the Last Bus',text:'Ravi Mehta is a fictional bus planner. One evening, he met workers leaving a hospital after the last bus had gone. They told him which stops they needed.\n\nRavi rode the old route at night and wrote down how long it took. He asked drivers and the town team to test one later bus on two evenings each week. After a month, they counted the riders and asked what still did not work.\n\nSome workers could now reach home by bus. Ravi took their other requests back to the team.',subtopic:'night bus planning'},
 s1333:{reason:'Sofia’s fictional bird photography project should show a concrete distance rule and viewing point instead of claiming cameras always protect nests.',title:'Sofia Almeida Keeps Her Distance',text:'Sofia Almeida is a fictional bird guide. On one tour, visitors walked too close to a nesting area to take pictures. She stopped the group. She asked a local bird watcher where they could stand.\n\nTogether they chose a marked path farther away. From there, Sofia showed visitors how to use the zoom on their cameras. Some birds were too far away for a clear picture, but the group stayed on the path.\n\nBefore the next tour, Sofia added the route to her guide notes.',subtopic:'wildlife guiding'},
 s1334:{reason:'The fictional designer must consult users, make a specific low-cost repairable item and test it with that person rather than claim universal accessibility.',title:'Daniel Cho Designs a Handle',text:'Daniel Cho is a fictional tool designer. A neighbor told him that a garden tap was hard for her to turn. Daniel watched her try it and asked which part was difficult.\n\nHe made a larger handle from parts the local shop could replace. The first handle slipped, so he changed its shape. The neighbor tried the new one and could turn her tap more easily.\n\nDaniel wrote down its parts for the shop. He asked the neighbor to tell him if the handle became loose again.',subtopic:'repairable tools'},
 s1335:{reason:'Fatima’s fictional market plan should include small sellers and a specific walkway problem, then observe results without guaranteeing every shop stays open.',title:'Fatima Noor Makes Room at the Market',text:'Fatima Noor is a fictional market planner. Sellers told her that a proposed new walkway would pass through their small stalls. She visited the market during its busiest hour and drew the places where people stopped.\n\nAt a meeting, Fatima showed the drawing. The sellers suggested moving the walkway along an empty wall. The town tested that route with temporary lines on the ground.\n\nPeople could pass the stalls, but one corner was still crowded. Fatima asked the sellers to help adjust it.',subtopic:'market planning'},
 s1336:{reason:'Henry Cole is the name of a documented British civil servant. Rename the imaginary weather observer and distinguish checked instruments from notebook observations.',title:'Henry Calder Watches the Weather',text:'Henry Calder is a fictional weather watcher by the sea. Salt air made the case of his rain tool hard to open. The case was metal. Henry cleaned the case. He asked a repair worker to check it.\n\nWhile it was being repaired, Henry marked a gap in his records. He wrote down what he saw, but did not turn those notes into exact rain amounts. When the tool came back, he kept it under a shelter and checked it often.\n\nHis records showed both the readings and the days he could not measure.',subtopic:'weather records',sources:['https://www.vam.ac.uk/articles/building-the-museum']},
 s1337:{reason:'Make Anika a fictional community teacher who helps people understand a farm form and seek a qualified adviser for legal questions, without promising an interpretation of rights.',title:'Anika Bose Explains a Farm Form',text:'Anika Bose is a fictional community teacher. Farm workers brought her a long form they could not read easily. She met them at the town hall and asked which words were confusing.\n\nAnika wrote a short list of questions in plain language. She did not tell people what to sign. A qualified adviser came to explain the form and answer their questions.\n\nAfter the meeting, Anika made a clear guide to where workers could get help with new forms.',subtopic:'plain-language forms'},
 s1338:{reason:'A clock repair requires a specific fault and qualified worker. Gabriel is fictional; show documentation of original pieces, then repair and test.',title:'Gabriel Stone and the Town Clock',text:'Gabriel Stone is a fictional clock repairer. The town clock stopped just before noon. Inside it, he found a worn wheel and marks from an older repair.\n\nHe took pictures before touching the parts. Then he checked an old drawing kept at the town hall. Gabriel replaced the worn wheel with a part that could be removed later. He kept the old one in a marked box.\n\nAfter a week of checks, the clock still showed the right time. The town kept Gabriel’s notes with its drawing.',subtopic:'clock repair'},
 s1339:{reason:'The original food donation gives no handling details. Mina’s fictional team should collect suitable food through a food-service partner with chilling and checks, and discard anything they cannot verify.',title:'Mina Rahman Plans a Food Pickup',text:'Mina Rahman is a fictional food program worker. A café offered extra meals at closing time. Mina asked which meals were still fit to share. She asked how the café kept them.\n\nShe arranged a pickup that day. A local meal service carried the chilled food and checked it again. Some meals could be used. Others were left out because their handling was unclear.\n\nAfter a few weeks, Mina and the café changed the pickup time so less good food was wasted.',subtopic:'food donation'},
 s1340:{reason:'Surface cave marks alone cannot show how polluted water moves underground. Arthur’s fictional survey maps an accessible cave path and asks water staff to take samples; conclusions await results.',title:'Arthur Vale Maps a Cave',text:'Arthur Vale is a fictional cave survey worker. Two nearby wells had water that looked cloudy after rain. People wondered whether a small cave linked the areas.\n\nArthur and his team mapped the cave entrance and the paths they could reach safely. They did not guess where the water went beyond them. Town water workers took samples from the wells and arranged tests.\n\nArthur put the map beside the test dates. The team would compare the results before saying whether the wells were connected.',subtopic:'cave mapping'},
 s1341:{reason:'A fictional reporter can describe repair options without declaring specific products durable from a brief observation. Give Zoe a comparison and named source.',title:'Zoe Bennett Asks About Repairs',text:'Zoe Bennett is a fictional news writer. Readers asked whether a broken kitchen tool could be fixed. She took two different old tools to a repair shop.\n\nThe worker could replace a part in one tool. The other needed a part the shop could not get. Zoe asked about the cost and wrote down what the worker knew and what was still uncertain.\n\nHer article gave readers questions to ask before buying a tool. It did not promise that every one could be repaired.',subtopic:'consumer reporting'},
 s1342:{reason:'A fictional river mapper should update a local guide with boat operators but not claim an informal map makes navigation safe. Show an official map as reference and reports of changes.',title:'Maya Chen Updates a River Guide',text:'Maya Chen is a fictional river guide writer. Boat workers told her a sandbank had changed after heavy rain. Her old drawing no longer matched what they saw.\n\nMaya checked the official river notice with a boat captain. She then marked the reported change on a local guide and added the date. At the next meeting, she asked more captains what they had seen.\n\nShe reminded readers to use current official notices for travel. Her guide helped them ask better questions about the changing river.',subtopic:'river guides'},
 s1343:{reason:'Give the fictional bicycle mechanic a concrete repair and safe brake check instead of suggesting anyone can fix critical parts from a brief lesson.',title:'Jon Bell Checks a Bicycle',text:'Jon Bell is a fictional bicycle mechanic. A worker brought in a bike whose brake lever moved too far. Jon inspected the cable and found it was worn.\n\nHe fitted a new cable. Jon tested both brakes before giving the bike back. He showed the owner how to spot a loose lever. He also said when to bring the bike in for a check.\n\nThe owner rode to work the next day. Jon put the worn cable in a box so new helpers could see why he had changed it.',subtopic:'bicycle repair'},
 s1344:{reason:'Old local seeds do not guarantee harvests during drought. Amina’s fictional seed project records varieties and grows small trial plots to observe what works.',title:'Amina Okafor Keeps Seed Records',text:'Amina Okafor is a fictional seed keeper. Families in her village brought seeds from plants they had grown for years. Some packets had no names or dates.\n\nAmina asked each family what it knew and wrote the answers on new labels. She kept a small amount of each kind and planted a few in trial beds. During a dry month, some plants grew and others did not.\n\nShe recorded the results without calling any seed a sure answer to dry weather. The families could use the notes for next year.',subtopic:'local seed records'},
 s1345:{reason:'Luis is a fictional adult reading teacher. Use a particular class adjustment and a measured outcome instead of an unsupported claim that several students became teachers.',title:'Luis Ortega Changes the Reading Class',text:'Luis Ortega is a fictional reading teacher. His students worked late shifts. Some arrived tired and missed the start of class.\n\nLuis asked what times they could come. He moved one lesson to the afternoon and used words from bus signs and work notes. Students practiced reading them together.\n\nAfter a month, one student said she could read the stop names on her way home. Luis asked which words she still wanted to learn and planned the next lesson with the class.',subtopic:'adult reading class'},
 s1346:{reason:'A fictional toy maker can design a replaceable wheel and check small parts with a specialist, without claiming all wooden toys are automatically safe or that the shop is saved.',title:'Hana Mori Makes a Repairable Toy',text:'Hana Mori is a fictional toy maker. A child brought a wooden cart with a broken wheel to her shop. Hana saw that the wheel could not be removed without breaking the cart.\n\nShe made a new cart with a wheel that a worker could replace. She asked a toy safety specialist to check the design before children used it. After the check, the child tried the cart at the shop.\n\nHana kept a spare wheel and instructions. The child knew where to bring the cart if a wheel broke again.',subtopic:'wooden toy design'},
 s1347:{reason:'Medical visits require qualified staff. Make Samir a fictional clinic coordinator who consults nurses, arranges a nearby visit and relies on their clinical judgment.',title:'Samir Patel Moves a Clinic Visit',text:'Samir Patel is a fictional clinic coordinator. Rain made the road to the main clinic hard to use. He asked families which days they could reach a community hall nearby.\n\nSamir spoke with the clinic nurses. They agreed to hold a supervised visit at the hall on one day each month. Samir organized the room and told families the time. The nurses brought the supplies they needed and decided what care they could offer there.\n\nAfter the first visit, Samir asked the staff and families what the next one needed.',subtopic:'community clinic planning'},
 s1348:{reason:'A raised bed does not by itself prove poor soil is safe or productive. Elena’s fictional group uses fresh planting soil and agrees on a small trial garden, then describes the actual use.',title:'Elena Rossi Starts a Garden Bed',text:'Elena Rossi is a fictional gardener. The ground near the town hall was hard to dig. Families wanted a place for children to grow a few plants.\n\nElena asked the town where a garden could go. With permission, the group built two raised beds and filled them with planting soil. Children chose beans and herbs. Some seeds grew; others needed another try.\n\nIn summer, families met beside the beds to water them. Elena wrote down what grew so they could plan the next season.',subtopic:'community gardening'}
};
const batch=[];
for(const [id,d] of Object.entries(decisions)){
 const s=stories.find(x=>x.id===id),p=prov.find(x=>x.id===id),a=audits.find(x=>x.id===id);
 if(!s||!p||!a||a.errors||s.level!==2||reviews.some(x=>x.id===id))throw Error('Unexpected source '+id);
 const before=structuredClone(s);
 if(d.title)s.title=d.title;
 if(d.text){s.text=d.text;s.wordCount=policy.countWords(s.text)}
 if(d.contentType)s.contentType=d.contentType;
 if(d.subtopic)s.subtopic=d.subtopic;
 if(d.topic)s.topic=d.topic;
 const changed=Boolean(d.title||d.text||d.contentType||d.subtopic||d.topic);
 if(changed){s.reviewedAt='2026-09-25';const check=policy.inspect(s);if(check.errors.length)throw Error('Learning policy '+id+': '+JSON.stringify(check));p.text_sha256=sha(s.text);p.status='editorial-revision-2026-09-25';p.evidence='content/editorial-batch-2.11.9q.json#'+id;p.note=d.reason;}
 batch.push({id,level:s.level,title:s.title,before,after:structuredClone(s),changed,reason:d.reason,sources:d.sources||[],review:'Individual full-text reading for language, source fidelity, logical order, level fit and fiction scope; AI-assisted editorial',beforeFlags:a.flags});
 reviews.push({id,contentDigest:gate.reviewDigest(s),language:'approved',facts:'approved',method:'AI-assisted-editorial',reviewedAt:'2026-09-25',note:d.reason,evidence:'content/editorial-batch-2.11.9q.json#'+id,warningDisposition:a.flags?`The ${a.flags} flag was evaluated in the complete text. ${d.reason}`:`No automatic flags. Full text checked. ${d.reason}`,origin:'editorial-batch-2.11.9q'});
}
reviews.sort((a,b)=>Number(a.id.slice(1))-Number(b.id.slice(1)));
write('stories.json',stories);write('content/current-provenance.json',prov);write('content/review-progress.json',reviews);write('content/editorial-batch-2.11.9q.json',batch);
console.log('Reviewed',batch.length,'changed',batch.filter(x=>x.changed).map(x=>x.id).join(','));
