'use strict';
const fs=require('fs'),path=require('path'),crypto=require('crypto');
const root=path.resolve(__dirname,'..'),read=p=>JSON.parse(fs.readFileSync(path.join(root,p),'utf8'));
const write=(p,v)=>fs.writeFileSync(path.join(root,p),JSON.stringify(v,null,2)+'\n');
const sha=s=>crypto.createHash('sha256').update(s).digest('hex');
const policy=require('../learning-policy'),gate=require('./review_release_gate');
const stories=read('stories.json'),reviews=read('content/review-progress.json'),prov=read('content/current-provenance.json'),audits=read('learning_audit_records.json');
const decisions={
 s1326:{reason:'Theo already acts as a named fictional person. Make the accessible theater change concrete: ask deaf audience members, involve a signer and leave a clear view of the stage. Avoid implying every audience member has the same need.',title:'Theo Makes Room for Signs',text:'Theo Martin helps at a theater. Some visitors cannot hear the actors well. Theo asks them what would help. They want to see someone use sign language during the show. Theo speaks with a signer and the actors. At the next show, the signer stands where people can see her and the stage. Afterward, Theo asks the visitors what worked for them.'},
 s1327:{reason:'The original claims seasonal tests located the source of unsafe well water without enough evidence. Let Priya and a trained worker gather samples, have a lab report the result, and have the town arrange another source while investigating.',title:'Priya Checks the Well',text:'Priya Das helped at a town well. Some people said the water looked different after rain. Priya asked a water worker to take samples. The worker sent them to a lab. One result showed a problem, but it did not show where the problem began. The town told families to use another water source for now. Priya and the worker kept checking the well.'},
 s1328:{reason:'Name Marcus in the text, use he instead of unexplained they, and show how moving rehearsals preserves one band without a formulaic ending.',title:'Marcus Finds a Room for Music',text:'Marcus Green taught music in a small town. The old music room closed. His young players had nowhere to meet. Marcus asked the school if they could use a classroom once a week. The school agreed. On the first day, the players carried their music there. They played together again, and Marcus wrote the next practice day on the board.'},
 s1329:{reason:'Dust can reduce solar panel output, but a cover over the panels would block sunlight. Show Yara checking a solar-powered fan with an installer and keeping the panels clean; do not promise full temperature control for a health room.',title:'Yara Helps a Room Stay Cool',text:'Yara Nasser worked at a small health room. On hot days, the room needed more air. An installer put a fan there that used power from the sun. After a dusty week, the fan moved more slowly. Yara asked the installer to check the system. They cleaned the panels in a safe way. On the next sunny day, the fan worked better. Yara kept a note of the checks.'},
 s1330:{reason:'The court guide concerns real consequences in an invented setting. Give Finn a court clerk who checks plain-language wording and avoid suggesting that the guide replaces official advice.',title:'Finn Explains Court Words',text:'Finn Osei worked with a court clerk. Some visitors found the forms hard to read. Finn wrote a short guide to words on the forms. The clerk checked each line and fixed two mistakes. They put the guide at the front desk. A visitor read it and then asked the clerk one more question. Finn learned that clear words can help people know what to ask.'},
 s1478:{reason:'The Brothers Grimm story gives the youngest son the goose after his brothers refuse to share food. Clarify that the brothers met the traveler earlier, then show the goose’s sticky feathers and procession.',text:'A traveler asked two brothers for food. They did not share. Later, he met their younger brother. The young man shared his food and drink. The traveler showed him a tree, and he found a golden goose there. Other people wanted its feathers. They touched the goose and could not let go. Soon they followed the young man in a long line.',sources:['https://www.gutenberg.org/cache/epub/2591/pg2591-images.html']},
 s1501:{reason:'The woman and her new seed bowl are a fictional historical vignette, not a documented individual. Give the drying, firing and cooling actions a clear order.',contentType:'narrative-fiction',text:'Long ago, a woman made pots in a village. She wanted a small bowl for seeds. She shaped wet clay with her hands and let it dry. Then she fired the bowl. When it was cool, she put seeds inside. She made a lid to keep the seeds in the bowl.'},
 s1502:{reason:'This invented bridge episode describes children crossing a stream soon after a flood on untested stones. Wait until the water falls and let experienced builders place and check stones before anyone uses them.',contentType:'narrative-fiction',text:'Rain made a stream rise. The old wood bridge washed away. People waited until the water was low again. Then builders from the village set flat stones across the stream. They checked each stone before opening the new path. Families helped carry tools and stones. Soon people could cross again. The villagers still planned to build a stronger bridge.'},
 s1503:{reason:'The watch and several small fires are invented, not a documented institution. Change the repeated-fire and guaranteed-safety language to one clear event: a watcher sees smoke, rings a bell and neighbors respond.',contentType:'narrative-fiction',text:'Long ago, a town had many wooden homes. At night, neighbors took turns watching the streets. Each carried a bell. One night, a watcher saw smoke by a house. She rang her bell. Neighbors came with water, and the family came outside. Together they put out a small fire. The watcher went on with her walk after the street was quiet again.'},
 s1520:{reason:'A snail crossing a path after rain is a particular invented incident, and the plants-and-fungi subtopic is wrong. Classify as animal fiction and keep the weather-path metaphor tied to this snail.',contentType:'narrative-fiction',subtopic:'snail after rain'},
 s1521:{reason:'The small bird’s bath and the passing person form a single fictional scene. Use a fiction label so the narrator does not imply this sequence describes all sparrows.',contentType:'narrative-fiction'},
 s1533:{reason:'The children observe an ice cube becoming liquid water. The piece explains a real everyday change with correct sequence, short sentences and no unsupported claim.'},
 s1534:{reason:'Indiana University’s plant observation confirms roots can respond to gravity in darkness while shoots orient upward. “Green stem” without light and “root finds water below” imply too much; describe a pale shoot and gravity response separately from later access to light.',text:'A bean seed started to grow in a dark jar. Its first root went down. A pale shoot went up. A child turned the jar on its side. After some time, the root bent down again. The shoot bent up. The new plant had no eyes. It could respond to the pull of the earth, even in the dark. Later, the shoot could reach light above the soil.',sources:['https://plantsinmotion.bio.indiana.edu/movies-categories/germination/corn-germination.html']},
 s1535:{reason:'An echo is reflected sound, but ten steps near a wall may not give a distinct change in delay. Place Mia far enough from the wall, then farther away, and name the longer round trip.',text:'Mia stood far from a high wall and clapped. She heard her clap again a little later. It was an echo. Mia walked farther from the wall and clapped once more. Now she waited a little longer for the echo. Her sound had gone to the wall and come back. From farther away, that trip took more time.',sources:['https://www.physicsclassroom.com/class/sound/Lesson-3/Reflection%2C-Refraction%2C-and-Diffraction']},
 s1547:{reason:'The work openly says “made-up story”; two groups within one school arrange field times and Friday play. Fiction classification matches this specific negotiated episode.',contentType:'narrative-fiction'},
 s1548:{reason:'The three streets’ water rules and town request are an explicitly made-up case, not an observation of a real town. Classify it as fiction; the text already notes that rationing alone cannot produce more water.',contentType:'narrative-fiction'},
 s1612:{reason:'One crab finding a pool by sea grass is an imagined coastal scene; mark it as fiction rather than a general claim about crab behavior.',contentType:'narrative-fiction'},
 s1613:{reason:'Two streets choosing a weekday and rest-day bus schedule is a specific invented town decision; the proposal is only a trial and does not guarantee every rider is served.',contentType:'narrative-fiction'},
 s1615:{reason:'The Metropolitan Museum documents reeds pressed into clay for grain records. This passage is an explanatory account of old writing, not one historical character’s narrative; identify the reed and avoid suggesting all tablets survived merely by sun drying.',contentType:'explanatory-nonfiction',text:'Long ago in Mesopotamia, people pressed marks into wet clay. A cut reed could make the marks. Some marks kept records of food and animals. The clay dried and became hard. Some clay records lasted for many years. People today can still read some of their marks.',sources:['https://www.metmuseum.org/art/collection/search/327384']},
 s1616:{reason:'Aya sees water drops outside a cold cup despite no hole. The water vapor in the air can form liquid drops on its cold surface; the repeated wipe makes the observation clear.'}
};
const batch=[];
for(const [id,d] of Object.entries(decisions)){
 const s=stories.find(x=>x.id===id),p=prov.find(x=>x.id===id),a=audits.find(x=>x.id===id);
 if(!s||!p||!a||a.errors||s.level!==1||reviews.some(x=>x.id===id))throw Error('Unexpected source '+id);
 const before=structuredClone(s);
 if(d.title)s.title=d.title;
 if(d.text){s.text=d.text;s.wordCount=policy.countWords(s.text)}
 if(d.contentType)s.contentType=d.contentType;
 if(d.subtopic)s.subtopic=d.subtopic;
 const changed=Boolean(d.title||d.text||d.contentType||d.subtopic);
 if(changed){s.reviewedAt='2026-09-24';const check=policy.inspect(s);if(check.errors.length)throw Error('Learning policy '+id+': '+JSON.stringify(check));p.text_sha256=sha(s.text);p.status='editorial-revision-2026-09-24';p.evidence='content/editorial-batch-2.11.9j.json#'+id;p.note=d.reason;}
 batch.push({id,level:s.level,title:s.title,before,after:structuredClone(s),changed,reason:d.reason,sources:d.sources||[],review:'Individual full-text reading for level, grammar, causal sequence, source and fictional framing; AI-assisted editorial',beforeFlags:a.flags});
 reviews.push({id,contentDigest:gate.reviewDigest(s),language:'approved',facts:'approved',method:'AI-assisted-editorial',reviewedAt:'2026-09-24',note:d.reason,evidence:'content/editorial-batch-2.11.9j.json#'+id,warningDisposition:a.flags?`The ${a.flags} flag was evaluated in context. ${d.reason}`:`No automatic flags. Full text checked. ${d.reason}`,origin:'editorial-batch-2.11.9j'});
}
reviews.sort((a,b)=>Number(a.id.slice(1))-Number(b.id.slice(1)));
write('stories.json',stories);write('content/current-provenance.json',prov);write('content/review-progress.json',reviews);write('content/editorial-batch-2.11.9j.json',batch);
console.log('Reviewed',batch.length,'changed',batch.filter(x=>x.changed).map(x=>x.id).join(','));
