'use strict';
const fs=require('fs'),path=require('path'),crypto=require('crypto');
const root=path.resolve(__dirname,'..'),read=p=>JSON.parse(fs.readFileSync(path.join(root,p),'utf8'));
const write=(p,v)=>fs.writeFileSync(path.join(root,p),JSON.stringify(v,null,2)+'\n');
const sha=s=>crypto.createHash('sha256').update(s).digest('hex');
const policy=require('../learning-policy'),gate=require('./review_release_gate');
const stories=read('stories.json'),reviews=read('content/review-progress.json'),prov=read('content/current-provenance.json'),audits=read('learning_audit_records.json');
const decisions={
 s408:{reason:'The fable has two contrasting meals, two interruptions and a clear choice to return to the field. The adapted danger and moral are coherent with the source tradition.',sources:['https://www.gutenberg.org/cache/epub/28/pg28-images.html']},
 s416:{reason:'The well sings within an expressly magical village story; dropping a coin happens by accident and family members hear the same sound. No real location is asserted.'},
 s426:{reason:'Nutkin is a named character and the closing lesson belongs to a fictional animal scene. Correct its content type and label the squirrel and seed subject; distinguish acorns from a generic collection of nuts and avoid promising that every hidden nut grows.',contentType:'narrative-fiction',subtopic:'squirrels and acorns',sources:['https://research.fs.usda.gov/feis/species-reviews/querub'],text:'In fall, a squirrel named Nutkin looked for acorns beneath the oak trees. He buried some in different places to find later.\n\nWhen snow came, Nutkin dug up several of them. He did not find every hiding place. In spring, a few young oak plants appeared where acorns still lay in the ground.\n\nNutkin had stored food for winter. Without knowing it, he had also given some acorns a chance to grow.'},
 s436:{reason:'The town meeting is expressly invented and presents a particular vote and its tradeoff. Classify the scene as fiction; the hall roof and next-year list are clear.',contentType:'narrative-fiction'},
 s446:{reason:'The repeated missing socks, discovery under the sofa and tentative future habit form a coherent domestic fiction without a promised universal solution.'},
 s456:{reason:'The village and fire are explicitly made up and have no historical referent. Mark it as fiction and replace the war label with village mutual aid.',contentType:'narrative-fiction',subtopic:'village mutual aid'},
 s466:{reason:'Replace the inaccurate phrase about soap changing the outside of water and the vague “very little skin” explanation with a thin soapy film whose surface tends toward a round shape; a film breaks when it dries or touches something.',text:'A bubble begins with a thin film of soapy water. Soap helps the film stretch without breaking at once.\n\nWhen you blow gently through a wet ring, air pushes the film outward. The film can close around the air and form a bubble. A floating bubble is usually round because its thin surface pulls into a shape with little surface for the air inside.\n\nThe film can dry or touch something sharp. Then it breaks, and the air escapes.',sources:['https://blogs.loc.gov/teachers/2020/06/lets-make-bubbles-connecting-history-and-stem/']},
 s476:{reason:'The Grimm version has the edible house, the witch imprisoning Hansel, Gretel escaping the oven trap, and a journey home. Add the missing imprisonment and the trick that frees Hansel so the retelling does not skip its key causal turn; retain gentle language.',text:'Hansel and Gretel got lost in a forest. After a long walk, they found a small house made of sweet food. They were hungry, so they broke off pieces to eat.\n\nAn old woman invited them inside. She was a witch. She shut Hansel in a small room and made Gretel work for her.\n\nOne day, the witch told Gretel to look into an oven. Gretel knew the witch was trying to trap her. She asked the witch to show her how. When the witch looked inside, Gretel pushed her in and shut the door.\n\nThen Gretel opened Hansel’s door. They left the house together and found their way home.',sources:['https://www.gutenberg.org/cache/epub/19068/pg19068-images.html']},
 s486:{reason:'The glowing plants exist as fantasy, their nightly change and Tomas’s response are consistent; neither plant behavior nor a real place is presented as nonfiction.'},
 s496:{reason:'Clara watches a specific spider rebuild after wind. The claim that it “did not seem angry” is a human inference; describe visible behavior and keep the human lesson in Clara’s thoughts.',contentType:'narrative-fiction',text:'A small spider made a web near Clara’s window. Each morning, Clara watched it add fine lines.\n\nOne night, strong wind broke the web. Clara thought the spider might leave. But the next morning, it began another web. By evening, new threads hung between two branches.\n\nClara thought about the little spider as she watched. A hard day did not always have to be the end. She could rest and try again too.'},
 s506:{reason:'This is explicitly a made-up city and Maria’s individual choice, so the content type is fiction. The final sentence limits the bus benefit to the journey she tried.',contentType:'narrative-fiction'},
 s516:{reason:'The grandmother’s recipe cards and her daughter’s additions create a plausible intergenerational scene. The hard-to-read cards are explained through a conversation.'},
 s526:{reason:'Gustaf is an invented historical-style character, not a documented biography. Reclassify as fiction and replace an unrelated politics subtopic with village metalworking. The apprentice resolves the skill-transfer concern.',contentType:'narrative-fiction',subtopic:'village metalworking'},
 s536:{reason:'The text correctly mentions water loss and changes in starch but wrongly says a closed bag slows both. Specify that covering mainly reduces drying and cannot stop bread becoming firm as starch changes; avoid a general storage recommendation that overlooks mold.',text:'Fresh bread often feels soft. As it sits, some water can move out of its soft middle. If the bread is left uncovered, it may also lose water to the air.\n\nThe starch in bread changes as the bread cools and gets older. This can make the middle feel firm even when it has not lost all its water.\n\nA bag can slow drying, but it cannot stop the starch from changing. Bread may still grow hard with time.',sources:['https://pmc.ncbi.nlm.nih.gov/articles/PMC7824337/','https://pmc.ncbi.nlm.nih.gov/articles/PMC6170360/']},
 s546:{reason:'The emperor, pretended cloth, fear of seeming foolish and child who speaks up follow Andersen’s central plot. The ending resolves the crowd’s silence without claiming a historical event.',sources:['https://www.gutenberg.org/files/1597/1597-h/1597-h.htm']},
 s557:{reason:'The existing fantasy topic is fixed for compatibility. Give the generous shoemaker one small, observable magical event when he offers a spare pair, and classify the subtopic as everyday magic.',subtopic:'everyday magic',text:`Anton made shoes in a small shop. He often made an extra pair of little shoes. His neighbors asked who would wear them.\n\n"Perhaps someone will need them," he said.\n\nOne winter evening, a family came to the shop. Their child’s shoes were worn out. One of Anton’s spare pairs fitted well. When the child stepped into them, the laces tied themselves in neat bows.\n\nAnton and the child looked at each other in surprise. He gave the shoes to the family. The next morning, he began another small pair.`},
 s558:{reason:'Cloud guiding is left as a possible village belief in a fantasy story. The subtopic should refer to weather magic rather than objects and transformations.',subtopic:'weather magic'},
 s577:{reason:'The grandfather’s explanation addresses one woodpecker searching for insects, but a named child draws a personal lesson, making this fiction. Replace the plant/fungi label; avoid suggesting every knock is food seeking.',contentType:'narrative-fiction',subtopic:'woodpeckers and insects',sources:['https://www.allaboutbirds.org/guide/Downy_Woodpecker'],text:'Each morning, a woodpecker tapped a tree outside Marcus’s room. The sound woke him early.\n\nAt first, Marcus wished the bird would go away. His grandfather said that a woodpecker can tap wood to find insects. Marcus watched from the window. The bird pulled a small insect from the tree.\n\nHe still woke up when it tapped, but now he knew what this bird was doing. He closed the window when he needed more sleep.'},
 s578:{reason:'This is a didactic turtle story with observing children, so classify it as fictional animal narrative. Remove the unsupported general claim that fast animals miss danger and the claim that the turtle avoids danger because she moves slowly.',contentType:'narrative-fiction',text:'An old turtle left the pond and moved toward a patch of warm sand. A few children watched her from the path.\n\nThe turtle stopped near a fox’s den. She waited, then turned and took another path. The children stayed back and let her pass.\n\nAfter a while, the turtle reached the sand. She rested there in the sun. The children were glad they had watched quietly.'},
 s597:{reason:'The group is explicitly invented. Classify the clean-up as fiction and use a community action subtopic rather than migration or rights.',contentType:'narrative-fiction',subtopic:'community clean-up'}
};
const batch=[];
for(const [id,d] of Object.entries(decisions)){
 const s=stories.find(x=>x.id===id),p=prov.find(x=>x.id===id),a=audits.find(x=>x.id===id);
 if(!s||!p||!a||a.errors||s.level!==2||reviews.some(x=>x.id===id))throw Error('Unexpected source '+id);
 const before=structuredClone(s);
 if(d.title)s.title=d.title;
 if(d.text){s.text=d.text;s.wordCount=policy.countWords(s.text)}
 if(d.contentType)s.contentType=d.contentType;
 if(d.subtopic)s.subtopic=d.subtopic;
 if(d.topic)s.topic=d.topic;
 const changed=Boolean(d.title||d.text||d.contentType||d.subtopic||d.topic);
 if(changed){s.reviewedAt='2026-09-24';const check=policy.inspect(s);if(check.errors.length)throw Error('Learning policy '+id+': '+JSON.stringify(check));p.text_sha256=sha(s.text);p.status='editorial-revision-2026-09-24';p.evidence='content/editorial-batch-2.11.9m.json#'+id;p.note=d.reason;}
 batch.push({id,level:s.level,title:s.title,before,after:structuredClone(s),changed,reason:d.reason,sources:d.sources||[],review:'Individual full-text reading for language, source fidelity, logical order, level fit and fiction scope; AI-assisted editorial',beforeFlags:a.flags});
 reviews.push({id,contentDigest:gate.reviewDigest(s),language:'approved',facts:'approved',method:'AI-assisted-editorial',reviewedAt:'2026-09-24',note:d.reason,evidence:'content/editorial-batch-2.11.9m.json#'+id,warningDisposition:a.flags?`The ${a.flags} flag was evaluated in the complete text. ${d.reason}`:`No automatic flags. Full text checked. ${d.reason}`,origin:'editorial-batch-2.11.9m'});
}
reviews.sort((a,b)=>Number(a.id.slice(1))-Number(b.id.slice(1)));
write('stories.json',stories);write('content/current-provenance.json',prov);write('content/review-progress.json',reviews);write('content/editorial-batch-2.11.9m.json',batch);
console.log('Reviewed',batch.length,'changed',batch.filter(x=>x.changed).map(x=>x.id).join(','));
