'use strict';
const fs=require('fs'),path=require('path'),crypto=require('crypto');
const root=path.resolve(__dirname,'..'),read=p=>JSON.parse(fs.readFileSync(path.join(root,p),'utf8'));
const write=(p,v)=>fs.writeFileSync(path.join(root,p),JSON.stringify(v,null,2)+'\n');
const sha=s=>crypto.createHash('sha256').update(s).digest('hex');
const policy=require('../learning-policy'),gate=require('./review_release_gate');
const stories=read('stories.json'),reviews=read('content/review-progress.json'),prov=read('content/current-provenance.json'),audits=read('learning_audit_records.json');
const decisions={
 s700:{reason:'The town’s roof, shopkeepers and negotiated market days form one invented policy episode. Classify the concrete town as fiction; the qualification that the roof solves only part of the problem is useful.',contentType:'narrative-fiction'},
 s703:{reason:'The Metropolitan Museum documents Egyptian bread making and bread rations. Avoid “every day” for every person and narrow the pay statement to some workers; use explanatory nonfiction for this historical overview.',contentType:'explanatory-nonfiction',text:'Bread was important in ancient Egypt. Many people ate it often. Farmers grew grain near the Nile River. Workers made flour from the grain and mixed it with water. Then they baked the dough. Bread came in many shapes. Some loaves had other foods in them, too. Bread was eaten in many homes. Some workers also received bread for their work. A simple loaf can tell us about daily life long ago.',sources:['https://www.metmuseum.org/perspectives/food-and-feasts-in-middle-kingdom-egypt','https://www.metmuseum.org/art/collection/search/544258']},
 s704:{reason:'English Heritage documents varied Roman road construction under military oversight. The original overview is explanatory, not a single historical event; replace “stone and small stones” with natural beginner wording and avoid implying every road was straight.',contentType:'explanatory-nonfiction',text:'The Romans built many long roads. Soldiers used them to travel. People also carried food and other goods along them. Road builders often used layers of stones. They made many roads strong and helped water run off them. Some Roman roads were very straight. The roads made travel between places easier, although journeys still took time. Parts of some old roads can be seen today.',sources:['https://www.english-heritage.org.uk/learn/story-of-england/romans/roman-roads/']},
 s705:{reason:'“The water tiny parts” is ungrammatical and the original implies a temperature rise throughout melting. Explain heat and freer motion with short Level 1 clauses while retaining the reversible state change.',text:'Ice is solid water. In a warm room, an ice cube takes in heat. The tiny parts of water in the ice can move more freely. The ice melts into liquid water. This is why an ice cube gets smaller in a warm room. If the water gets cold enough, it can freeze into ice again.'},
 s706:{reason:'NASA describes shadow motion and sundials. Use the correct common term “sundial” instead of “sun clock”; qualify noon shadows for a clear sunny setting.',text:'A shadow appears when something blocks light. Stand outside on a sunny morning. Your shadow may be long. Around the middle of the day, it may be shorter. Later, it grows long again. Your body has not changed. The Sun seems to move across the sky, so its light reaches you from different directions. Your shadow changes with the light. Long ago, people used moving shadows to tell time with sundials.',sources:['https://pwg.gsfc.nasa.gov/stargaze/Sundial.htm']},
 s707:{reason:'The dog mistakes his reflection for another dog, drops the meat when barking and loses what he carried. The simple fable ending follows clearly from the action.'},
 s708:{reason:'The Grimm tale has a kind young man share his food, then find the goose beneath a tree. Restore this causal step instead of saying the stranger handed him the goose; retain the procession and princess’s laughter.',text:'A young man shared his food with an old stranger. The stranger told him to look under a tree. There the young man found a golden goose. He carried it to town. A woman touched a feather and could not let go. Another person tried to pull her away and became stuck too. Soon a line of people followed the goose. A princess saw them and laughed. She had not laughed for a long time. The king was glad to hear her laugh again.',sources:['https://www.gutenberg.org/cache/epub/2591/pg2591-images.html']},
 s839:{reason:'In the original Heidi makes a hay bed, eats bread and cheese with her grandfather, and grows close to life on the mountain. The chair and home sequence remain plausible for a short retelling.',sources:['https://www.gutenberg.org/cache/epub/1448/pg1448-images.html']},
 s840:{reason:'Mary finds the buried key, a robin helps her find the hidden door, and the garden revives. The short retelling tracks the original book’s key, bird and garden events.',sources:['https://www.gutenberg.org/files/17396/17396-h/17396-h.htm']},
 s841:{reason:'The broken blue cup and instant return to a small nose are invented and conflict with the original lying-to-the-Fairy episode. Replace with the gold-coin lies and the Fairy’s woodpeckers restoring the nose.',text:'Pinocchio met the Fairy. She asked him about the gold coins he had lost. Pinocchio told her a lie. His nose grew long. He told her another lie, and it grew longer. At last he stopped lying. He told the Fairy what had happened. She called some woodpeckers. They pecked at his nose until it was small again. Pinocchio saw that his lies had caused trouble.',sources:['https://www.gutenberg.org/cache/epub/500/pg500-images.html']},
 s842:{reason:'Dorothy and Toto follow the yellow road, meet the Scarecrow and Tin Woodman and travel together. The simplified wishes and companionship make a coherent Level 1 retelling.'},
 s843:{reason:'Black Beauty is cared for after difficult owners and Joe Green recognizes him near the novel’s end. This retelling retains the main recognition and rest.',sources:['https://www.gutenberg.org/files/271/271-h/271-h.htm']},
 s845:{reason:'A particular fox drinks from a bowl and returns to the trees. The scene is invented and its existing plants-and-fungi label is unrelated to the animal; correct both classifications.',contentType:'narrative-fiction',subtopic:'wild animals near towns'},
 s846:{reason:'The original tells a child and mother to stop live traffic and carry a turtle, an unnecessary dangerous action in a beginner story. Instead they stay away from cars and seek local help; the turtle crosses only after traffic stops naturally.',contentType:'narrative-fiction',text:'A turtle came to a busy road. Cars went past. A boy saw the turtle and told his mother. They stayed away from the road and called a local wildlife helper. The helper came when the cars had stopped at a red light. She moved the turtle to the other side. The boy watched from a safe place. The turtle went into the grass.'},
 s847:{reason:'Smithsonian Gardens confirms that honey bees use a dance to communicate flower location. Specify a honey bee and classify the imagined individual episode as fiction; the factual dance remains grounded.',contentType:'narrative-fiction',text:'A honey bee found purple flowers. She drank from them, then flew back to her hive. Inside, she moved in a dance. Other bees watched. Her dance helped show them where the flowers were. Soon more bees flew across the garden. She had no paper map, but she had a way to share the place.',sources:['https://gardens.si.edu/gardens/pollinator-garden/why-what-when-where-who-how-pollination/']},
 s848:{reason:'Two named schools and their invented field-sharing schedule make a specific fictional example. Morning, later and Fridays are easy to follow; classify as fiction.',contentType:'narrative-fiction'},
 s849:{reason:'The three streets, tank and rain-dependent outcome are a fictional town episode. Remove the guarantee that rationing lasts until rain and frame it as an effort to make the supply last longer.',contentType:'narrative-fiction',text:'Three streets had little water in summer. People often waited with empty bottles. The town put a large water tank near the school. Each street chose two people to open it at set times. Families took only what they needed. This helped the water last longer while they waited for more rain. The tank belonged to the town, and people from all three streets cared for it.'},
 s850:{reason:'“The new route passed the market, the hospital. A large factory” is broken punctuation. Join the places in one grammatical sentence and classify this particular town route as fiction.',contentType:'narrative-fiction',text:'The old bus went to the market but not to the hospital. The town asked riders where they needed to go. Many people drew the same line on a map. The new bus route passed the market, the hospital, and a large factory. It could not stop at every house, but it helped more people reach places they used each day.'},
 s851:{reason:'The river bridge and first shared market are a fictional account of two towns. The metaphor that a bridge gives people a place to know each other is clear from the described meeting.',contentType:'narrative-fiction'},
 s856:{reason:'The Metropolitan Museum documents clay records of grain; the particular boy and writer are invented. Identify the setting, classify the account as fiction, and avoid saying the clay literally learned words.',contentType:'narrative-fiction',text:'Long ago in a town in Mesopotamia, a boy carried wet clay to a writer. The writer pressed small marks into it with a reed. The marks recorded how much grain a farmer had brought. The clay dried. Years later, someone could still read the marks. That small piece of clay held a message from the past.',sources:['https://www.metmuseum.org/art/collection/search/327384']}
};
const batch=[];
for(const [id,d] of Object.entries(decisions)){
 const s=stories.find(x=>x.id===id),p=prov.find(x=>x.id===id),a=audits.find(x=>x.id===id);
 if(!s||!p||!a||a.errors||s.level!==1||reviews.some(x=>x.id===id))throw Error('Unexpected source '+id);
 const before=structuredClone(s);
 if(d.text){s.text=d.text;s.wordCount=policy.countWords(s.text)}
 if(d.contentType)s.contentType=d.contentType;
 if(d.subtopic)s.subtopic=d.subtopic;
 const changed=Boolean(d.text||d.contentType||d.subtopic);
 if(changed){s.reviewedAt='2026-09-24';const check=policy.inspect(s);if(check.errors.length)throw Error('Learning policy '+id+': '+JSON.stringify(check));p.text_sha256=sha(s.text);p.status='editorial-revision-2026-09-24';p.evidence='content/editorial-batch-2.11.9h.json#'+id;p.note=d.reason;}
 batch.push({id,level:s.level,title:s.title,before,after:structuredClone(s),changed,reason:d.reason,sources:d.sources||[],review:'Individual full-text check of language, chronology, source fidelity, Level 1 fit and fact/fiction boundaries; AI-assisted editorial',beforeFlags:a.flags});
 reviews.push({id,contentDigest:gate.reviewDigest(s),language:'approved',facts:'approved',method:'AI-assisted-editorial',reviewedAt:'2026-09-24',note:d.reason,evidence:'content/editorial-batch-2.11.9h.json#'+id,warningDisposition:a.flags?`The ${a.flags} flag was evaluated in the full text. ${d.reason}`:`No automatic flags. Full text checked. ${d.reason}`,origin:'editorial-batch-2.11.9h'});
}
reviews.sort((a,b)=>Number(a.id.slice(1))-Number(b.id.slice(1)));
write('stories.json',stories);write('content/current-provenance.json',prov);write('content/review-progress.json',reviews);write('content/editorial-batch-2.11.9h.json',batch);
console.log('Reviewed',batch.length,'changed',batch.filter(x=>x.changed).map(x=>x.id).join(','));
